### ISSUE TITLE
Set challenge's validator number from settings

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1011]
Add a new setting  sc.yaml.storagesc.validators_per_challange.

In [addChallenge](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/challenge.go#L710) replace the number of validators from`alloc.DataShards` to the new setting `.validators_per_challange`.

We should also validate the partition size to be at least validators_per_challange.

**Comment by ma2b0043** [comment]
@sriep when can we expect to close this issue?

**Comment by peterlimg** [comment]
@Sriep isn't the validators number of challenge is calculated base on the data shards number and blobber numbers?

**Comment by Sriep** [comment]
@peterlimg Yes what you said was to be how it worked. The decision was then made to make validators a fixed number.
