### ISSUE TITLE
[FEATURE] Provide fee for transactions

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/0chain#1016]
Remove occurrences of hardcoded zeroes and replace with `min_fee`.

E.g.: 
```
// TODO: t.Fee needs to be compared to the minimum transaction fee once governance is implemented
	if config.DevConfiguration.IsFeeEnabled && t.Fee < 0 {
```
```
func (mc *Chain) createFeeTxn(b *block.Block) *transaction.Transaction {
	feeTxn := transaction.Provider().(*transaction.Transaction)
	feeTxn.ClientID = b.MinerID
	feeTxn.ToClientID = minersc.ADDRESS
	feeTxn.CreationDate = b.CreationDate
	feeTxn.TransactionType = transaction.TxnTypeSmartContract
	feeTxn.TransactionData = fmt.Sprintf(`{"name":"payFees","input":{"round":%v}}`, b.Round)
	feeTxn.Fee = 0 //TODO: fee needs to be set to governance minimum fee
	feeTxn.Sign(node.Self.GetSignatureScheme())
	return feeTxn
}

```
etc.

See:
- https://github.com/0chain/zwalletcli/issues/85
- https://0chain.slack.com/archives/G01FYNN6DK4/p1645097379703449

**Comment by samtholiya** [comment]
@Kishan-Dhakan how to get `min_fee` where is it stored or configured

**Comment by Kishan-Dhakan** [comment]
> @Kishan-Dhakan how to get `min_fee` where is it stored or configured

It's found in 0chain.yaml, also see https://github.com/0chain/0chain/pull/1028/files

**Comment by ma2b0043** [comment]
@Kishan-Dhakan @samtholiya when can we expect to close this issue?

**Comment by Kishan-Dhakan** [comment]
> @Kishan-Dhakan @samtholiya when can we expect to close this issue?

@ma2b0043 I am not working on this issue, I had created this issue as a requisite for https://github.com/0chain/system_test/issues/107. You can check with Yury or Peter for a better idea on the timeline.

**Comment by peterlimg** [comment]
Transaction fee is implemented in 0chain repo, while clients end need to finish the fee code.
