### ISSUE TITLE
Delete provider plus blacklist

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1020]
We need to be able to delete any provider ([miner](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L138), [sharder](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sharder.go#L158), blobber, validator or [athoriser](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/zcnsc/authorizer.go#L136)). Further we need to keep a record of deleted providers to prevent a deleted provider immediately rejoining the 0chain.

1. Add delete blobber smart contract endpoint.
  * Add a new field, `bool disabled` to a StorageNode.
  * A disabled blobber cannot be used for any new allocation.
 2. Add a `delete validator` smart contract endpoint.
  * Add a new field `bool disdabled` to ValidatorNode.
  * A disabled validator cannot be used to validate any new challenges.
3. Modify the `add provider` sc endpoints to not allow previously deleted providers to be added. 
 * As part of the validation process, ensure that the provider does not already exist with `disabled` set to `true`.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
