### ISSUE TITLE
Calling miners v1/client/put + random string returns miner basic JSON data (should error)

### ISSUE THREAD

**Issue by shaktals** [0chain/0chain#1022]
Playing around with the API to properly handle errors, I got the following:

![Selection_376](https://user-images.githubusercontent.com/24679343/155234584-c3ce0116-5525-4b59-bfe9-4f6c9d704849.png)

**Comment by peterlimg** [comment]
Any invalid http requests would be redirected to this page.

**Comment by shaktals** [comment]
This is very against standard REST API behavior.

@stewartie4 @Sriep @moldis do you agree with it?

**Comment by shaktals** [comment]
@peterlimg stating how things work today does not make the behavior correct.

**Comment by stewartie4** [comment]
Completely agreed @shaktals 
I think the key here is the webpage and REST API should be kept separate 
If we want to redirect any /web/x page to here then that's fine but the REST API should return a 404 with a JSON response as per REST standards
