### ISSUE TITLE
Move block reward constants to sc.yaml

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#1035]
Currently in block_reward, we use various constants for zeta, gamma calculation used to compute reward shares based on other variables. Once a user-friendly name is finalized, we should move these constants to sc.yaml in [`block_reward` section](https://github.com/0chain/0chain/blob/3fea102ed86641d30f5dcdf009b3c05ff0b1eab2/docker.local/config/sc.yaml#L150)
```
const (
		// constants for gamma
		alpha = 1
		A     = 1
		B     = 1

		// constants for zeta
		I  = 1
		K  = 1
		mu = 1
	)
```

**Comment by peterlimg** [comment]
@ssardana08 any updates for this?

**Comment by ma2b0043** [comment]
@ssardana08 when can we expect to close this issue?
