### ISSUE TITLE
Replace blobber in allocation, addition to update allocation

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1036]
Update allocation to have a new option to replace a blobber. This will take as input, a new blobber id, and the id of a blobber to be replaced.

After validation, the endpoint will remove active references to the old blobber from the allocations and add the new blobber.

The event database will need to be updated with new fields to indicate the last time each blobber was added or removed from an allocation. Also see https://github.com/0chain/0chain/issues/1037.

We will also need changes to GoSDK and zboxCLI to access the endpoint.  We can use the endpoint from https://github.com/0chain/0chain/pull/960 to suggest a replacement blobber.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
