### ISSUE TITLE
Round info diagnostics page panic

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1038]
Refresh page https://testnet1.devnet-0chain.net/miner02/_diagnostics/round_info several times, we will see panic as shown below:

goroutine 343060648 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa5
0chain.net/chaincore/chain.RoundInfoHandler.func1(0x154e280, 0xc002de1180)
	/0chain/go/0chain.net/chaincore/chain/handler.go:1254 +0x6e
panic(0x13259c0, 0xc0075baeb0)
	/usr/local/go/src/runtime/panic.go:971 +0x4c7
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0102d2780, 0x0, 0x0, 0x0)
	/0chain/go/0chain.net/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x7b4
go.uber.org/zap.(*Logger).DPanic(0xc00046c5f0, 0xc00a68a880, 0x3e, 0x0, 0x0, 0x0)
	/0chain/go/0chain.net/vendor/go.uber.org/zap/logger.go:217 +0x7d
0chain.net/chaincore/round.(*Round).GetMinerRank(0xc002e82900, 0xc0006d7a00, 0x0)
	/0chain/go/0chain.net/chaincore/round/entity.go:560 +0x754
0chain.net/chaincore/chain.RoundInfoHandler.func3(0x1, 0x0, 0x0)
	/0chain/go/0chain.net/chaincore/chain/handler.go:1341 +0x148
sort.insertionSort_func(0xc00c8b7360, 0xc00ad58d80, 0x0, 0xf)
	/usr/local/go/src/sort/zfuncversion.go:12 +0x88
sort.stable_func(0xc00c8b7360, 0xc00ad58d80, 0xf)
	/usr/local/go/src/sort/zfuncversion.go:171 +0xc5
sort.SliceStable(0x130f080, 0xc015d82ed0, 0xc00c8b7360)
	/usr/local/go/src/sort/slice.go:32 +0xec
0chain.net/chaincore/chain.RoundInfoHandler(0x154e280, 0xc002de1180, 0xc008334700)
	/0chain/go/0chain.net/chaincore/chain/handler.go:1337 +0x1177
0chain.net/core/common.Recover.func1(0x154e280, 0xc002de1180, 0xc008334700)
	/0chain/go/0chain.net/core/common/mdw_recover.go:42 +0xbb
net/http.HandlerFunc.ServeHTTP(0xc0005126f0, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/didip/tollbooth.LimitHandler.func1(0x154e280, 0xc002de1180, 0xc008334700)
	/0chain/go/0chain.net/vendor/github.com/didip/tollbooth/tollbooth.go:171 +0x244
net/http.HandlerFunc.ServeHTTP(0xc00ad58ce0, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
0chain.net/core/common.UserRateLimit.func1(0x154e280, 0xc002de1180, 0xc008334700)
	/0chain/go/0chain.net/core/common/rate_limter.go:50 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc0014935c0, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0x1a41160, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2448 +0x1ab
net/http.serverHandler.ServeHTTP(0xc000240460, 0x154e280, 0xc002de1180, 0xc008334700)
	/usr/local/go/src/net/http/server.go:2887 +0x22b
net/http.(*conn).serve(0xc0037a3d60, 0x15500b0, 0xc00f2c2200)
	/usr/local/go/src/net/http/server.go:1952 +0x1c25
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x96e

**Comment by ma2b0043** [comment]
@rrrooommmaaa as discussed, fix this bug in 2 days!
