### ISSUE TITLE
Providers

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1040]
# Provider

A provider is one of currently five objects that perform services for 0chian. There will be a linked wallet that can control the provider's settings. Each provider will also have a number of delegates; These are users that have invested 
tokens in the provider. 

Providers are given rewards when they perform services. These rewards are distributed amongst the delegates based on
creative stake size, the provider's control wallet can also get a fixed percentage of the reward as a service change.

## Commitment

While active each provider gains commitments to provide services.

- `Miners` produce blocks.
- `Sharders` stores the blockchain and other related data, such as the event database. They also support a query REST API.
- `blobbers` store user data files.
- `validators` validate challenges
- `authorizers` validate client transactions.

## Active and inactive

An active provider can take on new commitments while an inactive provider, for whatever reason, will not be able to take on any new commitments. Below are possible reasons for a provider to be inactive.

#### Envoirmental

If a provider is guaranteed to always fail its validation test to take on a new commitment we can consider it inactive.

An example of this might be if we reduced the maximum [max_challenge_completion_time](https://github.com/0chain/0chain/blob/staging/docker.local/config/sc.yaml#L71) this could result in blobbers with a higher [challenge_completion_time](https://github.com/0chain/blobber/blob/staging/config/0chain_blobber.yaml#L34) becoming inactive.

To help in this situation we will have an API endpoint that will return the active and inactive status of a provider. And indicate the reason. So in the example of `max_challenge_completion_time` above a blobber could run an [update_blobber_settings](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/sc.go#L259) transaction to reduce its challenge_completion_time and regain its active state.

#### Health check

Every so often a provider sends a heath check transaction. If the provider has not provided a health check in the required time it cannot take on any new commitments. This is similar to environmental inactivity, but for the [moment the health time is hard coded](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L22).

#### Shuts down

 A provider can send a `shut_down` transaction requesting that it be shut down. It no longer gets any new commitments. It is still expected to fulfil existing commitments and revives rewards as normal. Cannot be reversed.

#### Kill

A special user, the chain owner, can `kill` a provider by sending a kill transaction. This is similar to shut down but the provider no longer receives any rewards. This is irreversible.

#### Pending issues

New `am i active` API query https://github.com/0chain/0chain/issues/1041
Update provider settings https://github.com/0chain/0chain/issues/1042
Provider health check https://github.com/0chain/0chain/issues/1044
Provider shut down https://github.com/0chain/0chain/issues/1045
Killing provider https://github.com/0chain/0chain/issues/1046

**Comment by ma2b0043** [comment]
when can we expect to close this issue?

**Comment by Sriep** [comment]
make sure that inactive providers are NOT getting rewards. e.g.
1. inactive miners won’t generate, so its ok.
2. inactive sharders should not get rewards
3. inactive blobbers and validators should not get selected for allocation or validation
4. the validators get paid based on the challenge response ticket inclusion by blobber. So blobber waits for a second (chain configured) after receiving majority tickets and then collects all remaining validator response to send to the chain.
5. inactive authorizers should not get rewards - same as blobber, client waits for a second.
