### ISSUE TITLE
Update provider

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1042]
Each provider type should be able to update its settings. 

Changing settings on 0chain can result in a blobber becoming inactive, or unable to take on any new allocations. A blobber should have the option of rectifying this setting so that it can take on new allocations again.

We need to [update_blobber_settings](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/sc.go#L259) so that the [challenge_completion_time](https://github.com/0chain/blobber/blob/staging/config/0chain_blobber.yaml#L34) can be changed. 

We should also add any other missing settings that might be needed to reactivate a blobber - check allocation validation when issue resolved.

**Comment by ma2b0043** [comment]
when can we expect to close this issue?
