### ISSUE TITLE
Provider health check

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1044]
Every so often a provider sends a heath check transaction. If the provider has not provided a health check in the required time it cannot take on any new commitments https://github.com/0chain/0chain/issues/1040.

This functionally works for blobbers but is only partially implemented for other providers (miners, sharders, blobbers, validators and authorised. We wish to move the health check code into common code where possible.

1. A `?_health_check` smart contract endpoint for each provider. This will reset the LastHeathCheck member of a provider.
2. New health check period. A new validation check of this period against the time since the last health is to be provided, to be used before a provider commits to various tasks. 
3. The last heath check needs to be kept with the object in the MPT. This and summary stats of period passing or railing health checks can be updated in the event database after each health check.

#### Actions to be dependant on health checks
- `sharder` acquiring new blocks.
- `sharder` sending REST API queries.
- `miner` submitting new blocks of transactions.
- `authoriser` sing transactions
- `blobber` acquire new allocations
- `validators` selected to validate challenges.

**Comment by ma2b0043** [comment]
when can we expect to close this issue?
