### ISSUE TITLE
Provider shut down

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1045]
A provider should be able to deactivate itself. This can use common code associated with a new embedded object (Provider or ShutDownable)

- For each provider type, miner, sharder, blobber, validator and authoriser, we need a new `?_shut_down` transaction. This will set a new `ShutDown` field in the provider object stored in the MPT and mirrored in the event database. 
- If a provider is flagged as `shut_down` it will fail all validation to take on new provider commitments. However, it will still be expected to carry out existing commitments and will receive the full value for rewards and payments for doing so.
- Shutting a provider down is irreversible.
- There is a partial implementation for [miners](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L138) and [sharders](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sharder.go#L158) which can be copied and updated to work the new `shut_down` flag https://github.com/0chain/0chain/issues/499.  
- For an overview see https://github.com/0chain/0chain/issues/1040.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
