### ISSUE TITLE
Kill provder

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1046]
The owner or other selected user should be able to kill a provider. This can use common code associated with a new embedded object (Provider or Killable)

- For each provider type, miner, sharder, blobber, validator and authoriser, we need a new `kill_?` transaction. This will set a new `Killed` flag in the provider object stored in the MPT and mirrored in the event database. 
- If a provider is flagged as `killed` it will fail all validation to take on new provider commitments. It will also not be provided with any rewards or other paymetns.
- Killing a provider down is irreversible.
- There is a partial implementation for [miners](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L138) and [sharders](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sharder.go#L158) which can be copied and updated to work the new `killed` flag https://github.com/0chain/0chain/issues/499.  
- For an overview see https://github.com/0chain/0chain/issues/1040.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
