### ISSUE TITLE
Randomly shuffling partitions

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1050]
To  prevent Byzantine generation attacks we want to randomly shuffle partitions as used in blobber block rewards and challenge generation.

We add a shuffle partition item method to the [Partition interface](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/partitions/partition.go#L33)
1. We have a blobber Bk in Partition section Pk.
2. Randomly select a partition section Pi.
3. Swap the blobber Bkn in Pk with the a blobber Bin in partition section Pi.
4. Update B and B1 so they point to their new locations in the partition.

We can shuffle a blobber in the block rewards and challenge generation partitions during [verifyChallenge](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/challenge.go#L319).

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by ssardana08** [comment]
Currently partition shuffling logic might be needed at following places, but those are well handled with current implementation:
- generate_challenge: in generate_challenge the partitions are static, but the selection process is highly random, so we should not need shuffling.
- block rewards: block rewards partitions are dynamic. meaning they are created in n rounds, used in n+1th round only once and the discarded. as the partitions are dynamic on rounds and selection is randomness we won't need shuffling for now.

Hence, closing the issue
