### ISSUE TITLE
Bug Miners not displaying in every sharder api

### ISSUE THREAD

**Issue by samtholiya** [0chain/0chain#1051]
Miners not showing in sharder2 but getting listed in sharder1

**Comment by peterlimg** [comment]
Could be related to not synced events db or the duplicate keys that may be resolved by PR #1059 , @samtholiya can you check and see if this error still exists, thanks.

**Comment by ma2b0043** [comment]
@samtholiya when can we expect to close this issue?

**Comment by samtholiya** [comment]
This was resolved.
