### ISSUE TITLE
User read pools.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1062]
We want to allow allocations from which anyone can read. In our current implementation, to download from an allocation, a user would first have to create a read pool. This can lead to unlimited numbers of read pools which our current implementation cannot handle.

We replace the above with two read pools for each user.
1. OwnerReadPool A read pool to use for allocations of which the user is the owner.
2. VistiorReadPool  A read pool to pay to access allocation of which the user is not the owner.

We will need to remove all the existing code regarding read pools from staragesc.
The new read pool object can be a balance field 
```go
type readPool struct {
  Balance state.Balance
}
```
This can be keyed by either 
ownerKey = ADDRESS + encryption.Hash(userId + ":owner read pool")
visitorKey = ADDRESS + encryption.Hash(userId + ":visitor read pool")

We will want to change smart contracts as follows.
*   `free_allocation_request`: 
  1. Create ownerReadPool if it does not exist.
  2. Transfer free tokens to ownerReadPool.
*   `rp_lock`: new owner or visitor read pool.
  1. create owner or visitor read pool if it does not exist yet.
  2. transfer locked tokens from the user to the indicated read pool.
* `new_read_pool` unneeded can be removed.
* `read_pool_unlock` new token amount and owner or visitor pool flag.
  1. transfer tokens from indicated read pool to the user.
* `read_redeem`
  1. If the owner then transfer funds from the ownerReadPool.
  2. If not the owner then transfer funds from the user's vistiorReadPool.

We will also need a new readPool event database table, with userID and Balance fields.

**Comment by ma2b0043** [comment]
@sriep when can we expect to close this issue?
