### ISSUE TITLE
User write pool

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1064]
We want to limit the number of write pools an allocation has to handle. This is to avoid smart contracts that manipulate write pools taking too long, due to the number of write pools. With this end in mind, we require the following changes.

1. Each allocation will only have a write pool per.
2. Write pools will not lock for a duration, instead funds will be returned to the allocation owner when an allocation is closed or finalised.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
## Suggestion

Write pools are used to pay for uploads and min-lock-demand. uploads are paid only if the blobber passes challenges and min-lock-demand is paid only if rewards from uploads is insufficient.

Currently payment are paid from write pools at the moment they are needed. So on upload tokens are moved from linked write pools to the challenge pool, and moved back to the owner if challenges are not passed. Min-lock-demand paymeans are made when the allocation is closed, and is taken from linked write pools, so the combined write pools always need enough tokens to pay the min-lock demand.

In an effort to reduce write pool proliferation I suggest removing write pools completely and replacing with one allocation pool per allocation.

1. There is one allocation pool per allocation.
2. Anyone can fund an allocation's allocation pool.
3. When the allocation is cancelled or finalised the funds in the allocation pool are returned to the allocation's current owner.
4. New-allocation and update-allocation each confirm that there are enough tokens in the allocation's allocation pool to fund the min-lock-demand payment. Both transactions have a token field to allow top ups by the allocation's creator or updater respectively.
5. File uploads transfer funds from the allocation's allocation pool, to the challenge pool. Upload fails if there is insufficient funds.
6.  Funds from failed challenges are returned from the challenge pool to the allocation's allocation's pool.

The catch here might be that users that fund an allocation's allocation pool loose those tokens to the allocation's final owner (this partially happens anyway at the moment).  If all the allocations funders are consider agents of the same indivudal this might not be an issue. Also the main reason for this change is having limitless other users funding the allocation and having to remember all their details.

A third party software that funds allocations gets a bug where a for loop looses its terminating conditions, resulting in continuously creating write pools for all the software's allocations. This gets spotted fairly quickly but not before 0cahin grinds to a halt. (edited)

**Comment by Sriep** [comment]
# Suggestion II

### Currnet

The existing write pools
```go
type writePool struct {
	Pools allocationPools `json:"pools"` // tokens locked for a period
}
```
has a potentially unlimited number of allocation pools. This needs to change.

```go
type allocationPool struct {
	tokenpool.ZcnPool `json:"pool"`
	ExpireAt          common.Timestamp `json:"expire_at"`     // inclusive
	AllocationID      string           `json:"allocation_id"` //
	Blobbers          blobberPools     `json:"blobbers"`      //
}
```
There is no need to split allocation pools into blobber pools.

### Changes

1. Remove write pools and blobber pools and related code.
2. Use allocation pools, index by pool id. we already have a list of an allocation's allocation pools.
3. Have a maximum number of write pools per allocation. Allow the owner to unlock allocation pools.
4. Add an event database allocation pool table to provide for REST API queries regarding allocation and write pools.
