### ISSUE TITLE
Total stake should be saved in blobber

### ISSUE THREAD

**Issue by samtholiya** [0chain/0chain#1077]
We need to keep the[ total stake ](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L101)on the blobber object. Update the blobber each time it changes. Then we can use the equation from [cleanCapacity](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L226) directly in an SQL where clause.
So somewhere, [PR960](https://github.com/0chain/0chain/pull/960) or  [PR684](https://github.com/0chain/0chain/pull/684) or somewhere eilse, we need to add a TotalStake field to the blobber and update the object each time a stake changes - usually stakePoolLock and stakePoolUnlock.

https://0chain.slack.com/archives/C02QDMYFQJG/p1647819416329659

**Comment by ma2b0043** [comment]
@samtholiya when can we expect to close this issue?

**Comment by samtholiya** [comment]
@ma2b0043 I had raised the pr everything was working but due to some new changes, it is breaking. I am basically trying to debug staging now :(
