### ISSUE TITLE
Blockchain should timeout requests that have not been responded to in over 10 seconds

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/0chain#108]

**Comment by guruhubb** [comment]
Check allocation smart contract. It needs to execute it within 50ms or so ...thats the stretch goal. Then on the client end, it should timeout the request after 10s.

**Comment by bbist** [comment]
> Check allocation smart contract. It needs to execute it within 50ms or so ...thats the stretch goal. Then on the client end, it should timeout the request after 10s.

This will be partly handled by https://github.com/0chain/0chain/issues/104.

**Comment by bbist** [comment]
Regarding the smart contract REST API handlers as well as other endpoints, we could add a request timeout in context to for every endpoint as appropriate. Some endpoints inherently take longer than other. For example, state/get_nodes might take long time if too many state nodes are requested.
Anyway, it'll need further investigation.

**Comment by shravanshetty1** [comment]
We will just add a timeout middleware with configurable timeouts on both miner and sharder, also on the client in gosdk.

**Comment by shravanshetty1** [comment]
https://github.com/0chain/0chain/issues/285 - sub issue

**Comment by Sriep** [comment]
https://github.com/0chain/0chain/pull/400 fixes this for smart contracts

**Comment by Sriep** [comment]
Closed as fixed for smart contract. Raise as a separate issue if we need a timeout for REST API.
