### ISSUE TITLE
Limit the`string` field length on MPT object and the MPT object size 

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1085]
We don't have the size limitation for single object on MPT, which can be used by malicious nodes to attack the MPT. 

For example, the blobber `StorageNode` struct  looks like this:
```go
type StorageNode struct {
	ID              string                 `json:"id"`
	BaseURL         string                 `json:"url"`
        ...
}
```

Basically, the blobber can put as much data as it want in the `BaseURL` field, similar issue happens on all the MPT data structs. 

So we need to:
a) Check the object size before it goes into MPT, limit the length of `string` type for all the MPT data structs. 
b) In the MPT insert action, add the max allowed object size checking

**Comment by peterlimg** [comment]
@Dmdv  we only need to limit the MPT object size at the moment, checking the string length could be done `post-mainnet`, as we may need to do through msgp tag validation instead of checking all manually.

**Comment by Dmdv** [comment]
@peterlimg I agree, tag validation is more generic, it's no use in checking it imperatively in the code but declaratively

**Comment by Dmdv** [comment]
@peterlimg Regarding MPT object size, what would be an idea?
I guess, on every saving or when transaction is submitted with every insert?

**Comment by peterlimg** [comment]
@Dmdv the object size need to be checked with every insert, check here https://github.com/0chain/0chain/blob/a8f045c6d96a9f3c021a8126e5476236618024f7/code/go/0chain.net/core/util/merkle_patricia_trie.go#L133-L136
