### ISSUE TITLE
non-thread-safe on blobberHealthCheck

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#1112]
`blobberHealthCheck` is a high concurrency api if there are a lot of blobbers. but it is non thread-safe now. blobber.LastHealthCheck should save on isolated node on cassandra or eventdb's postgres instead of global node with ALL_BLOBBERS_KEY.
That is why some blobbers are lost sometimes on `./zbox ls-blobbers`. 
It also may cause `Not enough blobbers to honor the allocation` error even we have enough blobbers on network.

Another easier solution to add RWMutex on global Blobbers object.
```
func (sc *StorageSmartContract) blobberHealthCheck(t *transaction.Transaction,
	_ []byte, balances cstate.StateContextI,
) (string, error) {
	all, err := sc.getBlobbersList(balances)
	if err != nil {
		return "", common.NewError("blobber_health_check_failed",
			"Failed to get blobber list: "+err.Error())
	}

	var blobber *StorageNode
	if blobber, err = sc.getBlobber(t.ClientID, balances); err != nil {
		return "", common.NewError("blobber_health_check_failed",
			"can't get the blobber "+t.ClientID+": "+err.Error())
	}

	blobber.LastHealthCheck = t.CreationDate

	var i, ok = all.Nodes.getIndex(t.ClientID)
	// if blobber has been removed, then it shouldn't send the health check
	// transactions
	if !ok {
		return "", common.NewError("blobber_health_check_failed", "blobber "+
			t.ClientID+" not found in all blobbers list")
	}
	var found = all.Nodes[i]
	found.LastHealthCheck = t.CreationDate
	if _, err = balances.InsertTrieNode(ALL_BLOBBERS_KEY, all); err != nil {
		return "", common.NewError("blobber_health_check_failed",
			"can't save all blobbers list: "+err.Error())
	}

	err = emitUpdateBlobber(blobber, balances)
	if err != nil {
		return "", common.NewError("blobber_health_check_failed", err.Error())
	}
	_, err = balances.InsertTrieNode(blobber.GetKey(sc.ID),
		blobber)
	if err != nil {
		return "", common.NewError("blobber_health_check_failed",
			"can't save blobber: "+err.Error())
	}

	return string(blobber.Encode()), nil
}
```

**Comment by cnlangzi** [comment]
blocked by https://github.com/0chain/0chain/issues/1115

**Comment by Sriep** [comment]
Not sure this applies. The data for ls-blobbers comes from the event database now not the blockchain.

**Comment by cnlangzi** [comment]
@Sriep if so, the code still have thread-safe issue on https://github.com/0chain/0chain/blob/27e417dad41c6fd1484a66b16d5bb491cd72f976/code/go/0chain.net/smartcontract/storagesc/blobber.go#L306. It should also be fixed. I don't think this issue is fixed now.

**Comment by cnlangzi** [comment]
and `newallocation` doesn't work like you mentioned . see https://github.com/0chain/0chain/blob/27e417dad41c6fd1484a66b16d5bb491cd72f976/code/go/0chain.net/smartcontract/storagesc/allocation.go#L297

so this is a thread-safe issue for related blobber reading/writing.

**Comment by dabasov** [comment]
@cnlangzi why smart contract issue can be threadsafe? all data is stored in MPT which is thread safe and there are no concurrent execution of transactions atm

**Comment by Sriep** [comment]
[PR1245](https://github.com/0chain/0chain/blob/5a389c820b773b9a9648bf9b2e0de8003a9c9672/code/go/0chain.net/smartcontract/storagesc/provider.go#L9) redoes the blobberHealthCheck code. But I don't see the therad safe issue.
