### ISSUE TITLE
Action CONDUCTOR-STANDARD-TESTS falsely returns success

### ISSUE THREAD

**Issue by rrrooommmaaa** [0chain/0chain#1180]
as in https://github.com/0chain/0chain/runs/6052262819
"Standard Tests for Miners" resulted in a failure of one test.
"Standard Tests for Sharders" succeeded.

Overall result is shown as success, should be failure

**Comment by m-s-a-c** [comment]
I have created the gitactions to execute the script files that were already created by you. Example: ./docker.local/bin/start.conductor.sh miners
So, in case if any command in script is failing, it should also result in complete failure. As it is failing in the next step [CONDUCTOR-VIEW-CHANGE-TESTS](https://github.com/0chain/0chain/runs/6052945008?check_suite_focus=true#logs)
According to me it should be handled from scipt file only.

**Comment by fabioDMFerreira** [comment]
@rrrooommmaaa logs of the job you are pointing out are no longer available. I guess if "Standard Tests for Miners" fail it doesn't proceed to the sharder ones. At least it is what is happening here https://github.com/0chain/0chain/runs/6963655248?check_suite_focus=true.

@m-s-a-c has resolved this issue. Does it make sense to close this issue?

**Comment by rrrooommmaaa** [comment]
We don't know for sure what caused this issue. Perhaps, the conductor erroneously returned a success code when it should have returned failure. I'd suggest to review and re-organize the conductor flow-control code so that it returns the full summary upon exit, like normal software does, e.g.
```
Test a: Success
Test b: Failure
Test c: Not run
```
and then returns an exit code based on this summary in an obvious manner. Then we are safe to close this issue.

**Comment by service-0chain** [comment]
@dabasov 
For running standard test we are below 2 commands:
- bash ./docker.local/bin/start.conductor.sh miners
- bash ./docker.local/bin/start.conductor.sh sharders

https://github.com/0chain/0chain/actions/workflows/conductor-standard-tests.yml

What else is expected from my end in flow?

**Comment by fabioDMFerreira** [comment]
Nothing. It's all right.

This ticket is for the cases where tests fail. We want the conductor to show the status of all tests. Currently, we are only showing the status of the tests until the first test that failed. There's a fix on #1428

**Comment by service-0chain** [comment]
@fabioDMFerreira close this issue if it is fixed
