### ISSUE TITLE
Remove errors for context cancel

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1187]
Context cancel can happen during generating and verifying the block, if notarization is received before these actions are finished. Now interrupted actions (transaction calculation, block generation, verification etc) logs errors, it can be confusing for admins of miners/sharders

**Comment by peterlimg** [comment]
We can change it to `DEBUG` logs as we'll need to know what happened when issue happens

**Comment by dabasov** [comment]
Yeah, under "remove" I meant sort them out and log with DEBUG level

**Comment by dabasov** [comment]
fixed https://github.com/0chain/0chain/pull/1416
