### ISSUE TITLE
Update `/nodePoolStat` endpoint to return all (or pagniation) if param `pool_id` is not provided

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1188]
Currently, this API requires users to provide node id and a pool id to return a specified node pool. There's no way to list all the stake pools a node has, so we need to change the API to return all stake pools a node have or do it with pagination when the `pool_id` param is not provided, otherwise return the specified node pool. 

Check the discussion here: https://0chain.slack.com/archives/C03788G8N2D/p1650357692458329?thread_ts=1650351299.823269&cid=C03788G8N2D

**Comment by iamrz1** [comment]
Closed by https://github.com/0chain/0chain/pull/1192
