### ISSUE TITLE
0chain conductor tests.

### ISSUE THREAD

**Issue by service-0chain** [0chain/0chain#1198]
These tests will be written/modified by Roman or Dabasov Yuri.

- [x] Configure a separate server as a github runner.

- [x] Create its github actions to run these whenever required.

- [x] Run these github actions automatically on daily basis.

**Comment by guruhubb** [comment]
@m-s-a-c @rrrooommmaaa separate the conductor jobs and title them differently because faultTolerance, byzantine, and view-change are different tests, and can have them run them on different machines in parallel as they are independent.

**Comment by service-0chain** [comment]
Completed here --> https://github.com/0chain/0chain/pull/1244

**Comment by service-0chain** [comment]
@dabasov 
@rrrooommmaaa had created the 0chain conductor tests & @m-s-a-c have created gitactions for performing standard & complex scenarios conductor test. But conductor tests are failing due to some chain stuck issue as reported by @rrrooommmaaa.

gh actions --> https://github.com/0chain/0chain/actions/workflows/conductor-complex-scenarios-tests.yml
gh actions --> https://github.com/0chain/0chain/actions/workflows/conductor-standard-tests.yml

you will have to run manually to check for complex scenerios test like --> https://github.com/0chain/0chain/actions/runs/2314516663

After every run report is uploaded over to the gh action run. You can check it for analysing the errors.

**Comment by service-0chain** [comment]
also related to https://github.com/0chain/0chain/issues/465
