### ISSUE TITLE
Return list of delegate pools instead of map for `nodePoolStat`

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1206]
Please also update gosdk, zwallet, and related API document about the API changes.

**Comment by Sriep** [comment]
I am reworking this code and the matching system test as part of https://github.com/0chain/0chain/pull/1025, so any changes here might be immediately redone.  So it might be best to wait until https://github.com/0chain/system_test/pull/211 is finished.

**Comment by peterlimg** [comment]
@iamrz1 please help to fix this since #1025 is merged.

**Comment by iamrz1** [comment]
Closed by https://github.com/0chain/0chain/pull/1502
