### ISSUE TITLE
Triggered restartRound may not work properly

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#121]
When BC gets stuck, we can see logs of `round timeout` and `restartRound`, so if the round could restart correctly, we should see BC moves on. 

Apparently, we don't see it. I find miners are waiting for the VRF to meet the threshold. However, it never met. I can not see any miner sends VerifiedTickets to others. Sending VerifiedTickets only happens in `GenerateBlock` function, which may be called when restarting a round after timeout. However, it is not called at all, what it does is repeatedly do `RedVrfShare`.

**Comment by guruhubb** [comment]
The round_timeout generates a new VRF with timeout counter after hard reset. So it restarts round with same VRF  round_restart_mult times to make sure the VRF was received, and then increases the round timeout counter to send a new VRF share to everyone, and this process repeats until the timeout_cap is met, when the  VRF does not increment is sent over and over.  The reason to choose a new VRF is to prevent Byzantine miners from stalling the BC.
