### ISSUE TITLE
Use Max challenge completition time from gloabl config

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1230]
We set the max challenge completion time with the value get from the new allocation request, see code [here](https://github.com/0chain/0chain/blob/516789d037bf4c54636d703fdb7151267eca9876/code/go/0chain.net/smartcontract/storagesc/allocation.go#L321). This will complicate the challenge expiration implementation, and does not make sense. We should treat all the challenges the same that with the same max completion time, and get it from the global config.

**Comment by guruhubb** [comment]
I agree we should simplify and have a fixed CCT in global config for all blobbers across the network

**Comment by cnlangzi** [comment]
discussion on https://0chain.slack.com/archives/C03788G8N2D/p1654621796262099
