### ISSUE TITLE
ZCNSC global config not saved in MPT

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1238]
The config is not saved in MPT, the cost map is empty. See [config](https://dev.0chain.net/miner01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712e0/getGlobalConfig).

This will cause zcn SCs fail due to error 'can't get cost'.

**Comment by Dmdv** [comment]
Fixed in https://github.com/0chain/0chain/pull/1232
