### ISSUE TITLE
Tokens burn unexpectedly due to type casting

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1255]
Type casting in [DistributeReward](https://github.com/0chain/0chain/blob/ecc4c2fc7ad1ed95249e10d505aabf342c03e1fe/code/go/0chain.net/smartcontract/stakepool/stakepool.go#L183) cause burn tokens. Fix it and check if it is possible to add sanity checking for each transaction that the input tokens must be the same as the output tokens.

**Comment by ssardana08** [comment]
Closing this as it's duplicate of #319
