### ISSUE TITLE
Check if there are tokens burned after each transaction

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1270]
We need to check if transactions have tokens burned unexpectedly due to any reason, need to check code to confirm how this constraint checking could be implemented and applied.

Related issue #1255

TODOs:
- [x] For `send` transaction, verify that the sum of the original balances of `from` and `to` is equal to the sum of their updated balances after executing the transaction, including the fee.
- [x] Do balances checking for [DistributeRewards](https://github.com/0chain/0chain/blob/90c1cfc57e7c6fcf95aec36cbaf7b6096f68118b/code/go/0chain.net/smartcontract/stakepool/stakepool.go#L506) method, the input `value` that is going to be distributed must be the same as the sum of all tokens that are added to the pools.
- [x] For `mint` SC, assert that client won't get tokens beyond `max_mint`. Also, check the balances. 
- [x] Check the `burn` SC does not burn tokens overflow.

The `mint` and `burn` are checked in `transfer` the same as how `send` is processed.

**Comment by dabasov** [comment]
we can use benchmark tests to make sure that no tokens were really burnt, the idea is to track all the 
 mints of the run and assert that `sum_balances_before = sum_balances_after - mints`
