### ISSUE TITLE
Add filters to get top performing blobbers

### ISSUE THREAD

**Issue by shaktals** [0chain/0chain#1316]
As per [slack thread](https://0chain.slack.com/archives/C036CEH1L6P/p1653527871469819) on EventDB channel.

@ssardana08 suggestion there is that we use `num_chall_passed/total_chall`, but of course other metrics can be used too.

**Comment by Sriep** [comment]
Done in https://github.com/0chain/0chain/pull/1349

**Comment by Sriep** [comment]
Order by blobber capacity.
