### ISSUE TITLE
Remove unnecesary Event.Data encoding/decoding

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1327]
Change the [Event.Data](https://github.com/0chain/0chain/blob/2d587247e7168f494277f73970c2c1694b010ab5/code/go/0chain.net/smartcontract/dbs/event/event.go#L18) type from `[]byte` to `interface{}` and do type assertion to get concrete event data in [addStat](https://github.com/0chain/0chain/blob/2d587247e7168f494277f73970c2c1694b010ab5/code/go/0chain.net/smartcontract/dbs/event/process.go#L90). We don't need to do the JSON encoding/decoding work.

**Comment by cnlangzi** [comment]
@peterlimg  it impossible to convert Event.Data from string to interface{}. Because Event has to be loaded/saved in postgresql. `interface{}` can't work properly.

**Comment by peterlimg** [comment]
@cnlangzi we will need to remove the Event.Data field, it will not be used, so please remove it in the same PR too, thanks. cc @dabasov @Sriep
