### ISSUE TITLE
VerifyOutput should always be a valid json object for error

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#1332]
blobber is getting an invalid json on `VerifyOutput`.
```
"commit_connection_failed: malformed input: json: cannot unmarshal string into Go value of type storagesc.BlobberCloseConnection"
```

<img width="1118" alt="Screen Shot 2022-06-01 at 16 09 27" src="https://user-images.githubusercontent.com/347651/171358264-da29fb3f-88cf-4ded-8f0a-0e416b1e5952.png">

is it better to define a command struct for error instead of plaint text? eg

```json
{ "error": "commit_connection_failed: malformed input: json: cannot unmarshal string into Go value of type storagesc.BlobberCloseConnection" } 
```

blobber bug is reported on https://github.com/0chain/blobber/issues/706

**Comment by cnlangzi** [comment]
<img width="1311" alt="Screen Shot 2022-06-01 at 17 11 49" src="https://user-images.githubusercontent.com/347651/171370062-0eb557a2-a2e9-4115-abbc-cc84597f17fb.png">

**Comment by boddumanohar** [comment]
these function `VerifyOutput` are no longer available. Can you check and conform if you are stilling this issue. If not could you please close the ticket. Thanks.

**Comment by dabasov** [comment]
fixed output format in different PR, closing it
