### ISSUE TITLE
don't generate new challenge for expired allocation

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#1333]
please check if it stops to generate new challenge for expire allocation.

Question: should its challenge should be closed if an allocation expires?

`Finalize Allocation doesn't work` is reported on https://github.com/0chain/blobber/issues/704

**Comment by peterlimg** [comment]
Currently, the selected allocation expiration is not checked when generate the challenge, should be easy to fix @sum-it08 .

**Comment by ssardana08** [comment]
@peterlimg we already do this: https://github.com/0chain/0chain/blob/10f2aab46e48d144dc635a03854b1b5575aac08b/code/go/0chain.net/smartcontract/storagesc/challenge.go#L707

Please check it returns error and halts, if that's ok.
