### ISSUE TITLE
offline blobber should be skipped on new allocation request

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#1341]

**Comment by boddumanohar** [comment]
https://github.com/0chain/0chain/blob/5a1506ff070be2e92852fc7cc2acc57b8df7b153/code/go/0chain.net/smartcontract/dbs/event/blobber.go#L273-L275

 new allocation request, here we are already doing a check `last_health_check > 1h` 

Looks like this is already fixed. can any please conform.

**Comment by dabasov** [comment]
already fixed
