### ISSUE TITLE
Propose to fix slow MPT state pruning

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1348]
The current MPT state pruning process are a) it iterates through the whole MPT periodically to update all the MPT nodes version, then b) scanning the whole rocksdb to delete all nodes that below specific version. According to the local server testing, it takes about 10 seconds to go through the MPT for about 1.5millions rounds state. For b), it takes about 6 seconds to remove all the nodes below specific version. And that’s only about 4 days data. The prune process could be much longer when the network runs for weeks, months, etc. Someday it eat up all the resources to do the pruning, which is absolutely not what we want.

Anyway, after checking around, the following way might be the way we can go.

1. Collect the deleted nodes keys when finalizing blocks, together with the round number, and save them to rocksdb, perhaps a seperate db file, name it as dead_nodes. We can get the deleted nodes easily from the state change collector.
2. Setup a state prune worker that check the dead_nodes to get the keys of nodes that need to be pruned by comparing the node round number with the latest finalized block(LFB). Delete nodes with round number 100 rounds below the LFB, or perhaps more.
3. We might need to set a max size limit for the dead_nodes in case the new delete nodes generated faster than the prune process. So when the max size is reached, the prune process will be triggered immediately. Not sure if this is needed, but can be implemented if needed.

Related issue: 
- #1210

**Comment by dabasov** [comment]
@peterlimg just to check if I understood correctly.
1. we collect all nodes currently being finalized, with version equal to lfb and store them to the dead_nodes
2. after 100 rounds, when pruning, we check versions of these nodes, if versions changed, not a big deal we skip it, otherwise we prune it. it is safe to simply skip it, because if versions were updated this node was stored to other newer dead_nodes set

so we store a view of this nodes for further pruning, is it the plan?

**Comment by peterlimg** [comment]
@dabasov we will only collect deleted node key and round number and save to dead_nodes, new added nodes will not be collected. 

We don't need to update versions anymore, as updating the versions will need to scan all the nodes from the MPT root, which is the issue we are going to fix. So with the dead nodes, we will only need to check if the node round number in dead_nodes if 100 rounds below the LFB, then remove those nodes by keys from the MPT db, and update the dead_nodes.

**Comment by peterlimg** [comment]
Fixed by #1457
