### ISSUE TITLE
Get transaction hashes by file metadata

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1365]
A new REST API endpoint to return transaction hashes filtered by LookUpHash, Name or Contenthash. https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/writemarker.go#L29

**Comment by lawRathod** [comment]
Should this endpoint do: 
* Find on WriteMarker with LookUpHash/Name/ContentHash to get ClientId
* Find on Transaction using the ClientId from WriteMarker 

Return all transaction hash after find? 

If not then how are these two tables related (ClientId/ToClientId/BlockNumber)? Did I misunderstand the transaction hash in the context of this issue?

**Comment by Sriep** [comment]
transaction id is the same thing as transaction hash. We want to do something like. Except there might only be one or two fiters, so allow for one, two or three where conditions.
```sql
SELECT transaction_id FROM WriteMarker WHERE
  look_up_hash = ? AND
  name = ? AND
  content_hash = ?
```

**Comment by Sriep** [comment]
https://github.com/0chain/web-apps/issues/472

**Comment by Sriep** [comment]
transaction id is the same thing as transaction hash. We want to do something like the below, except there probably will be only one non-empty `where` condition.
```sql
SELECT transaction_id FROM WriteMarker WHERE
  look_up_hash = ? AND
  name = ? AND
  content_hash = ?
```
