### ISSUE TITLE
Total locked across pools

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1368]
We want a REST API endpoint to return the value of tokens locked across pools. This can have an optional filter to indicate pool type.
allocation pool, read pool, blobber stake pool, validator stake pool, miner stake pool, sharder stake pool and authoriser stake pool.

This is currently blocked by https://github.com/0chain/0chain/issues/1064.

**Comment by dabasov** [comment]
@lawRathod please verify that we have it already in snapshot table

**Comment by lawRathod** [comment]
Not yet available in snapshot table https://github.com/0chain/0chain/pull/1475, we may need to extend it by storing total locked for each stake pool and make possible the filtering.

**Comment by manasnisar** [comment]
@dabasov I see a `total_value_locked` in snapshots table, we also have a REST API for it, but I doubt it covers what's asked in the issue. Where is this needed?

**Comment by dabasov** [comment]
total_value_locked = locked_stake_pool + locked_read_pool + locked_write_pool
exactly what is needed
