### ISSUE TITLE
API endpoint `/transactions` response is not sorted

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1377]
The returned transactions are not sorted, please sort them by transaction timestamp. It does not make scene that we do pagination without sorting them. Also, please add new param to indicate the sorting order.

**Comment by droyson** [comment]
Can we add a query param as well to determine the sort order of the response. It will be great help to fetch recent transactions first.

**Comment by peterlimg** [comment]
@droyson yes, sure.
