### ISSUE TITLE
New cancellation charge

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1405]
Add a new cancellation charge

An allocation should have the full cost of an allocation in its write pool at all times. 

When an allocation is cancelled, a percentage of the full cost of the allocation is paid to the blobbers. The fraction given by a new smart contract setting.

**Comment by illuyankas** [comment]
@Sriep is this % fees a global settings constant? or unique to the blobbers involved in an allocation?

**Comment by guruhubb** [comment]
@Sriep 

Cancellation charge **replaces** min_lock_demand payment and is same to all the blobbers. It is a flat fee set in the global network config.

For new allocation, clients need to pay upfront the full amount of the allocation. Think of this as min_lock_demand set to 100% in the code.

**Comment by illuyankas** [comment]
@guruhubb @Sriep 

**(1) min_lock_demand definition conflict **

Not sure we can simply just change min_lock_demand to 100% in the code as afaik that would essentially by definition mean blobbers keep all tokens in the event of cancellation or finalization ... 

I presume we'd need to override the min_lock_demand function when it comes to cancelations or finalizations should we set it at 100%

**(2) Cancellation Fee Cliff  **

Having a global % cancellation fees is clean and predictable across the board but think it should be on a **cliff basis** so to avoid last minute cancellations, i.e **blobber starvation**! 

Suggestion - Either increase cancellation % fees from a global base amount as time on the allocation passes such that at expiry, cancellation is 100% OR have time cliffs OR don't allow cancellations after a certain time or combination thereof.

**Comment by Sriep** [comment]
We should add a new `global min charge` setting, which is the minimum that a blobber should be able to receive from an allocation irrespective of other factors.

**Comment by illuyankas** [comment]
@sriep @guruhubb	

I agree and think this charge should be paid upfront from the amount deposited by the client not at the end. Thinking of it as a commitment charge. 

Reason for upfront, is client can deprive blobber from block rewards if he doesn't write anything to the allocation and leaves it to expire, as blobber won't get challenged. 

This commitment charge can count towards the writes of the client (as credit with blobber) as blobber would want the client to write anyways to get challenges and block rewards. Maybe, this credit can be implemented as a discount on the blobber's nameplate write price.

**Comment by guruhubb** [comment]
@Sriep @dabasov  just so we're clear the blobber receives the cancellation charge regardless of whether the client writes or cancels their allocation and the allocation expires. The blobber can finalize upon expiry and receive the cancellation charge like it was before with min_lock_demand.

The change that I asked for is to decouple min_lock_demand from cancellation_or_expiration_fee to make it simple for compute, 
a) min_lock_demand is a global universal setting for all blobbers, which is initially set to 100%, 
b) cancellation_charge is global universal setting for all blobbers, where the blobber gets the charge regardless of whether the client cancels or lets the allocation expire and have one of the blobbers finalize the allocation to collect the charge.

**Comment by Sriep** [comment]
So just to be clear. We are not replacing the min lock demand but adding a new payment. So the blobber will now get both a min lock demand `AND` a cancellation charge.

**Comment by illuyankas** [comment]
@sriep I think the confusion may be stemming from what min_lock_demand means - it's the amount the client should lock (100%) not the amount the blobber would get. 

As to what the blobber should get: 

Let Cancellation_Charge = 0.2

1- In case of early cancellation, the blobber would get **remaining_tokens*Cancellation_Charge**

2- In case of expiry, if the allocation expires AND the client has not used at least (**Threshold = min_lock_demand*Cancellation_Charge**) then the blobber gets (**Threshold - used_tokens**) otherwise nothing as blobber has already received more than the Threshold. 

This is my understanding. CC @guruhubb

**Comment by sculptex** [comment]
I thought allocation duration/expiry was removed, some of the above comments seem to make no sense in this case?

**Comment by guruhubb** [comment]
I talked to @sum-it08 to sort it all out. There is a lot of confusion and this is the wrong forum for a discussion.
Also we have not removed allocation duration/expiry.

**Comment by dabasov** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/5922236/184214635-1760fa91-e8bf-4b40-a260-0d74037b3e7d.png">
