### ISSUE TITLE
Missing free storage space info in response of `/getStakePoolStat`

### ISSUE THREAD

**Issue by lawRathod** [0chain/0chain#1431]
* The `free` field in the response is always 0 because it's not calculated while generating response https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/handler.go#L927-L965
* free storage = staked storage space - allocated storage space, how to know staked storage space info for a blobber? 
* Will it make sense to include `staked_storage` and `unstaked_storage` also in response of this query? 
* unstaked_storage =  blobber capacity - staked storage, should `stakePoolStat` model have these new fields? Should blobber model have this info?

**Comment by Sriep** [comment]
1. The `Free` field seems to have been orphaned. We should remove it or repurpose it.
2. Does anyone need to know the free storage from `getStakePoolStat`?  It requires continually updated information.
3. It depends on whether anyone wants that information? If the Atlus explorer team need it they will ask.
4.  Same as (3)

**Comment by lawRathod** [comment]
The mobile team needs either `staked_storage` or `unstaked_storage` to display staking opportunity on blobbers.

**Comment by manasnisar** [comment]
@dabasov Already done. I can see both `stake_total` and `unstake_total` in the response. Should I close this?
