### ISSUE TITLE
Generic search API for clients

### ISSUE THREAD

**Issue by lawRathod** [0chain/0chain#1480]
The API accepts query as parameter and return eventsdb data if query is one of the following:
* BlockHash
* Round no
* transaction_hash,
* file_name
* content hash
* Wallet address

Requirement for: https://github.com/0chain/web-apps/issues/473, https://github.com/0chain/web-apps/issues/472

**Comment by peterlimg** [comment]
https://github.com/0chain/0chain/pull/1441#discussion_r921086747
