### ISSUE TITLE
build.miners.sh: --dev flag leads to standard_init_linux.go:219: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by bbist** [0chain/0chain#149]
While running the image build using build.miners.sh with --dev flag enabled, on ubuntu 20.10 container crashes with following error.
```
standard_init_linux.go:219: exec user process caused "no such file or directory"
```
The build script seems to build the image on local system and copy it to alpine based image.

This issue could be addressed by moving the go build step inside docker build stage.

**Comment by mallochine** [comment]
in codereview

**Comment by mallochine** [comment]
merged.
