### ISSUE TITLE
blank page on getblobbers url in both miner/sharder

### ISSUE THREAD

**Issue by service-0chain** [0chain/0chain#1494]
@dabasov @peterlimg 

complete blank page is there when we click on getblobbers url for both miner/sharder example[https://dev-mobile.devnet-0chain.net/sharder01/v1/screst/6dba10422e368813802877a85039d3985d[…]a85039d3985d96760ed844092319743fb3a76712d7/getblobbers](https://dev-mobile.devnet-0chain.net/sharder01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/getblobbers)

here `/v1/screst/6da…` is getting appended twice.

**Comment by peterlimg** [comment]
This is a known issue that I mentioned before, mainly the wrong URL address, the correct one should be https://dev-mobile.devnet-0chain.net/sharder01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/getblobbers

**Comment by ssardana08** [comment]
@service-0chain `v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7` repeating twice in your URL

**Comment by service-0chain** [comment]
@sum-it08 @peterlimg 
yup, can you look why is it getting appended twice itself.

**Comment by ssardana08** [comment]
how can it get appended itself. How to reproduce this..
try clicking on link @peterlimg shared.. it's working exactly fine

**Comment by cnlangzi** [comment]
@sum-it08  steps are reported on https://0chain.slack.com/archives/C01GMABG2T1/p1657869406684049?thread_ts=1657644614.850819&cid=C01GMABG2T1

**Comment by ssardana08** [comment]
Looks like all `href` are wrong.
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/103603196/179173756-0d915b7b-429c-48a6-b484-0d8c80ba14d5.png">

**Comment by boddumanohar** [comment]
tested on latest staging image works fine. closing it.
