### ISSUE TITLE
/getStakePoolStat inconsistant with GoSDK

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1497]
[getStakePoolStat](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/handler.go#L1070) assumes the blobber_id parameter is the id of the blobber of which you want the stake pool stats.

zbox and [GoSDK](https://github.com/0chain/gosdk/blob/staging/zboxcore/sdk/sdk.go#L321) assume that no blobber id means we want all the stake pools belonging to the client. We have not implemented this in 0chain.  If we were to implement this we would want to use another parameter, say `user_id` when we  trigger this alternative functionality.

**Comment by lawRathod** [comment]
We have another endpoint called `/getUserStakePoolStat` which accepts `client_id` as parameter and returns all the delegate pools belonging to the client. Is it something that satisfies the requirement? 

The two endpoints are:
1. `/getUserStakePoolStat` to get delegate pools of the client
2. `/getStakePoolStat` to get blobber stake pools for the blobber id

**Comment by Sriep** [comment]
Yes, I believe `/getUserStakePoolStat` is working ok. ...

[zbox sp-info](https://github.com/0chain/zboxcli/blob/staging/cmd/stakepool.go#L89) if there is no blobber id input, an empty blobber id is used.

[GoSDK GetStakePoolInfo](https://github.com/0chain/gosdk/blob/staging/zboxcore/sdk/sdk.go#L289) No blobber id is treated as client id.

So `zbox sp-info` with no blobber id assumes the user is the blobber. Likely not a useful default and is slightly confusing but not urgent to fix.

**Comment by Sriep** [comment]
Slightly confusing but not urgent closing.
