### ISSUE TITLE
Remove `block.max_block_size` from 0chain.yaml

### ISSUE THREAD

**Issue by ssardana08** [0chain/0chain#1505]
Block generation should only be only dependent on block cost: `max_block_cost`
and hence remove `max_block_size`.

and smartcontracts have cost to be used.

**Comment by boddumanohar** [comment]
`max_block_size` is used to calculate `transactionCacheSize` which is used to determine blockchain transaction cache size.

https://github.com/0chain/0chain/blob/f0e47248610e12558cf90b60b56c471c89a8623d/code/go/0chain.net/sharder/chain.go#L38-L41

if we are planning to remove `max_block_size` then we should have some other ways to determine transaction cache size.
