### ISSUE TITLE
Add miner refactor

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1511]
[AddMiner](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L54) calls `getMinerList` three times, and again [verifyMinerState](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L314), from
https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L62 and https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L129

We should refactor these down to one.

**Comment by boddumanohar** [comment]
@dabasov PR is merged. can we close this ticket now? Thanks

**Comment by Sriep** [comment]
Fixed in https://github.com/0chain/0chain/pull/1699
