### ISSUE TITLE
Blobber snapshot table to hold blobber specific history metrics

### ISSUE THREAD

**Issue by lawRathod** [0chain/0chain#1529]
Blobber snapshot table will store blobber state per round 

This is to support Chimney requirements for historic data:
* https://github.com/0chain/web-apps/issues/623
* https://github.com/0chain/web-apps/issues/619
* https://github.com/0chain/web-apps/issues/618
* https://github.com/0chain/web-apps/issues/617
* https://github.com/0chain/web-apps/issues/615
* https://github.com/0chain/web-apps/issues/606

Will keep updating for more APIs

**Comment by manasnisar** [comment]
@dabasov We already have both `blobber_aggregates` and `blobber_snapshots`. I'm assuming that's what was asked here. Should I close this?
