### ISSUE TITLE
[Aggregates] Uptime for providers

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1535]
Add uptime for providers based on health check

**Comment by Sriep** [comment]
How is this information being used? A single statistic of total time or maybe some sort of graph. Is adding a total uptime field to providers good enough?

**Comment by Sriep** [comment]
Needs kill, shutdown, health check Pr https://github.com/0chain/0chain/pull/1439

**Comment by devyetii** [comment]
Shouldn't this be done as #1933 is closed ? @Sriep
