### ISSUE TITLE
Challenges from interval

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1540]
Add fields to [Challnge](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/challenge.go#L14) table.
* The data the challenge was resolved
* pass or fail

These values can be added to the `TagUpdateChallenge` emitted from verifyChallenge. https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/challenge.go#L534 and https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/challenge.go#L600

We need an rest endpoint that will return all challenges for a blobber over an interval.

**Comment by dabasov** [comment]
fixed in snapshots
