### ISSUE TITLE
Remover blobber information from MPT

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1544]
We should remove[ StorageNode.Information](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L347) field. This information should only be kept in the event database.

**Comment by dabasov** [comment]
using events_db to store some data is not a good way to go, events_db is for events but not for any data that can’t be placed in MPT, we should not misuse it

**Comment by Sriep** [comment]
So we should just keep the information on the blobber? The important thing is to keep unbounded string fields out of the MPT.

**Comment by dabasov** [comment]
I think, that we can move it to the 0box and store all UI related info there 
@guruhubb @peterlimg what do you think?
