### ISSUE TITLE
Add challenge pools to event database

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1575]
We should add the challenge pool to the event database. We can add to the [event.Allocation table](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/allocation.go#L16).

Change to [getChallengePoolStat](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/handler.go#L670).

**Comment by dabasov** [comment]
https://github.com/0chain/0chain/blob/a1c3312a7d5db50288780a0652c0474fc5694734/code/go/0chain.net/smartcontract/storagesc/handler.go#L773

**Comment by dabasov** [comment]
eature/snapshots
