### ISSUE TITLE
The `WZCNNonceMinted` in zcnsc.GlobalConfig is unbounded

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1581]
https://github.com/0chain/0chain/blob/315118ed18660e32a7b2b79e34b040a5da79784f/code/go/0chain.net/smartcontract/zcnsc/nodes.go#L41-L45

Which will cause performance issue when the map is huge as we will need to encode/decode each time we have mint/burn tokens

**Comment by dabasov** [comment]
@YarikRevich why did you change it to post mainnet?

**Comment by YarikRevich** [comment]
@dabasov missclick, sorry

**Comment by peterlimg** [comment]
Use partitions to store the nonces to fix the unbound single MPT node.

**Comment by peterlimg** [comment]
closed via #2604
