### ISSUE TITLE
Remove storage allocation TimeUnit

### ISSUE THREAD

**Issue by ssardana08** [0chain/0chain#1601]
- StorageAllocation struct has a property called `TimeUnit`
- We should get rid of this field as it's always coming from config. We can directly fetch from config and use it

**Comment by iamrz1** [comment]
TimeUnit is used in instances where config is not passed down as a parameter or inside the receiver, ie:
https://github.com/0chain/0chain/blob/e0f4108ffc4b7be2232fcad7c1812cd8cfbeef04/code/go/0chain.net/smartcontract/storagesc/models.go#L1169
