### ISSUE TITLE
Privacy report endpoint and support using markers 

### ISSUE THREAD

**Issue by lawRathod** [0chain/0chain#1609]
Brief: 
1. Need to be able to generate privacy report for an file/folder using the lookup-hash
2. Store info about the CRUD action in a column on eventsdb in respective marker tables.
3. The report will include the client CRUD actions on a file w.r.t to time.
4. The file to writemarker association data already exists but readmarkers cannot be associated to a file yet. 
5. Need an endpoint on storagesc to fetch the report.

**Comment by lawRathod** [comment]
Depends on https://github.com/0chain/0chain/issues/1610

**Comment by lawRathod** [comment]
Depends on https://github.com/0chain/gosdk/issues/570

**Comment by guruhubb** [comment]
We can close this because we're doing it at the blobber end. @lpoli

**Comment by lpoli** [comment]
This will be implemented in the blobber. Blobber can charge client based on whether they subscribe for gdpr reporting.
Generating gdpr from writemarkers will pressurize sharder on both cpu and memory consumption.
