### ISSUE TITLE
Push-to-gitlab needs fixing

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#161]
The [push-to-github](https://github.com/0chain/0chain/blob/master/.github/workflows/push-to-gitlab.yml) pull request check is broken and needs fixing.

At the moment it seems to be erroring with
```shell
debug1: Exit status 1
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The check was disabled in PR https://github.com/0chain/0chain/pull/160

**Comment by guruhubb** [comment]
Is this issue closed @satchinjoshi ?

**Comment by satchinjoshi** [comment]
@guruhubb we can close this
