### ISSUE TITLE
Transaction type when commiting blobber copy, move, delete, upload or rename.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1610]
Depends on https://github.com/0chain/blobber/issues/476. 

https://github.com/0chain/0chain/pull/1453 added boolean toggles to [Storage allocation](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L660) to allow for upload, download, move, copy, rename and delete.  https://github.com/0chain/blobber/issues/476 will implement this in the blobber and also return the type of action in the expanded WriteMarker object sent to the [commit_connection](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/sc.go#L185) transaction.

We need to add code to [commitBlobberConnection](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L590) to verify the action being done with the new  [Storage allocation](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L660)  fields; we should probably use an enumerated type here. We also want to include this new field in the event database [WriteMarker](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/writemarker.go#L11) table.

**Comment by lawRathod** [comment]
Should close after https://github.com/0chain/gosdk/issues/570

**Comment by guruhubb** [comment]
This is taken care at the blobber side. See https://github.com/0chain/blobber/pull/891
