### ISSUE TITLE
Do not return error if activePassedBlobberReward partitions is empty

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1617]
Instead of returning error and be included in a block as chargeable error transaction, we can just return nil as it's just no blobber are ready to be rewarded yet.

https://github.com/0chain/0chain/blob/7dbf89a8596daa7896931544a918dd361ea94092/code/go/0chain.net/smartcontract/storagesc/block_reward.go#L71

Related transaction error:

DEBUG   chain/state.go:275      Error executing the SC, chargeable error        {"error": "empty list, no items to return", "client id": "bfa64c67f49bceec8be618b1b6f558bdbaf9c100fd95d55601fa2190a4e548d8", "block": "3e3a6843cafa66ed06258f38fde8a45144c2232f8e8ef6380fb6be8bcb78c326", "begin client state": "4961438cd5195a74b99036ddd6319243b078c2004f2b36a97e2776621acc9305", "prev block": "5e183d116e48404dda679f05d0b24fec05965f7637b71334485640064e2955f7", "time_spent": "295.561<C2><B5>s", "txn": {"hash":"174be30587de3db6bad38542a7e9c0dca8f8f83170f9a0200677dc192054c350","version":"1.0","client_id":"bfa64c67f49bceec8be618b1b6f558bdbaf9c100fd95d55601fa2190a4e548d8","public_key":"aa182e7f1aa1cfcb6cad1e2cbf707db43dbc0afe3437d7d6c657e79cca732122f02a8106891a78b3ebaa2a37ebd148b7ef48f5c0b1b3311094b7f15a1bd7de12","to_client_id":"6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7","chain_id":"0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe","transaction_data":"{\"name\":\"blobber_block_rewards\",\"input\":{\"round\":8760}}","transaction_value":0,"signature":"31a033d6d8d31d6b43046f1ce1eadd50e0941b790275912db96a01066e9dea92","creation_date":1661338664,"transaction_fee":0,"transaction_nonce":4371,"transaction_type":1000,"transaction_output":"empty list, no items to return","txn_output_hash":"256c53103d55a99c9ffc9c40afcce2e22b3981b6f63cb3dffb44873698b9ce08","transaction_status":2}}

**Comment by boddumanohar** [comment]
@peterlimg  this has been fixed on staging:

https://github.com/0chain/0chain/blob/5a1506ff070be2e92852fc7cc2acc57b8df7b153/code/go/0chain.net/smartcontract/storagesc/block_reward.go#L70-L74

please check if this solves the issue
