### ISSUE TITLE
Add round numbers to rest api endpoints

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1618]
Add round number to [nodeStat](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L56).

Other endpoints to be added ...

**Comment by boddumanohar** [comment]
https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L40-L60

None of these endpoints are returning any data: All of them are returning empty page:

sample URL: https://dev.0chain.net/miner01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d9/getDkgList

**Comment by boddumanohar** [comment]
@Sriep  what is the usecase of adding round number to `/nodeStat?id=<miner-id/sharder-id>` ?

the typical output returned is:

```
{
  "simple_miner": {
    "id": "776d48b254d64473fce3e3de311fb23e1db739a49282f6dc6d68b67ef9df90ac",
    "n2n_host": "dev.0chain.net",
    "host": "dev.0chain.net",
    "port": 31201,
    "geolocation": {
      "latitude": 28.6448,
      "longitude": 77.216721
    },
    "path": "miner01",
    "public_key": "58da230fa504cc1ec4fd44399aa69347636f50704597014b3a64f661ffd6f31097847609e88283aa4a5e972f42aa1f395cc07266ac2df219f8ddb315a9060b9f",
    "short_name": "localhost.m01",
    "build_tag": "543f3a3f4402bdd48b1562d6faf349c9880f633d",
    "total_stake": 30929,
    "delete": false,
    "node_type": "miner",
    "last_health_check": 1663153610,
    "last_setting_update_round": 0
  },
  "stake_pool": {
    "pools": null,
    "rewards": 6359808000000,
    "settings": {
      "delegate_wallet": "776d48b254d64473fce3e3de311fb23e1db739a49282f6dc6d68b67ef9df90ac",
      "min_stake": 0,
      "max_stake": 1000000000000,
      "num_delegates": 20,
      "service_charge": 0.1
    },
    "minter": 0
  }
}
```

**Comment by dabasov** [comment]
@boddumanohar I think the idea is to add round_number to responses. not sure it will be possible to get the consensus on response then.

@Sriep where is it used by the way?

**Comment by Sriep** [comment]
We can probably consider done for the moment in https://github.com/0chain/0chain/pull/1627.
