### ISSUE TITLE
Remove blobber information

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1626]
StorageNode.Information, we don't need to store this in the MPT. Need to confirm whether we need this in the event database. Remove as necessary from transactions and objects.

```go
// Info represents general information about blobber node
type Info struct {
	Name        string `json:"name"`
	WebsiteUrl  string `json:"website_url"`
	LogoUrl     string `json:"logo_url"`
	Description string `json:"description"`
}
```

**Comment by dabasov** [comment]
https://github.com/0chain/0chain/pull/1612 fixed here
