### ISSUE TITLE
Return error rather than change limit silently

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1640]
https://github.com/0chain/0chain/blame/staging/code/go/0chain.net/smartcontract/common/pagination.go#L43
```go
		if limit > DefaultQueryLimit {
			limit = DefaultQueryLimit
		}
```
For example
```url
http://localhost:7171/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/get_blocks?content=full&start=99&end=147&limit=48&limit=48&offset=0
```
Returns only 20 times as the limit is being silently changed to DefultQueryLimmit = 20 , thus leading to a Gotcha which is likely to get everyone using the 0chain pagination for the first time.

Rather than silently change the limit to 20 when it is too large, we should return a `limit, 48, too high cannot exceed 20 error`.  Then each user will know what is going on rather than get confused.

**Comment by Sriep** [comment]
We should add an endpoint that returns settings like the upper bound on pagination. This will allow the user to use the limit in there own code.

**Comment by uneet7** [comment]
I can pick this up

**Comment by uneet7** [comment]
What would be the right place to implement the API that will return pagination settings @Sriep ?

**Comment by Sriep** [comment]
```
What would be the right place to implement the API that will return pagination settings @Sriep ?
```
There isn't one. 

I guess we can put it in `minersc` for the moment.
