### ISSUE TITLE
Block and staking rewards for a blobber

### ISSUE THREAD

**Issue by sagchain** [0chain/0chain#1647]
I see end points for block rewards and staking rewards, if both are same based on Siam's explanation then not sure why we get different values.

More context here: https://0chain.slack.com/archives/C03UX0USFQC/p1662054872417119

**Comment by lawRathod** [comment]
What endpoints would that be?

**Comment by sagchain** [comment]
@realrisman can you share the end points we are using for block rewards?

**Comment by Sriep** [comment]
What do you mean you get block rewards automatically? There is a collect reward smart contract transaction that moves rewards into the user's wallet. At this point block rewards and other rewards have been merged.

There are various endpoints that query objects for information that includes reward information that merges both block rewards and other reward types.

**Comment by realrisman** [comment]
@sagchain block rewards -> `graph-blobber-service-charge` and staking -> `graph-blobber-total-stake`.

Sorry I'm not following this issue and I can't open the slack link, so I'm not sure what is this issue about.

**Comment by manasnisar** [comment]
@dabasov This one's pretty vague. I can't open the slack link here, I don't know if this is a valid issue anymore

**Comment by dabasov** [comment]
it is `total_service_charge` and `total_stake` it is different values simply
