### ISSUE TITLE
Fix empty fields in /v1/screst getWriteMarkers

### ISSUE THREAD

**Issue by YarikRevich** [0chain/0chain#1659]
There should not be such empty fields

"User": {
"ID": 0,
"CreatedAt": "0001-01-01T00:00:00Z",
"UpdatedAt": "0001-01-01T00:00:00Z",
"DeletedAt": null,
"user_id": "",
"txn": "",
"balance": 0,
"round": 0,
"nonce": 0
},
"Allocation": {
"ID": 0,
"CreatedAt": "0001-01-01T00:00:00Z",
"UpdatedAt": "0001-01-01T00:00:00Z",
"DeletedAt": null,
"allocation_id": "",
"allocation_name": "",
"transaction_id": "",
"data_shards": 0,
"parity_shards": 0,
"size": 0,
"expiration": 0,
"terms": "",
"owner": "",
"owner_public_key": "",
"is_immutable": false,
"read_price_min": 0,
"read_price_max": 0,
"write_price_min": 0,
"write_price_max": 0,
"challenge_completion_time": 0,
"start_time": 0,
"finalized": false,
"cancelled": false,
"used_size": 0,
"moved_to_challenge": 0,
"moved_back": 0,
"moved_to_validators": 0,
"time_unit": 0,
"num_writes": 0,
"num_reads": 0,
"total_challenges": 0,
"open_challenges": 0,
"successful_challenges": 0,
"failed_challenges": 0,
"latest_closed_challenge_txn": "",
"write_pool": 0,
"User": {
"ID": 0,
"CreatedAt": "0001-01-01T00:00:00Z",
"UpdatedAt": "0001-01-01T00:00:00Z",
"DeletedAt": null,
"user_id": "",
"txn": "",
"balance": 0,
"round": 0,
"nonce": 0
}
}

**Comment by lawRathod** [comment]
This doesn't seem to be a valid writemarker. What would be the steps to reproduce it?

**Comment by YarikRevich** [comment]
Here is the steps to reproduce this error:

**Comment by YarikRevich** [comment]
- Create a new allocation
- Upload some file(there is no difference, with "commit" flag or not)
- Perform a request to "/v1/screst/getWriteMarkers" and you'll see those empty fields

**Comment by devyetii** [comment]
Tried this locally and giving the same results. Investigating the issue ...

**Comment by devyetii** [comment]
Looks like "User" and "Allocation" are stored properly in the database (events_db). It should be a problem with loading them as relations to the writeMarkers.

**Comment by devyetii** [comment]
The problem is genuinely related to the version we're using of gorm, where Preloads are not working properly. What I'll be doing is that I'll use Joins instead of Preloads but this has the limitation of nested associations.
