### ISSUE TITLE
Get sharders from the MPT

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1674]
We distribute rewards to all miners and sharders obtained from magic block, which seems to be incorrect. Before we enable the veiw-change protocol, miners and sharders are always in the list, so even if they are offline, we will pay rewards to them. See code https://github.com/0chain/0chain/blob/b2c07e09f818b453f1a3ff3f69f087f440491f6a/code/go/0chain.net/smartcontract/minersc/fees.go#L482
the getBlockSharders is getting sharders from magic block
https://github.com/0chain/0chain/blob/f622fb6fbc5636eaaf05d3acbae57647b24b560a/code/go/0chain.net/chaincore/chain/entity.go#L889-L903
it should be selected form MPT instead, by this key
https://github.com/0chain/0chain/blob/f622fb6fbc5636eaaf05d3acbae57647b24b560a/code/go/0chain.net/smartcontract/minersc/models.go#L83

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/0chain/pull/1684
