### ISSUE TITLE
How about to add a setup_network.sh call to restart_from_scratch.sh

### ISSUE THREAD

**Issue by andrenerd** [0chain/0chain#168]
Experiencing an issue running restart_from_scratch.sh:
https://github.com/0chain/0chain/blob/master/quickstart/1s_2m_4b/reliable/restart_from_scratch.sh

As pointed in the readme, this script should all the instances (blobbers/miners/sharders/...). Meanwhile there is an issue, see the attached screenshot. I guess it appears as a result of not calling setup_network.sh from restart_from_scratch.sh or otherwise, to create the network explicitly with SPECIFIC ip.

<img width="938" alt="Screenshot 2021-04-06 at 23 25 59" src="https://user-images.githubusercontent.com/3892914/114106494-2c129680-98cf-11eb-80c2-d9492a58fb2c.png">

PS. Im a newbie to the project, so maybe the issue is caused by my misuse of instructions from the readme.

**Comment by andrenerd** [comment]
Hi @andriykutsevol 
please, check

**Comment by andriykutsevol** [comment]
Yes, it was a flaw.
