### ISSUE TITLE
msgp checking does not work

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1687]
https://github.com/0chain/0chain/actions/runs/3075659642/jobs/4969292009#step:4:358

The msgp check will always pass as it does not work as expected, i.e compare if there are changes after running msgp.

**Comment by boddumanohar** [comment]
when github actions checkout a repo, https://github.com/0chain/0chain/blob/staging/.github/workflows/unit-test.yml#L40
it should checkout while preserving the `.git` folder contents. 

But here we get `Not a git repository` error. 

```Wrote and formatted "stakepool_gen.go"
[357](https://github.com/0chain/0chain/actions/runs/3118229242/jobs/5057371718#step:4:358)
Not a git repository
[358](https://github.com/0chain/0chain/actions/runs/3118229242/jobs/5057371718#step:4:359)
To compare two paths outside a working tree:
[359](https://github.com/0chain/0chain/actions/runs/3118229242/jobs/5057371718#step:4:360)
usage: git diff [--no-index] <path> <path>
```

**Comment by Manali-Jain-squareops** [comment]
@boddumanohar  https://github.com/0chain/0chain/pull/1703
