### ISSUE TITLE
Parallel loops, error messages need to be deterministic.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1688]
Examples of parallel for loops:
[fetchStorageNodePlusStake](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L423) [fetchPools](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L481) [getStakePoolsByIDs](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L727) [getAllocationBlobbers](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L767) [blobberBlockRewards](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/block_reward.go#L81). There may be others.

If multiple errors are found in these loops, then the error is random. For example, we might have both `value not present` and other times `node not found`. We should sort the errors found and return an order list.

Probably be best if we could do this in common code to reduce the chance of this confusion being reintroduced in the future.

**Comment by peterlimg** [comment]
Closed via #1729
