### ISSUE TITLE
Read pool depletion

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1697]
details for that wallet if anyone wants to investigate:-
id: f9446b941277057835b2b589edbc934844dcc8cd8c368ac7d7454ce1d0bf181c
allocation: 9ae5f83621c9821801d0ae8de3f55f2dd2e3d55705e69536b18e3f1841e8357b
seed phrase:
wink,option,away,state,arrow,nominee,lazy,phone,denial,remove,street,where,lens,share,fever,effort,gloom,breeze,damp,diagram,skin,book,elephant,liberty
wink option away state arrow nominee lazy phone denial remove street where lens share fever effort gloom breeze damp diagram skin book elephant liberty

**Comment by dabasov** [comment]
https://0chain.slack.com/archives/C01GMABG2T1/p1663906424166649

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/gosdk/pull/587
