### ISSUE TITLE
Investigate 0chain /storage_config issues

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1700]
[storagesc.SettingNames ](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/config_settigns.go#L127)max_write_price is repeated

When you do ./zwallet sc-config, which calls /storage-config the following are missing
missing field time_unit, index 1
missing field min_alloc_duration, index 3
missing field max_challenge_completion_time, index 4
missing field min_offer_duration, index 5
missing field stakepool.min_lock_period, index 10
missing field free_allocation_settings.duration, index 17
missing field challenge_enabled, index 31
missing field expose_mpt, index 47
missing field owner_id, index 48
missing field cost, index 49

**Comment by iamrz1** [comment]
@Sriep From my testing only the `stakepool.min_lock_period` was missing because it was not in the hander response, so I have added it. 
I dont see `expose_mpt` and `cost` fields mentioned anywhere in latest staging branch. Could they have been removed?
