### ISSUE TITLE
Minimum number of challenge validators must respected

### ISSUE THREAD

**Issue by fabioDMFerreira** [0chain/0chain#1711]
A challenge must be validated by `the number of data shards assigned to the allocation + 1` validators. If we don’t have enough validators, we should return an error instead of continuing. 

Add the verification in the next place.
https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/challenge.go#L881

**Comment by guruhubb** [comment]
Needs to be a fixed number of validators, say 10, for every challenge, randomly selected. The number 10 should be a setting in sc.yaml. cc @dabasov

**Comment by fabioDMFerreira** [comment]
@guruhubb so, we should rely on `validators_per_challenge` specified in `sc.yaml` instead of the formula above `the number of data shards assigned to the allocation + 1`.

We need to ensure the `validators_per_challenge` in validator conductor tests has the value 3.

**Comment by guruhubb** [comment]
Yes @fabioDMFerreira its fixed globally irrespective of number of shards.  We need to ensure there are enough validators to generate a challenge and I think we do that check (@dabasov )

**Comment by devyetii** [comment]
@guruhubb I can't find any file named `sc.yaml`. Please where is this global config stored (about `validators_per_challenge`)

**Comment by fabioDMFerreira** [comment]
@devyetii `docker.local/config/sc.yaml`

**Comment by devyetii** [comment]
Since the ids of the validators are generated randomly, can't we just set the minimum of the length of the generated list be always `conf.ValidatorsPerChallengs` ? @guruhubb @fabioDMFerreira
