### ISSUE TITLE
Remove float64 fields from MPT.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1712]
We want to remove float64 fields from the MPT. 

[storagesc/Config](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/config.go#L93) has several float64 fields, for example 
```go
	ValidatorReward float64 `json:"validator_reward"`
	// BlobberSlash represents % (value in [0; 1] range) of blobbers' stake
	// tokens penalized on challenge not passed.
	BlobberSlash float64 `json:"blobber_slash"`


	// allocation cancellation
	CancellationCharge float64 `json:"cancellation_charge"`

	// ChallengeGenerationRate is number of challenges generated for a MB/min.
	ChallengeGenerationRate float64 `json:"challenge_rate_per_mb_min"`
```

The [miner object's geolocation fields ](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/models.go#L668)are float64s
```go
type SimpleNodeGeolocation struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}
```

There are likely other examples.

We need to decide on a deterministic way of representing these float64 fields.

**Comment by dabasov** [comment]
consider https://pkg.go.dev/math/big and Rat

**Comment by Sriep** [comment]
We should distinguish between ratios and other fields. 

Ratios and fractions stored as [big.Rat](https://pkg.go.dev/math/big#Rat).

Some file sizes are stored in `GB` as float64, where they should probably be stored in `bytes` as [big.Int ](https://pkg.go.dev/math/big#Int).

**Comment by Sriep** [comment]
We should also consider reworking [currency.Coin](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/currency/currency.go#L54) as big.Int, so can handle token values over a billion.

**Comment by peterlimg** [comment]
Saving the float64 value in MPT is not a problem, see https://0chain.slack.com/archives/C03788G8N2D/p1665377414139449?thread_ts=1665140945.823189&cid=C03788G8N2D
