### ISSUE TITLE
Probable fix for 0dns building script

### ISSUE THREAD

**Issue by andrenerd** [0chain/0chain#172]
There is an issue i experience building 0dns. Please check the attached screenshot.

Seems the building script works well for other users, but not for me. So i see no other way to complete the build except making a minor tweak in docker files:
https://github.com/0chain/0chain/blob/ee5704d2617f42dcf857270cf73be44a9e5c523b/quickstart/1s_2m_4b/config/reference/0dns/docker.local/Dockerfile
https://github.com/0chain/0chain/blob/ee5704d2617f42dcf857270cf73be44a9e5c523b/quickstart/1s_2m_4b/config/1s_2m_4b/0dns/docker.local/Dockerfile
... and potentially other ones, where there are similar instructions (there are many).

To replace this line:
```
    make -C bls -j $(nproc) install && \
```

with:
```
    make MCL_DIR=../mcl -C bls -j $(nproc) install && \
```

<img width="726" alt="Screenshot 2021-04-08 at 19 22 35" src="https://user-images.githubusercontent.com/3892914/114254813-0ca06a00-99b2-11eb-9763-8f859fc50ac4.png">

**Comment by andrenerd** [comment]
Hi @andriykutsevol,
please, check.

**Comment by guruhubb** [comment]
You can't use MCL yet as we use bls from herumi, but possible in future for clients.

**Comment by mallochine** [comment]
actually bls uses mcl underneath. That's why Shigeo talks about the mcl implementation so much.

**Comment by mallochine** [comment]
dunno seems like a network error, you can see in that screenshot there is a `wget -O - https://github.com/herumi/mcl/archive/master.tar.gz | tar xz` that should've created the mcl directory

Actually looks like @andrenerd  is already pretty much there with the fix so I'm gonna reassign this to him. I don't think I would know this any better than he does.

**Comment by andriykutsevol** [comment]
Did you follow the /quickstart/1s_2m_4b/readme.txt
base / git_pull_all.sh
config / compare_wdirs.sh
config / patch.sh
reliable / restart_from_scratch.sh

**Comment by andriykutsevol** [comment]
I have already commited the setup_nwetwork.sh and added it to the reliable/restart_from_stratch.sh

**Comment by andriykutsevol** [comment]
I just tried those steps on my localhost, it works.
But I did not clear a docker cache.

So try these steps again.

If this does not work, then most likely some external libraries (C / C ++), or scripts were changed.

Because the script /config/compare_wdirs.sh eliminates the difference in the docker.local directories for:
0Chain, 0dns and blobber.
