### ISSUE TITLE
Bug: using empty config

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1731]
[This](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L1174) bit of code does not make sense.
```go
func (sa *StorageAllocation) Until() common.Timestamp {
	var conf = Config{}
	return sa.Expiration + toSeconds(conf.MaxChallengeCompletionTime)
}
```
The value of conf.MaxChallengeCompletionTime should be taken from the conf read from the MPT, not some disguised zero value. We should check that this does not occur anywhere else.

**Comment by peterlimg** [comment]
Closed via #1738
