### ISSUE TITLE
Restart miner/node may re-Initial state on genesis block

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1755]
See code below, the smart contract balance will be reset to the value in `init_state.yaml` when nodes (miner/sharder) get restarted, rather we should check if the balance node does exist first to avoid resetting on restarting.
https://github.com/0chain/0chain/blob/047a6fa6d55a7a8dff3e088668abfc633e604cf6/code/go/0chain.net/chaincore/chain/entity.go#L564-L568

**Comment by dabasov** [comment]
I guess the problem is that we call `SetupGenesisBlock` on every start which is not correct, we should avoid calls completely if genesis block is already set.
```
	gb := mc.SetupGenesisBlock(viper.GetString("server_chain.genesis_block.id"),
		magicBlock, initStates)
```

**Comment by peterlimg** [comment]
@dabasov yes I agree that we should avoid setup genesis block on every start

**Comment by K-Kumar-01** [comment]
@peterlimg @dabasov 
Is there any way to check if the genesis block has already been set up? If so, what would `gb` variable be assigned in such a case?
I saw a `started` field in the `chain` struct that can be used for this process, but I am unsure whether we can use it as such

```
var gb
if mc.started==0
gb = mc.SetupGenesisBlock(viper.GetString("server_chain.genesis_block.id"),
		magicBlock, initStates)
else
// cannot think of how variable will get value here
```
