### ISSUE TITLE
Miners/Sharders nodes could be added without limitation

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1769]
We don't have any limit for adding miners or sharders to the the nodes list, malicious users could attack the network by adding lots of faked nodes to the list.

**Comment by devyetii** [comment]
I guess this could be solved by adding a global config variable `max_miners / max_sharders` and check for it during the view change process.

**Comment by devyetii** [comment]
There's a functions in the system that should do this behavior. However, it's never called (I tried using print debugging).
For the miners : https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/models.go#L848
