### ISSUE TITLE
Parallelise conductor tests and prevent conductor tests from running in parallel in the same server

### ISSUE THREAD

**Issue by fabioDMFerreira** [0chain/0chain#1773]
1. Parallelise conductor tests
- [ ]  Miners and sharders standard tests can run separately https://github.com/0chain/0chain/blob/staging/.github/workflows/conductor-standard-tests.yml
- [ ] 3 Blobbers suits can run separately https://github.com/0chain/0chain/blob/staging/.github/workflows/conductor-blobber-tests.yml

2. Prevent conductor tests from running in parallel on the same server
- [ ] Ensure scheduled jobs do not overlap in the same server
- [ ] Have in mind some jobs may take more than one hour to run.

3. Other
- [ ] Remove unnecessary pipeline https://github.com/0chain/0chain/blob/staging/.github/workflows/conductor-blobber-3-tests.yml as tests are already running on blobbers pipeline
- [ ] Send slack notifications if some of the next pipelines fail
* https://github.com/0chain/0chain/blob/staging/.github/workflows/conductor-no-view-change-tests.yml
* https://github.com/0chain/0chain/blob/staging/.github/workflows/conductor-blobber-tests.yml
* https://github.com/0chain/0chain/blob/staging/.github/workflows/conductor-standard-tests.yml
- [ ] Conductor tests may fail from time to time due to the space occupied by docker. We need to run `docker system prune` from time to time or add a clean-up task in each pipeline.

**Comment by shahnawaz-creator** [comment]
Waiting to merge this [PR](https://github.com/0chain/0chain/pull/1784)
