### ISSUE TITLE
Fix benchmark generation to avoid failed blobber stake

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/0chain#1812]
For doing a loadtest run with loaded MPT, using benchmark code causes issues with blobber staking.

Acceptance criteria: Blobber staking works when using benchmark code to load the MPT.

**Comment by boddumanohar** [comment]
The repeated loadtests can be considered as our loaded MPT tests only. As explained before by Peter, bechmark cannot be used to load the MPT

**Comment by boddumanohar** [comment]
The repeated loadtests can be considered as our loaded MPT tests only. As explained before by Peter, bechmark cannot be used to load the MPT
