### ISSUE TITLE
Event database changes should allow exactly one of add or update

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1826]
Throughout the event database, we have code that updates the table if the object is in the event table, otherwise adding it. 

This is wrong, the event database code should either 
1. Update an object in the event database and return an error if it is not present.
2. Add an object to the event database and return an error if it is present.

The key point is that in the smart contract that emitted the event we **know** if we are adding or updating. So we should either emit an event that updates an object and returns an error if it is missing or emit an event that adds an object and gives an error if it is already present. We should never emit an event that could do either add or update.

The problem with the current situation is:
1. Extra resources are used to allow either option - add or update.
2. The code is confusing as it leads new developers to think we should be doing either operation. Resulting in this bug perpetuating itself. And leading to further confusing code and possibly bugs.
3. In a live situation there should never be an actual mixup. It's a blockchain, so if we try to add over an existing object or update a non-existing object - it is either a developer bug, or we are pointing to a bad event database. If this happens, then we have the following problems.
4. Adding when we want to update fills the database up with dud objects.
5. Updating when we want to add will corrupt existing objects.
6. By not returning an error, we make it much more likely a problem will be missed in testing and find its way into live code.

We should start replacing the code when appropriate and stop repeating the bug.

**Comment by peterlimg** [comment]
Yes, I agree that `insert` and `update` need to be separated, but the current batch update impl will do `insert` if the item does not exist, so in order to separate that, we need to figure out how to do batch update on existing items only first.

**Comment by dabasov** [comment]
fixed with UpdateBuilder
