### ISSUE TITLE
Logo upload

### ISSUE THREAD

**Issue by stewartie4** [0chain/0chain#1830]
Used for logo upload:
![Züs--Color=Color, Mark=False](https://user-images.githubusercontent.com/18306778/203391445-0455ac3a-afe9-4a66-bdfe-091add197102.svg)
![Züs--Color=Color, Mark=False@Large](https://user-images.githubusercontent.com/18306778/203391515-41f14c36-9b24-460d-be94-bee1744a8ff2.png)

**Comment by boddumanohar** [comment]
@stewartie4  can you please provide more details about the scope of this ticket? thanks.

**Comment by stewartie4** [comment]
No scope - I just needed somewhere to host the above image so created an issue so I could upload it
