### ISSUE TITLE
Blobber `open_challenges` are sometimes negative

### ISSUE THREAD

**Issue by devyetii** [0chain/0chain#1843]
I'm running a local network on WSL (Ubuntu 20.04) + Docker with:
- 1 Sharder
- 3 Miners
- 2 Blobbers

I was working on a task regarding the sharder API Endpoints. One of them was unsuccessful because `event.Blobber.open_challenges` was casted to `uint64` and turns out it was negative in my DB. All I did since I setup a new clean network was to register a wallet, add 6 ZCNs to it using faucet, add an allocation and upload a file to it.

cc @boddumanohar @dabasov

**Comment by dabasov** [comment]
duplicates #1945
