### ISSUE TITLE
strage bug on open_challenges

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#1881]
allocation_fetch_error: Error fetching the allocation.internal_error: can't convert to storageAllocationBlobbers: error retrieving blobbers from db: sql: Scan error on column index 33, name "open_challenges": converting driver.Value type int64 ("-31") to a uint64: invalid syntax

**Comment by cnlangzi** [comment]
it can be reproduced to stop some blobbers for a while.

**Comment by boddumanohar** [comment]
@cnlangzi the steps to reproduce are not clear. Could you please clarify on the step to reproduce the issue.

**Comment by cnlangzi** [comment]
@boddumanohar try it on local
- start 2 sharders
- start 4 miners
- start 2 blobbers
- don't start any validator
- stake tokens on blobbers
- create wallet, and get test tokens
- create allocation
- upload file
- stop blobber 1 for a few minutes
- start blobber 1
- try do any operation on the allocation

**Comment by cnlangzi** [comment]
it is reported on https://github.com/0chain/0chain/issues/1843 again.

**Comment by dabasov** [comment]
duplicates https://github.com/0chain/0chain/issues/1945
