### ISSUE TITLE
Remove sharder endpoints from miners and miner endpoints from sharders

### ISSUE THREAD

**Issue by stewartie4** [0chain/0chain#1916]
Due to a shared codebase:
- every miner endpoint listed on api.zus.network can be called on a sharder
- every sharder endpoint listed on api.zus.network can be called on a miner

Many times, these calls do not work as they are not intended to be called on a miner/sharder 
Sometimes they do work, but are flakey and are not guaranteed to work 

This causes confusion, and could lead apps to be built against the incorrect service, as we have seen with our own apps.

Acceptance criteria:
- Compile a list of miner and sharder concerns 
- Ensure only endpoints required for those concerns are accessible on the miner/sharder sservice 
- Chat to @stewartie4 to update api.zus.network
- Ensure our gosdk, wasm and all apps still work after this separation of concerns

**Comment by stewartie4** [comment]
Could whoever is assigned to this ticket please reply here with how the miner/sharder endpoint split should be? I will update the docs

**Comment by stewartie4** [comment]
focusing on system tests for now

**Comment by Sriep** [comment]
**Do we have an example of a sharder only endpoint that can be accessed from a miner or vis versa?**

The endpoints from the [smart contract ](https://github.com/0chain/0chain/tree/staging/code/go/0chain.net/smartcontract)and [sharder](https://github.com/0chain/0chain/tree/staging/code/go/0chain.net/sharder) packages can only be accessed from sharders. The endpoints from the miners package can only be accessed from [miners](https://github.com/0chain/0chain/tree/staging/code/go/0chain.net/miner); As far as I can tell, these looks ok. For endpoints elsewhere in 0chain, how do we determine if they should be accessed from miners, sharders or both?

**Comment by Sriep** [comment]
Handlers are split into packages and SetupHandlers routine for a package sets up the handlers for that package. For miners these are setup in [miners.initHandlers](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/sharder/sharder/sharder.go) and sharders in [sharder.initHandlers](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/miner/miner/miner.go#L457).

To remove the handlers from the miner and sharder we only need to remove the relevant setupHandlers call from the respective initHandlers method.

The packages handlers are currently split between miner and sharder as follows.

Both
config, node, chain-state, diagnostics, block, chain-node

Sharer only
config-development, sharder, smartcontract-rest-api, chain-sharder

Miner only
chain-miner, miner, transaction, client

**Comment by Sriep** [comment]
These endopints can be reached from both sharder and miner
#### [config](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/config/handler.go#L14)
/v1/config/get

#### [node](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/node/handler.go#L17)
/_nh/whoami
/_nh/status
/_nh/getpoolmembers

#### [chain-state](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state_handler.go#L62)
/v1/client/get/balance
/v1/scstate/get
/v1/scstats/
/v1/screst/
/_smart_contract_stats

#### [diagnostics](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/diagnostics/handler.go#L15)
/_diagnostics/info
/v1/diagnostics/get/info
/_diagnostics/logs
/_diagnostics/n2n_logs
/_diagnostics/mem_logs
/_diagnostics/n2n/info
/_diagnostics/miner_stats
/_diagnostics/txns_in_pool
/_diagnostics/block_chain

#### [block](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/handler.go#L13)

#### [chain-node](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/n2n_handler.go#L21)
/_nh/list/m
/_nh/list/s

**Comment by boddumanohar** [comment]
2 items are pending on the UI side: 

- [ ] remove register client
- [ ] get_client should be on sharder
