### ISSUE TITLE
Uptime for providers

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1933]
We need to show uptime of the provider

- move LastHealthCheck to Provider instance and remove it from particular provider
- add uptime (unix) field to Provider 
- every time LastHealthCheck is updated check and increase uptime (TagUpdateBlobberAllocatedHealth event)
- add aggregate to each provider aggregate table with uptime
```go 
if curr.LastHealthCheck - prev.LastHealthCheck < HealthCheckPeriod + const {
   uptime += LastHealthCheck - prev.LastHealthCheck 
}
```
const can be reasonably small, not more than `HealthCheckPeriod`
example
```
curr.LastHealthCheck = 20:25
prev.LastHealthCheck = 20:00
HealthCheckPeriod = 5min
const =1min

25min > 6min {
    //uptime is not set
}
```

**Comment by devyetii** [comment]
@dabasov I suggest moving `HealthCheckPeriod` to a config file (maybe 0chain.yaml), it's now just const variables named `HEALTH_CHECK_TIMER` in miner and sharder workers.

**Comment by devyetii** [comment]
As per DM thread with @dabasov :
1.  Extract changes from #1946 related to Downtime.
2. Only keep `CreatedAt` and `Downtime` for Provider in events_db, Uptime will be calculated from them.
3. If T2 and T2 are two successive timestamps when a provider sent a HealthCheck beat, and if `T2 - T1 > HealthCheckPeriod` (the default/expected period between health checks), we will just take `downTime  = T2 - T1 - HealthCheckPeriod`.

**Comment by peterlimg** [comment]
We need to have a health check worker that will mark providers status as `offline` when we found they do not send health check in time. In that way,  we don't need to check if the `T2 - T1` > `HealthCheckPeriod`, instead we check if the provider is online, and return the time since the `CreatedAt` or return `0` or `status` as `offline` to indicate the provider is not available right now.

**Comment by devyetii** [comment]
@peterlimg Good Point. I want to add that Downtime tracks the amount of time during which the provider was offline, so it should be tracking this provider even if it goes offline then returned online. We perform the `> HealthCheckPeriod` whenever the provider sends a health check request as part of the handler of this request. It checks if the duration between two successive health checks exceeds the default duration and adds the difference in duration to the total downtime of the provider. Although we still need a worker to track the status of the provider, we'll still need the accumulation of provider's downtime.
