### ISSUE TITLE
All API endpoints do one event database SQL query.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1940]
All 0chian API queries that provide a view to the event database should be combined into one query. 

The problem is that if we do more than one query in an endpoint, we cannot guarantee that they will return data from the same round. Leading to mismatched data being returned.

**Comment by Sriep** [comment]
One example: There are a few places where we check for existence before doing an update, these need to be removed as the object could be added or removed between the existence check and the update.

**Comment by dabasov** [comment]
transactions does not guarantee read consistency, phantom reads are possible, please read https://www.postgresql.org/docs/current/transaction-iso.html
