### ISSUE TITLE
OpenChallenges are negative

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1945]
OpenChallenges can't be negative, most likely update is broken
```
{"code":"internal_error","error":"internal_error: cannot get blobber listsql: Scan error on column index 31, name \"open_challenges\": converting driver.Value type int64 (\"-226\") to a uint64: invalid syntax"}
```
related commit https://github.com/0chain/0chain/commit/4db016c625600e1188c69a3660a325210e8a585e

> The 1-expiredN means add one new open challenge and remove expiredN open challenges, it’s not the final result, and should be added to the current open challenge number, but the TagUpdateBlobberOpenChallenges process code just simply set the total open challenge as the 1-expiredN , which is wrong.

related discussion
https://0chain.slack.com/archives/C03788G8N2D/p1671805735260109

**Comment by cnlangzi** [comment]
it was reported https://github.com/0chain/0chain/issues/1881
