### ISSUE TITLE
github.com/spf13/viper is not thread safe

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#195]
We use [viper](https://pkg.go.dev/github.com/spf13/viper) to control project configuration settings. Unfortunately, the viper package is not inherently threadsafe, so we have to implement our own race protection.

The unit test [fs_store_test.go](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/sharder/blockstore/fs_store_test.go) gives illistration of viper data race issues. For example [FSBLockStore.read](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/sharder/blockstore/fs_store.go#L167) is unsafe.

Also, there is no unit test for it, but [updateConfig](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/miner/miner/handler.go#L60) looks problematic.

**Comment by Sriep** [comment]
Suggestions:
Control all access to the `spf13/viper` package through our own threadsafe viper object.

Write a unit test for `0chain.net/miner/miner/handler.go`.

**Comment by platsko** [comment]
In progress
