### ISSUE TITLE
Logs clean up

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1963]
Logs should not contains huge block of data that flush the logs too fast. Logs such as

- `INFO    block/block_eventdb.go:50       finalize block event    {"block": `
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/54137706/210491577-470bfe21-05b8-493c-8d82-c3baf04fc8b3.png">

- ` DEBUG   event/blobber_aggregate.go:106  getting ids`
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/54137706/210491653-3d45ee9c-f74f-4e6f-b40d-d16b4d061209.png">

**Comment by devyetii** [comment]
Fixed in #1988 . I'll do a little bit of scanning for any other like logs.
