### ISSUE TITLE
cleanup collaborator feature

### ISSUE THREAD

**Issue by boddumanohar** [0chain/0chain#2010]
https://0chain.slack.com/archives/C04EFTQH26T/p1672685897151809?thread_ts=1672261246.092239&cid=C04EFTQH26T

at the moment, collab features allows a non owner to update a file. As per the current writemarker implementation, for any changes to the allocation, writemarkers need to be signed by the owner. Because of this collab feature is not working properly. 

So can cleanup collaborator feature so that way, all modifications to the files should be done by the owner only.

**Comment by stewartie4** [comment]
@boddumanohar so collaborator feature is removed now?
