### ISSUE TITLE
Error log on finalized block save changes panics

### ISSUE THREAD

**Issue by devyetii** [0chain/0chain#2013]
Reported by @Manali-Jain-squareops , sharder panics with the following error
```
panic: finalize block save changes failed

goroutine 85331523 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc006a33110, {0x17d23e0, 0xc000d85d60, 0xb14ea0})
        /0chain/code/go/0chain.net/vendor/go.uber.org/zap/zapcore/entry.go:198 +0x9b
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc006a33110, {0xc004f5a180, 0x3, 0x3})
        /0chain/code/go/0chain.net/vendor/go.uber.org/zap/zapcore/entry.go:264 +0x61c
go.uber.org/zap.(*Logger).Panic(0xc000165b20, {0x195be0b, 0x22}, {0xc004f5a180, 0x3, 0x3})
```
referring to this snippet : https://github.com/0chain/0chain/blob/5bac8131b0bf3d1fb3654ebf03a4654bc0c096c9/code/go/0chain.net/chaincore/chain/protocol_block.go#L348-L354

**Comment by peterlimg** [comment]
@devyetii the `panic` has already been changed to `logging.ERROR`, basically it means the code needs to be updated, otherwise it could have missing blocks issue. See details in PR #1955. I'll close this issue and feel free to re-open if the issue still exists.
