### ISSUE TITLE
Fix lint issues

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#202]
PR https://github.com/0chain/0chain/pull/184 gives us a pull request check to ensure that a PR does not increase the total number of lint issues.

To support this functionality we should address all the easy to fix lint issues in [0chain](https://github.com/0chain/0chain). Similar to https://github.com/0chain/blobber/pull/37

I would suggest doing one directory or package at a time rather than all at once.

**Comment by Sriep** [comment]
When this is issue is resolved we should activate PR https://github.com/0chain/0chain/pull/184

**Comment by Sriep** [comment]
Fixed by https://github.com/0chain/0chain/pull/184

**Comment by ma2b0043** [comment]
@peterlimg @Sriep when can we expect to close this issue?

**Comment by peterlimg** [comment]
Fixed via #1065
