### ISSUE TITLE
Block rewards calculation issue

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#2055]
The `blockReward` and `minerRewards` calculated below is in `ZCN` unit, while in `DistributeRewardsRandN` method, we consider the `minerRewards` as `SAS`, therefore, with global config setting `block_reward: 0.21`, `reward_rate: 1`, `share_ratio: 0.8`. The `minerRewards` will be `0.168`, which will be used in `DistributeRewardRandN` to calculate the service fee if delegate pool is not empty. And from the second code block below, we will see, it will always be `0` because of the `currency.Float64ToCoin()`. e.g. `currency.Flat64ToCoin(0.168*serviceChargeRatio)`.  
https://github.com/0chain/0chain/blob/0303fefce74732aabd720e6ad25a06e94acdfd3c/code/go/0chain.net/smartcontract/minersc/fees.go#L282-L307

https://github.com/0chain/0chain/blob/e43e3436d773cd71c35a62843045dc3699dfafb7/code/go/0chain.net/smartcontract/stakepool/stakepool.go#L330

**Comment by Sriep** [comment]
I am not sure this is a problem.

```go
blockReward, err := currency.MultFloat64(gn.BlockReward, gn.RewardRate) 
```
The gn values are read from [readConfig](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/models.go#L261)
[BlockReawrd](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/models.go#L261)
```go
gn.BlockReward, err = currency.ParseZCN(config.SmartContractConfig.GetFloat64(pfx + SettingName[BlockReward]))
```
[ParseZCN](https://github.com/0chain/common/blob/main/core/currency/currency.go#L57) converts ZCN to a balance amount, multiplying by 1e10. 

So in the example `gn.BlockReward = 2100000000` and hence on line 287 `minerRewards = 1680000000` not 0.168. So the service charge is calculated correctly on [stakepool.go line 330](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/stakepool/stakepool.go#L330)

**Comment by peterlimg** [comment]
@Sriep yes, if we read `gn` from `readConfig`, it should work as expect, but seems the `gn` passed in is loaded from [getGlobalConfig](https://github.com/0chain/0chain/blob/3e91e3f7a6eaba74d5d1d3d129f6727dba5126d6/code/go/0chain.net/smartcontract/minersc/sc.go#L120) when executing the SC. 
https://github.com/0chain/0chain/blob/3e91e3f7a6eaba74d5d1d3d129f6727dba5126d6/code/go/0chain.net/smartcontract/minersc/sc.go#L116-L133

**Comment by Sriep** [comment]
[getGlobalNode](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sc.go#L135) reads the global node from the MPT with no option to read from config files.

I believe the global node is setup in [InitConfig](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sc.go#L147). Which is called from [GenerateGenesisBlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/entity.go). This is in turn called from [main](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/miner/miner/miner.go#L153).

InitConfig calls readConfig which as above converts ZCN to balance by multiplying by 1e10.

**Comment by dabasov** [comment]
I thought of changing how we read config in [Load config from MPT on node starts and update on block finalization](https://github.com/0chain/0chain/issues/1392) 
we can load config only once and store it in viper, on every update we can refresh config in MPT (for integrity) and reload it in viper.

**Comment by Sriep** [comment]
```
we can load config only once and store it in viper, on every update, we can refresh the config in MPT (for integrity) and reload it in viper.
```
That sounds dodgy to me. What is the upside? The config settings are under the control of the blockchain. 

We have the event database that could be considered a mirror of the MPT for non-smart contract operations. We could and probably should have a table for smart contract settings there. Currently, endpoints such as [getConfig](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/handler.go#L848) gets there data from the MPT rather than the event database.

**Comment by peterlimg** [comment]
@Sriep yes, you're right, the block rewards is initialized in genesis block by multiple 1e10, so this issue does not exist actually, I'll close it.
