### ISSUE TITLE
addChallenge: Modify validator selection procedure

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#209]
Add a new smart contract config entry to sc.yaml, `minimum number of validators`.

Modify the [validator selection procedure](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/challenge.go#L727).

Set the number of validators to the maximum of the new `minimum number of validator` entry and the `allocation.DataShards`. Unless that is more than the total number of validators, then use all the validators.

Select the validators randomly.

**Comment by guruhubb** [comment]
On second thought, doesn’t Select the validators randomly already exist ? I think you can close this issue because its unlikely anyone will have an allocation with a low number of datashards.

**Comment by Sriep** [comment]
Converted to a bug and reopend as https://github.com/0chain/0chain/issues/234
