### ISSUE TITLE
Mock Submodule

### ISSUE THREAD

**Issue by TheTeaParty** [0chain/0chain#210]
`mocks` are useful for users of your library as well, so we need to create `mocks`, sub package in `mocks` directory, which will contain both generated and hand made mocks.

**Comment by guruhubb** [comment]
@Sriep please share your thoughts on this

**Comment by Sriep** [comment]
@MurashovVen is working on mocks while writing unit tests, e.g.  https://github.com/0chain/0chain/pull/248, https://github.com/0chain/0chain/pull/262 and https://github.com/0chain/0chain/pull/264. Feel free to review.

**Comment by TheTeaParty** [comment]
closed by #320
