### ISSUE TITLE
add health check sc for validators

### ISSUE THREAD

**Issue by boddumanohar** [0chain/0chain#2128]
all providers should have health check transaction to let blockchain know that they are alive. 

at the moment, only blobbers, miners, sharders have health check.

we should also enable it for validators

**Comment by Hitenjain14** [comment]
PR created -[added health check for validator]( https://github.com/0chain/blobber/pull/951)

**Comment by Hitenjain14** [comment]
PR created to execute [validate health check transaction on 0chain ](https://github.com/0chain/0chain/pull/2138)

**Comment by peterlimg** [comment]
closed via #2138
