### ISSUE TITLE
New storagesc endpoints for system tests

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#2140]
We need storagesc versions of the following endpoints for blobber and validators. The existing ones are in minersc for miners and sharders.

* [/test/screst/nodeStat](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L65) return blobber and validator with stake pool guaranteed to be from the same round.
* [/provider-rewards](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L61) list of rewards paid to validators and blobbers during a period.
* [/delegate-rewards](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L62) list of rewards paid to validator and blobbers stake pools during a period.

**Comment by dabasov** [comment]
we should avoid `for all` endpoints, please move them under the `/test/`

**Comment by Sriep** [comment]
```
we should avoid for all endpoints, please move them under the /test/
```
So as to not increase the scope of this issue, creating a new issue https://github.com/0chain/0chain/issues/2144 for this.

**Comment by Kishan-Dhakan** [comment]
Closed after discussing with @Sriep.
