### ISSUE TITLE
Error reading DKG file. ERROR: Error reading dkg file: path is blank

### ISSUE THREAD

**Issue by anish-squareops** [0chain/0chain#216]
@Kenwes13  can you explain how dkg files are being generated and what changes are needed in magicblock.json

**Comment by Kenwes13** [comment]
There is a script that should be able to generate the dkg files and the corresponding magic block. Run `docker.local/bin/build.magic_block.sh` then `docker.local/bin/create.magic_block.sh` to create a new magic block and dkg files. 

The program takes in the yaml file that is on line 11 in 0chain/docker.local/build.magicBlock/docker-compose.yml. Each yaml file has the name of the magic block and dkg files that will be created.

Once the new dkg files and magic block are created update the 0chain.yaml so it uses the new magic block. Also update the 0chain/docker.local/build.miner/b0docker-compose.yml on line 55 to use the new dkg files.

**Comment by anish-squareops** [comment]
How can I change the filenames being generated ?

**Comment by anish-squareops** [comment]
Closed
