### ISSUE TITLE
Allocation size is changed after some invalid update attempts by non-owner

### ISSUE THREAD

**Issue by devyetii** [0chain/0chain#2180]
We have this system test: https://github.com/0chain/system_test/blob/master/tests/cli_tests/zboxcli_update_allocation_test.go#L703
It tests that a non-owner cannot perform any update action on an allocation except for expanding (increasing size or extending expiration) when `third_party_extendable` property of the allocation is true.  No size expansion is performed in this test, however, it fails in the first attempt saying that Size of the allocation has changed (see [this run](https://github.com/0chain/system_test/actions/runs/4286084895/jobs/7481473283)), it succeeds after the first re-run though.

I guess this maybe a background job that may be syncing allocation info with the blobbers or something, since nothing in the test nor in the code that updates the allocation should increase the size when a request by a non-owner fails, this needs to be checked.

**Comment by Jayashsatolia403** [comment]
To make sure everything is lined up or reproduce the error, if any, follow these steps:

1. Stake the blobbers and create the allocation. Now the wallet you used to run the command newallocation is the allocation owner.
2. List the allocation info using getallocation command and write down its size for later reference
3.Using the same wallet, update the allocation to make it third_party_extendable , you can do this using --third_party_extendable flag in ./zbox updateallocation
4. Using a different wallet, try to reduce the allocation's size using --size=<negative_number> . The command should fail
5. Now list the info of the allocation using getallocation command, you should see the size of the allocation unchanged from the one you wrote down before.

As this is successful we can close this issue.
