### ISSUE TITLE
NetscanOutLevel: Netscan detected from <server ip>

### ISSUE THREAD

**Issue by shahnawaz-creator** [0chain/0chain#2202]
Many servers got blocked/locked by the provider. They reported an issue or port scanning.

logs provided by them 
`> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 60542 =>     125.2.128.0 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 45564 =>     125.2.128.1 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 33030 =>     125.2.128.2 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 60342 =>     125.2.128.3 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 59102 =>     125.2.128.4 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 34828 =>     125.2.128.7 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 49486 =>    125.2.128.12 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 33394 =>    125.2.128.13 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 42074 =>    125.2.128.14 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 35366 =>    125.2.128.15 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 50352 =>    125.2.128.20 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 52862 =>    125.2.128.25 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 58648 =>    125.2.128.26 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 37712 =>    125.2.128.27 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 60938 =>    125.2.128.28 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 59644 =>    125.2.128.30 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 57190 =>    125.2.128.31 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 34358 =>    125.2.128.33 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 34358 =>    125.2.128.33 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 50936 =>    125.2.128.41 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 36712 =>    125.2.128.42 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 60852 =>    125.2.128.59 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 55750 =>    125.2.128.72 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 48358 =>    125.2.128.73 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 33528 =>    125.2.128.79 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 36086 =>    125.2.128.93 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 35780 =>    125.2.128.94 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 50596 =>    125.2.128.96 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 38530 =>    125.2.128.97 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 59316 =>    125.2.128.98 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 38114 =>   125.2.128.103 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 47650 =>   125.2.128.104 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 36532 =>   125.2.128.105 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 50200 =>   125.2.128.109 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 49424 =>   125.2.128.110 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 41198 =>   125.2.128.111 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 36588 =>   125.2.128.112 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 37124 =>   125.2.128.113 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 60216 =>   125.2.128.114 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 42914 =>   125.2.128.115 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 58034 =>   125.2.128.126 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 55324 =>   125.2.128.127 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 56774 =>   125.2.128.128 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 48736 =>   125.2.128.129 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 49766 =>   125.2.128.130 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 42858 =>   125.2.128.131 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 54472 =>   125.2.128.148 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 37498 =>   125.2.128.152 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 52712 =>   125.2.128.153 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 34002 =>   125.2.128.156 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 56690 =>   125.2.128.157 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 56270 =>   125.2.128.158 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 51858 =>   125.2.128.159 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 38630 =>   125.2.128.160 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 33746 =>   125.2.128.161 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 49370 =>   125.2.128.162 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 57440 =>   125.2.128.183 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 54472 =>   125.2.128.184 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 34986 =>   125.2.128.185 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 59228 =>   125.2.128.186 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 58694 =>   125.2.128.193 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 39722 =>   125.2.128.194 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 49276 =>   125.2.128.195 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 56570 =>   125.2.128.196 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 57722 =>   125.2.128.201 6379
> Wed Mar  8 00:46:04 2023 TCP  65.109.230.138 50158 =>   125.2.128.202 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 43590 =>   125.2.128.216 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 50142 =>   125.2.128.217 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 42488 =>   125.2.128.218 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 51270 =>   125.2.128.219 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 34468 =>   125.2.128.226 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 60412 =>   125.2.128.227 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 57276 =>   125.2.128.234 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 60132 =>   125.2.128.253 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 47990 =>   125.2.128.254 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 47814 =>   125.2.128.255 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 32904 =>     125.2.129.0 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 36494 =>     125.2.129.3 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 60570 =>     125.2.129.4 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 34430 =>     125.2.129.5 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 45190 =>     125.2.129.7 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 46090 =>     125.2.129.8 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 42676 =>    125.2.129.11 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 44796 =>    125.2.129.12 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 40590 =>    125.2.129.13 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 54622 =>    125.2.129.27 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 46844 =>    125.2.129.28 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 57142 =>    125.2.129.29 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 59360 =>    125.2.129.30 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 50456 =>    125.2.129.31 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 56756 =>    125.2.129.32 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 41982 =>    125.2.129.33 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 51236 =>    125.2.129.34 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 37378 =>    125.2.129.35 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 37182 =>    125.2.129.36 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 48766 =>    125.2.129.37 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 58118 =>    125.2.129.38 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 59358 =>    125.2.129.39 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 60988 =>    125.2.129.40 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 46334 =>    125.2.129.41 6379
> Wed Mar  8 00:46:05 2023 TCP  65.109.230.138 39534 =>    125.2.129.47 6379`

**Comment by shahnawaz-creator** [comment]
port 6379 refers to redis. according to me seems like queue is getting bigger for redis to process it.
port 5432 refers to postgres.

**Comment by shahnawaz-creator** [comment]
According to the report shared by hertzner shows that from the server where only 0dns, 0box are deployed is scanning port 6379(redis). Redis is only used by the miners and i'm unable to understand what's the dependency of redis from 0dns/0box.

**Comment by shahnawaz-creator** [comment]
According to the report shared by hertzner shows that from the server where only 0dns, 0box are deployed is scanning port 6379(redis). Redis is only used by the miners and i'm unable to understand what's the dependency of redis from 0dns/0box.

**Comment by shahnawaz-creator** [comment]
This issue is resolved we will be hardening the servers with our deployment scripts. We already tested this out.
@dabasov you can close this issue.

**Comment by dabasov** [comment]
can't reproduce
