### ISSUE TITLE
1/3 (approx) of the challenges are failing every time a new file is uploaded.

### ISSUE THREAD

**Issue by Jayashsatolia403** [0chain/0chain#2243]
Conditions : 

Network : 2 blobbers | 2 validators

Allocation : 100mb | 1 data | 1 parity | 5m expiry

File : 10mb

File is downloaded immediately after creating allocation and kept till allocation expiry.

**Comment by gerta17** [comment]
@dabasov Can you assign a developer to work on this bug and provide an ETA?
