### ISSUE TITLE
generate_challenge: could not remove allocation from blobber: item not found ; allocation_id

### ISSUE THREAD

**Issue by Jayashsatolia403** [0chain/0chain#2300]
One of the transactions in the demo network is recorded with the error : 

generate_challenge: could not remove allocation from blobber: item not found: 5a5e392d6761885f91618100fb12e390cbeb324b0bea46a96a8ad35853d016fa",

Transaction Link : https://demo.atlus.cloud/transaction-details/5867823241d29c93d4338fdf6e810cfe879d0b3c8eda6fd8477084b6dda0c314

It looks like the it is not able to find the allocationID in MPT. 

Here is the code that is causing the error : 

https://github.com/0chain/0chain/blob/b73ffc4ae4b3c7413013a6109cdde088f00f26a6/code/go/0chain.net/smartcontract/partitions/partitions.go#L274

https://github.com/0chain/0chain/blob/b73ffc4ae4b3c7413013a6109cdde088f00f26a6/code/go/0chain.net/smartcontract/storagesc/challenge.go#L932

**Comment by peterlimg** [comment]
This will be fixed by https://github.com/0chain/0chain/commit/85247550bcfad8249082a1c103b51b6f44f687b7 in `fix/stuck-debug` branch. I'll do a cherry-pick. cc @dabasov @guruhubb
