### ISSUE TITLE
Fix: fix broken mint nonce registration logic

### ISSUE THREAD

**Issue by YarikRevich** [0chain/0chain#2323]

**Comment by dabasov** [comment]
looks like UI sends ZCN instead of SAS for mint operation on 0chain, please fix, minting of ZCN doesn’t work atm
```"transaction_data": "{\"name\":\"mint\",\"input\":{\"ethereum_txn_id\":\"0xa2996b28aa40fd5b1aff3aa190717cf0e5c5354fc63f9f58c2f7db44d5651bdb\",\"amount\":1,\"nonce\":1,\"signatures\":[{\"authorizer_id\":\"896c171639937a647f9e91d5ba676be580f6d2b7e0d708e4fe6ea36610a13ffd\",\"signature\":\"9a04499818376d89ef7b7205e89257b4ea7c5e25f677de5665dab5e573279117\"},{\"authorizer_id\":\"d6e9b3222434faa043c683d1a939d6a0fa2818c4d56e794974d64a32005330d3\",\"signature\":\"84dd7d26d81925f7aa9998d1a21f963869bcb19cab8ca4142686e8b2da028003\"},{\"authorizer_id\":\"7b07c0489e2f35d7c13160f4da2866b4aa69aa4e8d2b2cd9c4fc002693dca5d7\",\"signature\":\"8783ff97daf2cefb7b4404a46ed11d0e56004bb70e82bb2c66ba698c5b10fd0f\"}],\"receiving_client_id\":\"1746b06bb09f55ee01b33b5e2e055d6cc7a900cb57c0a3a5eaabb8a0e7745802\"}}",```
