### ISSUE TITLE
Filter blobbers by geolocation

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#238]
A new option added to `zbox newallocation` to amend blobber selection to increase geo-location diversity.

### blobber
Add latitude and longitude to `blobber.yaml`.

### 0chain
Add a new boolean to `StorageAllocation`.
allocation.go, newAllocationRequewst; Add new  code to [filterBlobbers](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/allocation.go#L273) to select blobber so as to maximise geo-diversity. Algorithm to be determined.
Modify unit tests to confirm changes.

### zboxcli
Add new command line option to `newallocation`, `use-diverse-blobbers`. This should link to 0chain changes.

**Comment by andrenerd** [comment]
Transformed to #315
