### ISSUE TITLE
process challenges based on round

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#2399]
- validate that create-challenge transaction is included in the block with exact round
- process challenges based on round created and round response submitted, make them expire based on current round as well

**Comment by peterlimg** [comment]
> @dabasov 
> The main reason to change it is the situation when network is stuck for sometime (we should be ready for such a situation). Also, we should be ready even to rollback network (like ethereum did during the dao hack) and replay transactions again. In that case challenges will be failed, since time will move forward and challenge transactions were emitted long ago. If challenges were processed in a round specific manner (as suggested) they could be processed smoothly, as if nothing happened (in blockchain the time is measured in rounds and there are no any stuck or rollbacks even). But it’s not as easy to change challenges handling to use rounds as I thought before, we compare sometimes challenge times with expiration time and so on.
what are your thoughts about it?

**Comment by peterlimg** [comment]
I agree that it’s more reasonable to do it with round based. For the expiration, is it possible to use the fixed number of rounds as challenges’ expiration. Say 100 rounds, so the challenge will be expired after 100 rounds. If the allocation get expired before the 100 rounds (we should know the current block round when the allocation expired/canceld/finalized), we can mark the challenge as expired as well. Not sure if there are other cases that need to compare with, but seems can do it in similar way.

**Comment by Jayashsatolia403** [comment]
https://github.com/0chain/actions/pull/257

**Comment by Jayashsatolia403** [comment]
Green run : https://github.com/0chain/system_test/actions/runs/6059936841/job/16451780277

StorageConfigUpdate test failing is because of helmchart. We can't remove `max_challenge_completion_time` from helmchart until this PR is merged to staging. 

Other 2 failures are known failures on staging too.

**Comment by Jayashsatolia403** [comment]
Updated green run : https://github.com/0chain/system_test/actions/runs/6079801651/job/16494928501

This only has `StorageConfigUpdate` issue other than that everything is completely green on very first run.
