### ISSUE TITLE
Prevent duplicate registraton for blobber

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#253]
We can add a check in  [addBlobber](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/blobber.go#L191) to prevent duplicate registration.

**Comment by andrenerd** [comment]
for more details, check the discussion for more details:
https://github.com/0chain/blobber/pull/109

long story short:
To replace duplicate blobbers in sc and leave a warning.
