### ISSUE TITLE
Fix not enough tokens to honor the cancellation charge plus min lock demand

### ISSUE THREAD

**Issue by manasnisar** [0chain/0chain#2535]
Ref: https://0chain.slack.com/archives/C03HUFQD01M/p1685719441874609?thread_ts=1685127367.777709&cid=C03HUFQD01M

**Comment by boddumanohar** [comment]
we have discussed that this will handled from the UI side based. Associated ticket from the UI. 
https://github.com/0chain/web-apps/issues/7003
