### ISSUE TITLE
In blobber total used should be 0 after cancelling allocation

### ISSUE THREAD

**Issue by Jayashsatolia403** [0chain/0chain#2617]
Steps to reproduce : 

Take a record write data in blobbers table in eventsDb.

Create new allocation and write some data. 

USED should increase in blobber table. 

It should be back when the allocation is cancelled but it is not.

**Comment by sunilmhta** [comment]
Hi @Jayashsatolia403 , I do not see any column named write data in the blobbers table. Can you please update the comment which column you are referring to?

I checked two snapshots:
1. After uploading a file on blockchain:
<img width="719" alt="image" src="https://github.com/0chain/0chain/assets/15699710/506c432a-dfb2-47a8-8dbd-ae8a9a09ff63">
2. After cancelling the allocation:
<img width="719" alt="image" src="https://github.com/0chain/0chain/assets/15699710/829e923b-efba-40bb-ae32-0b628f9f908b">

Do you perhaps mean some other column when you said `write_data`? 
cc: @dabasov

**Comment by Jayashsatolia403** [comment]
I meant `used` column only.
