### ISSUE TITLE
Test provider sync up with conductor testing

### ISSUE THREAD

**Issue by lpoli** [0chain/0chain#2653]
In the network there will be many providers running. Sometime some provider may crash and after few moments it will try to rejoin network. We need to test whether this sync up was successful or not. The following conductor tests are required to be added.

- [x]  Sharder crashes and comes back:
1. Run a network with 3 miners and 2 sharders for upto some rounds
2. Stop a sharder and let some rounds pass
3. Restart sharder in step-2.
4. Compare LFB with another sharder.

- [x] Miner crashes and comes back:
1. Run a network with 4 miners and 1 sharder for upto some rounds
2. Stop a miner and let some rounds pass
3. Restart miner in step-2
4. With some timeout, check if this miner is able to produce any block. If it produces then we can consider that this miner has synced up with the the network

- [x]  Validator crashes and comes back:
1. Run a network with 3 miners, 1 sharder, 2 blobbers(one-data, one-parity) and 3 validators. Note that due to docker-compose file we need to run same number of blobbers and validators. This can be changed however.
2. Create an allocation and upload some file
3. Wait for blobber to commit writemarker and blockchain to generate challenge.
4. Check if the selected validator sends ticket and earns reward.
5. Stop a validator
6. Wait for some rounds
7. Restart a validator 
8. Challenge would continually be created by blockchain so it will select this validator at some iteration
9. Check if the selected validator sends ticket and earns reward

- [x] Authorizer crashes and comes back:
1. Run a network with 3 miners, 1 sharder and 4 authorizers.
2. Do some bridge transactions.
3. Check authorizer reward.
4. Stop a authorizer
5. Wait for some rounds
6. Restart authorizer in setp-4
7. Check if this particular authorizer was able to sign ticket
8. Verify whether signature is valid
9. Check authorizer rewards.

- [x] Blobber crashes and comes back:
1. Run a network with 3 miners, 1 sharder, 1 blobber and 3 validators.
2. Create and allocation and upload a file
3. Wait for blobber to commit writemarker and blockchain to generate challenge
4. Check if blobber is passing challenges and is earning tokens
5. Stop the blobber
6. Check if blobber is loosing tokens
7. Restart blobber.
8. Blobber should earn afterwards.

**Comment by devyetii** [comment]
All done in:
https://github.com/0chain/0chain/pull/2934
https://github.com/0chain/0chain/pull/2797
