### ISSUE TITLE
Delete authorizer by owner

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#2677]
Add delete authorizer that can be run by owner only (force delete), also check that current delete is adjusting the authorizer's count and deleted authorizer can't be used in consensus anymore

**Comment by peterlimg** [comment]
@dabasov PR https://github.com/0chain/0chain/pull/2698 will adjusting the auth count. We check if the signatures in `mint` contract is signed by authorizer nodes that exist in our chain, so if any one is deleted, the signature verify process will fail and the `mint` will fail, so this should help use to prevent deleted node being used in consensus.

**Comment by peterlimg** [comment]
The PR #2698 and #2743 fixed the count and remove by owner. And I have tested manually to confirm that the deleted authorizers would not be participant in the consensus and new added one will be in the consensus once it gets registered.
