### ISSUE TITLE
WARN Go compiler: conversion from int to string yields a string of one rune, not a string of digits

### ISSUE THREAD

**Issue by platsko** [0chain/0chain#271]
petr@latsko:~/work/0chain/0chain/code/go/0chain.net/core/encryption$ go test -v -tags bn256 -cover ./...
# 0chain.net/core/encryption
./handler.go:19: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL    0chain.net/core/encryption [build failed]
?       0chain.net/core/encryption/keys [no test files]
FAIL

**Comment by mallochine** [comment]
I don't really know the intent of that code, where the git blame says it was last changed May 2018

```
5a570776b code/go/src/0chain.net/encryption/handler.go (Siva Dirisala 2018-05-21 16:57:14 -0700 19)             text = string(buff)
```

at first glance looks like it's just trying to generate a hash, in which case you can just go with the compiler suggestion of `fmt.Sprint`

@Sriep  should confirm.

**Comment by mallochine** [comment]
this is just a 1 line change, anybody on the team could do easily do it unless everybody is really that busy, in which case I can submit a PR

**Comment by Sriep** [comment]
```go
/*HashHandler - returns hash of the text passed */
func HashHandler(w http.ResponseWriter, r *http.Request) {
	text := r.FormValue("text")
	if text == "" {
		var data []byte
		buff, err := r.Body.Read(data)
		if err != nil {
			return
		}
		text = string(buff)
	}
	fmt.Fprintf(w, Hash(text))
}
```
[buff, err := r.Body.Read(data)](https://pkg.go.dev/io#Reader)  returns the data read in `data`, and the number of bytes read to `buff`. It seems clear that the intention is to set `text = string(data)` not `buff`.

**Comment by mallochine** [comment]
ah. yeah. that makes more sense to me. Glad I didn't do the PR :) Thanks @Sriep Sriep

**Comment by mallochine** [comment]
at the end of the day it doesn't really matter, it's just a Hash that's the ultimate return value. Doing Sprintf on the len(data) would've yielded equally random results anyway.

**Comment by Sriep** [comment]
Its already being fixed as part of [PR264](https://github.com/0chain/0chain/pull/264/files#diff-9f950c8ba682d9e2b14b40e0a044a9c4a3948f558190fdb13ba8024ea3d2e17e)
