### ISSUE TITLE
instructions to run unit tests on local

### ISSUE THREAD

**Issue by boddumanohar** [0chain/0chain#2720]
Currently to run unit tests locally: 

```
docker build -f docker.local/build.unit_test/Dockerfile . -t zchain_unit_test
docker run --rm  -w /0chain/code/go/0chain.net zchain_unit_test  go test -timeout 30s 0chain.net/smartcontract/storagesc -tags=bn256
````

But method lacks native integration with editors like vscode and golang. We need to have clear set  of instructions that works 

- [ ] MacOS
- [ ] Windows
- [ ] Linux

We have see instructions, but when other tried don't seem to be working fine.
https://github.com/0chain/0chain/blob/acca15a00f786eb2152c5feb483c591a5a77132f/dev.local/cli.sh

An other option that we can try is using [dev containers.](https://code.visualstudio.com/docs/devcontainers/containers). Both Goland and Vscode supports it.

Please use this ticket to come up proper development environment for running unit tests of 0chain/0chain natively on editors.

**Comment by devyetii** [comment]
Added documentation for macos and linux here: https://app.gitbook.com/o/-MWVD-8BJlEUSju1kMMq/s/JSnVTrEJX0y7DNsRCmTE/#environment-variables
For Windows, just use WSL2
