### ISSUE TITLE
Cleanup block struct

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#2766]
there are two different fields in the block structure, will fix it
```go
  "CreatedAt": "0001-01-01T00:00:00Z",
  "created_at": "2023-09-12T10:12:00Z",
```

**Comment by tanishq67** [comment]
@dabasov Sir, I am unable to understand the issue properly. The block struct has one field "CreatedAt" only, as we can see from the below image. Please give me a little more details. Thank you very much.
![image](https://github.com/0chain/0chain/assets/52757132/38177572-271d-4a72-bf61-801edbe46c57)
