### ISSUE TITLE
Miner panic on startup

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#280]
Start sharder, start a miner. Delay starting a second miner. The miner panics.

This [bit of code](https://github.com/0chain/0chain/blob/b35817bcef614e6dd6932051add2f426356936f4/code/go/0chain.net/chaincore/chain/protocol_round.go#L149) from PR https://github.com/0chain/0chain/pull/245 seems to be the problem.
```go
	genNum := c.GetGeneratorsNumOfRound(roundNumber)
	if genNum > len(c.NotarizedBlocksCounts) {
		newCounts := make([]int64, genNum)
		copy(newCounts, c.NotarizedBlocksCounts)
		c.NotarizedBlocksCounts = newCounts
	}

	c.NotarizedBlocksCounts[nbCount]++
```
The panic happens when `c.NotarizedBlocksCounts` does not have `nbCount+1` members.

The program should be able to handle slow startup, plus if it fails here it should do it in a controlled manner.

**Comment by peterlimg** [comment]
The `newCounts` slice length should be `genNum+1`, will fix it in the fix/vc-true-stuck branch.

**Comment by peterlimg** [comment]
This has been fixed by https://github.com/0chain/0chain/commit/5a4e94ebf76e3fe35809db215b1a7a3c582cfdd0
