### ISSUE TITLE
Delete allocation on finalization from MPT

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#2821]
when allocation is finalized we need to delete it from MPT

**Comment by peterlimg** [comment]
The `write_pool_lock` SC requires the allocation is finalized or cancel by loading the allocation from MPT and check it's `finalized` or `canceled` field. However, if we remove the allocation when it's finalized, it will also get `nil` allocation, and it would not know what's the remaining tokens to unlock. So perhaps we will need to unlock the tokens automatically when finalize/ cancel the allocation. And perhaps the `write_pool_lock` is not needed then.

**Comment by peterlimg** [comment]
This will be closed via #2829
