### ISSUE TITLE
Delete killed/shutdown blobber/validator from MPT

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#2825]

**Comment by peterlimg** [comment]
Not sure if we should delete them as comment says:
> shuts down the blobber: It is no longer available for new allocations
 but its existing commitments will still be upheld.

Also, the number of blobbers and validators are small, so may not affect the MPT size.

**Comment by dabasov** [comment]
We can have a protection from empty blobbers registration, when malicious client will  try to create a lot of empty blobbers and will try to spam the system. obviously, fee is a protection, but sometimes we will want to clean up the state.
