### ISSUE TITLE
I was able to update allocation, but got an error

### ISSUE THREAD

**Issue by moldis** [0chain/0chain#290]
Reducing size with zbox CLI

`zbox updateallocation --allocation 143747f9cf6942edcacad5f57373c93ef582079daf0179ee3d044bffa96c4af9 --size -6442450956 --expiry 1h --lock 0.1 --verbose`

Got an error:

`[ERROR]  2021/05/18 14:35:02.055802 sdk.go:951: Error verifying the transactiontransaction_not_found: Transaction was not found on any of the shardersa1eea41f40ecb002160c7cbe983d822e21241af5d688cb99b31665fe318d685c`

But size was actually reduced (zbox listallocations showed me update size)

**Comment by moldis** [comment]
@Sriep

**Comment by guruhubb** [comment]
@moldis it seems the transaction execution took longer than the client was willing to ping the sharder. This will be fixed as @peterlimg is working on optimizing smart contract execution

**Comment by guruhubb** [comment]
https://github.com/0chain/0chain/issues/385 address same issue
