### ISSUE TITLE
Remove typecaset 'rounding' errors

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#319]
```go
package main
import (
	"fmt"
)
func main() {
	var zp9 = 0.9
	fmt.Println(10*int(zp9), int(10*zp9))
}
```
Result `0 9`.

Rounding errors are mostly insignificant while typecasting errors always give a noticeable error of `1`.

Internal monetary calculations should all be done using floating-point arithmetic. Typecasting to a `state.Balance` value should only be done once on the final assignment. 

Internal functions with monetary parameters should all take `float64` parameters rather than `state.Balance` or `int64` parameters.

We should investigate a method for avoiding repeated type cast errors on regular payments like interest and block rewards.

**Comment by Sriep** [comment]
Here is some code from [stakepool.go](https://github.com/0chain/0chain/blob/3ce38f9875a4ba2681dfd9042a12f087fc9f5017/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L470)
```go
func (sp *stakePool) interests(dp *delegatePool, now common.Timestamp,	rate float64, 
   period common.Timestamp) (mint state.Balance) {
   if period == 0 {	
      return // avoid infinity loop
   }

   for at := dp.MintAt; at+period &lt; now; at += period {		
      mint += state.Balance(rate * float64(dp.Balance))	   
   }	
   return
}
```

this is a particularly bad example. So if `interest_interval: 1m` and your unlucky to have your interest per minute be 0.9, then you will get `0` interest per day rather than `1296`. Obviously the typecast should come after calculating the interest, not at each intermediate stage. Here is the same idea done better in [mintPool](https://github.com/0chain/0chain/blob/3ce38f9875a4ba2681dfd9042a12f087fc9f5017/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L438)
```go
   var at = dp.MintAt // last periodic mint
   var floatMint = 0.0	
   for ; at+period &lt; now; at += period {	
      floatMint += rate * float64(dp.Balance)	
   }	
   mint = state.Balance(floatMint)
```

**Comment by guruhubb** [comment]
Sure go ahead @Sriep

**Comment by platsko** [comment]
FYI. Floating-point arithmetic often gives unexpected results.
Examples: https://stackoverflow.com/questions/18056787/floating-point-operations-in-go

**Comment by guruhubb** [comment]
@platsko is this still an issue with the current Go

**Comment by Dmdv** [comment]
@Sriep Shouldn't we use decimals (https://github.com/shopspring/decimal) in case we are talking about numbers or big.Int we are talking about big integers. In smart contracts we are supposed to use integers as with Ethereum.
Am I correct?

**Comment by Sriep** [comment]
In smart contracts, we currently use `state.Balance` object to hold fund amounts, which is `int64` or `1e0 * tokens`. As far as I know, that is sufficient, although we could use [big.Int](https://pkg.go.dev/math/big)` if it later runs out that int64 is not big enough.

**Comment by ma2b0043** [comment]
@dabasov who should we assign this task too?

**Comment by dabasov** [comment]
we'll see, who will be free next

**Comment by peterlimg** [comment]
I agree with @Dmdv that we should use https://github.com/shopspring/decimal, float could cause unexpected result. It's a common pattern to use integer/unsigned integer instead of float in crypto.

**Comment by ssardana08** [comment]
@peterlimg with decimal package @dabasov had a point:
```
but we should keep in mind, that it will be necessary to implement custom types for json/msgp and gorm
```
why can't we just use uint64?

**Comment by peterlimg** [comment]
@sum-it08 tokens will be saved in MPT all in uint64, but APIs/CLI may provide string float values, and we need to convert it to uint64 to participant the tokens calculation. Also we need to limit the decimal numbers, it should be `10` for us.

**Comment by ssardana08** [comment]
> Also we need to limit the decimal numbers, it should be 10 for us.

Didn't get this - if we're keeping tokens in MPT as uint64 and doing all calculation in uint64, where would decimal be coming?

**Comment by ssardana08** [comment]
from @peterlimg 

Re fixing the rounding errors, there are mainly two things we need to fix:
- Fixing the rounding error, apparently
- Add constraint checking to ensure no token is burned after each transaction. If every transaction could pass this validation, we basically don’t need the event db to record mint and transfer records. As this will soon fill up the database. Also, the transactions contain the token move flow themselves, if we want system tests to validate no tokens are burned, we can have system tests to pull blocks and parse the transactions and verify the balance changes instead of wasting sharders’ resources.
- The event db table for recording the mint and transfer is the last thing we need to do perhaps, please do not work on it until we have figured out the above two things and still thought this is needed.
