### ISSUE TITLE
Allocation and related stuff transfer to new owner method

### ISSUE THREAD

**Issue by andrenerd** [0chain/0chain#333]
Allow to modify storage smart contract to:
- set new owner and probably payer, if it's equal to the current owner
- check the transfer initiated by current owner or auth token generated by current owner provided (to be discussed)
- transfer write pool (literally, write allocation pool) to the new owner too (to be discussed)

Also:
- add api endpoint to expose the method (to be discussed)

PS. further a related command supposed to be added to zbox and other interfaces. the new feature, for example, could be used for nft-cases.

**Comment by guruhubb** [comment]
@andrenerd make sure that both current owner and curator are able to transfer ownership of owner's allocation to new owner/buyer. cc @Sriep

**Comment by guruhubb** [comment]
https://github.com/0chain/zboxcli/issues/29#issuecomment-860120687

**Comment by andrenerd** [comment]
Closing, as the related branch was forcefully closed.
