### ISSUE TITLE
Create tool that auto generate proto definitions from golang objects

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/0chain#338]
Similar to https://github.com/vektra/mockery

Tool should also generate conversion functions that automatically allow to convert grpc objects -> golang objects and vice versa

**Comment by TheTeaParty** [comment]
I think it is not good approach to generate protos from golang structures, it is better have transitional DTOs for that which are generated from protos, will be faster and safer, @Sriep @guruhubb .

**Comment by shravanshetty1** [comment]
> I think it is not good approach to generate protos from golang structures, it is better have transitional DTOs for that which are generated from protos, will be faster and safer, @Sriep @guruhubb .

Corrected the heading which was wrong

**Comment by Sriep** [comment]
Unfocused and abandoned. Closing.
