### ISSUE TITLE
Free Storage

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#346]
Implement 0Chain changes for the free storage protocol as out in [ZeroStoreFree document.](https://0chain.slack.com/files/U9B3NRW69/F01QNPRB09L/zerostorfree_1_.pdf?origin_team=T9C1E9JEB&origin_channel=D01NYCVANLC) or try https://0chain.slack.com/archives/C01V6BX52BB/p1620243966000900

Three transactions for interacting with free storage allocations
1. Create a free storage marker.
2. Create a marker for topping up a previously issued free storage marker
3. Redeem free storage marker.
4. Redeem top-up free storage maker.
3. Renew a previously expired free storage allocation using unspent free tokens.

------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/6240686/121802409-05a50a80-cc34-11eb-8a5d-a68ad906881e.png)
------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/6240686/121802001-29ffe780-cc32-11eb-9477-7f6220dcf28e.png)
------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/6240686/121802368-d098b800-cc33-11eb-921e-a63ae916787c.png)
------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/6240686/121700779-251f2480-cac8-11eb-85e0-00dafc5b8557.png)

**Comment by andrenerd** [comment]
One of the recently added features, that is supposed to be used for free storage use cases:
https://github.com/0chain/blobber/pull/162

PS. 
As was discussed with Saswata, free storage feature(s) are mostly handled by existing storage smart contract (storagesc) with minimal upgrades.

**Comment by guruhubb** [comment]
We still need storage marker to be processed by storagesc to mint tokens and unused tokens to be used for renewing allocation. Also @moldis needs to generate this marker from 0Box.

**Comment by Sriep** [comment]
Updated sequence diagrams to take account of new transactions to create markers.

Redeem free storage marker transactions is different from the existing `create new allocation` transaction as it mints rather than transfers tokens, and there are restrictions on the subsequent movement of tokens locked in a free storage allocation.

**Comment by guruhubb** [comment]
We want the SC to be a simple function.  So today we have write markers and read markers signed by user that we use for data writes and reads to give to blobbers for them to submit to blockchain to collect payments. Its the same concept. 

In this scenario, the user goes to the corporation and the corp issues a signed marker which the user uses to lock tokens in his allocation or create new allocation.  Corp previously got approved by SC owner to be able to issue free storage markers.  So the corp address is inside the smart contract that allows for minting of tokens and locking it for a new allocation or existing allocation. So the corp does NOT interact with SC. 

User uses this marker to create new allocation or top up tokens to existing allocation. Example commands are as follows.

1) ./zbox newallocation --fs free_storage_marker.json, 
2) ./zbox updateallocation --fs free_storage_marker.json, and 
3) ./zbox add freeStorageCorp --limit xxx --max xxx, where limit = tokens given out to each user, max = max tokens allowed to be given out.

Item 3 gives a Corp permission to generate free storage markers and limits the number of tokens the Corp is allowed to give out over one year and to each individual. 

There is also an overall max limit in the smart contract on how many total tokens the network will give out. Each corp added by SC owner will have a limit as well.

**Comment by Sriep** [comment]
We need to consider all allocation related endpoints and list the ones that need to be changed for free allocations. Suggestions.

`cancelAllocation` and `finalizeAllocation`: The allocation is mothballed and free storage write-pools are kept with the allocation, not returned to the user.
`Transfer allocation`. Can't transfer free allocation.
`Lock more tokens`. Anyone can lock more tokens with a free allocation. It's necessary to keep track of the free `writePool` and the non-free ones.

**Comment by guruhubb** [comment]
Yes keep it simple. After finalization of an allocation, any unused tokens go back to the payer for multi payer pool including freeStorage since it is from a network contract address. So a write pool may have freeStorage, payer1,and payer2, in the pool, etc.
