### ISSUE TITLE
Automatic unstaking of tokens

### ISSUE THREAD

**Issue by hm90121** [0chain/0chain#354]
In staking and unstaking of tokens using explorer
I just staked for example 0.5 zcn on sharder(see the attached screenshot)
but after that in last five minutes explorer has unstaked tokens multiple times automatically and increased the total wallet balance.
(explorer used  on nine network)

![explorer staking](https://user-images.githubusercontent.com/65766301/121948684-2cb72580-cd75-11eb-8aef-ef903df43b89.PNG)

**Comment by Sriep** [comment]
Moved to https://github.com/0chain/block-explorer/issues/239
