### ISSUE TITLE
Transaction confirmation does not exist in sharder.

### ISSUE THREAD

**Issue by MurashovVen** [0chain/0chain#362]
When working with the network, I ran into a problem:
1) Run clean 1 sharder and 4 miner.
2) During the start of consumer, provider, and magma, the smart contract function is launched, the transaction is successfully verified.
3) After some time, transactions are no longer verified and do not reach the sharder.

[Logs](https://drive.google.com/drive/folders/1uAfE4bDPQpl6ThBUGyhphl9fl2Fp2rs4?usp=sharing).

For reproduce:
1) Run 0dns, sharder1, miners1-4.
2) Run consumer1:
`CONSUMER_ID=1 make cons-refresh-start`
3) Run provider1:
`PROVIDER_ID=1 make prov-refresh-start`
4) Run magma:
`make magma-refresh-start`
5) To execute another sc function:
- build [ana_client](https://github.com/magma/augmented-networks/tree/main/accounting/tools/ana_client) tool.
- run with args:
`-provider_id=man_embedded_cwag_network -consumer_id=man_feg_network -grpc_connect_tout_sec=10  -extra_clients=1 -remote_tout_sec=40  -notls=true :7051`

Reruning sharder and miners fix the problem, but usually for 10-15 minutes.

**Comment by ma2b0043** [comment]
@MurashovVen when can we expect to close this issue?

**Comment by dabasov** [comment]
won't reproduce
