### ISSUE TITLE
Challenges expiration

### ISSUE THREAD

**Issue by andrenerd** [0chain/0chain#368]
Challenges are generated and passed well. Not found any issues.
The only prob is a very strict expiration condition and not fully defined actions for "expired" changes. As a result, all challenges taken as expired and not properly processed later.

- expiration time: should it be in config? how much it should be? currently it's set based on `challenge_response.frequency` param.

- post-expiration actions: what to do with expired challenges? to set them as failed? or as passed? or something else? should "expired challenges" be filtered out by blobber (currently) or pre-filtered by sharder too?

@guruhubb

**Comment by guruhubb** [comment]
Yes expiration time is set by the blobber in 0chain_blobber.yaml (blobber repo).Its called `challenge_completion_time`.  It serves as a SLA (service level agreement) and the blobber gets paid for storage only when they pass challenges, and their stake test slashed when they fail. See @Sriep implementation for payment/slash based on challenges pass/fail.

Yes expired challenges are considered failed challenges. Yes they need to be pre-filtered by sharder based on the API request where the blobber can ask for all challenges, or non-expired challenges.

**Comment by andrenerd** [comment]
@guruhubb 
If the "ChallengeCompletionTime" field should be used, it was already implemented:
https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/challenge.go#L412

so barely any updates are needed.
going to close the issue.
