### ISSUE TITLE
Duplicated tests in state_handler_test

### ISSUE THREAD

**Issue by andrenerd** [0chain/0chain#376]
Please, clarify the code:
https://github.com/0chain/0chain/blob/master/code/go/0chain.net/chaincore/chain/state_handler_test.go

There are duplicated tests there. Probably all of them. For example, this one:
"Faucet_/pourAmount_Decoding_Global_Node_500"

If there is no reason behind it, please, clean it up.

**Comment by guruhubb** [comment]
@andrenerd please go ahead as @MurashovVen is busy with the other project
