### ISSUE TITLE
Bad stringified json format on transaction_output field from TransactionConfirmationHandler

### ISSUE THREAD

**Issue by shaktals** [0chain/0chain#415]
As per [this issue](https://github.com/0chain/js-client-sdk/issues/35) opened on `js-client-sdk`, the _transaction_output_ field received from 0chain's [TransactionConfirmationHandler](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/sharder/handler_main.go) has a stringified _json_ content, but it is badly formatted. Here is what is coming through to `go-sdk` now:

![Selection_038](https://user-images.githubusercontent.com/24679343/126577281-525441ba-e87f-480d-98cd-4ea0781910a4.png)

And here is what we get from the `js-client-sdk`:

![Selection_037](https://user-images.githubusercontent.com/24679343/126577641-1ad08f70-53c4-4401-8d5a-7f74a5d62423.png)

If we are to send a collection of objects to be parsed as json, they should be put in a comma separated object array `"[{}, {}, {}]"`.

**Comment by shaktals** [comment]
Bump :+1:

**Comment by shaktals** [comment]
Actually, this should not have been closed. It has been worked around, but the issue is still there.
If someone can help me with the draft PR #531 I'll be happy to finish it and fix this.

**Comment by ma2b0043** [comment]
@shaktals when can we expect to close this issue?

**Comment by shaktals** [comment]
@ma2b0043 can you help me with #531?

**Comment by ma2b0043** [comment]
> @ma2b0043 can you help me with #531?

isnt it closed @shaktals ?

**Comment by shaktals** [comment]
> > @ma2b0043 can you help me with #531?
> 
> isnt it closed @shaktals ?

It's closed because I wasn't able to finish the PR.
The web frontend team needed lots of attention, so I have done basically nothing on the backend yet.
Feel free to pick that PR and finish it.

**Comment by uneet7** [comment]
Hi, @shaktals , can you please post a detailed payload or a bit about the command that you are executing? I think I got the issue.
