### ISSUE TITLE
Add package/classes/category filter on logging

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#417]
There is only `LogLevel` filter on logging. It is difficult to debug zcn with logging. Because it is too much noise on logging even `LogLevel` is error.

It is better to set different loglevel for different packages/classes/category like log4j http://logging.apache.org/log4j/1.2/manual.html

```
import com.foo.Bar;

 // Import log4j classes.
 import org.apache.log4j.Logger;
 import org.apache.log4j.BasicConfigurator;

 public class MyApp {

   // Define a static logger variable so that it references the
   // Logger instance named "MyApp".
   static Logger logger = Logger.getLogger(MyApp.class);

   public static void main(String[] args) {

     // Set up a simple configuration that logs on the console.
     BasicConfigurator.configure();

     logger.info("Entering application.");
     Bar bar = new Bar();
     bar.doIt();
     logger.info("Exiting application.");
   }
 }
```

And it should be easy to turn on/off `MyApp.class` filter on config file.

**Comment by PratikDhanave** [comment]
@cnlangzi I like to work on it.

**Comment by ma2b0043** [comment]
@cnlangzi when can we expect to close this issue?

**Comment by dabasov** [comment]
@cnlangzi is it correct repo for this issue?
