### ISSUE TITLE
Block merge if code smells on new code is not resolved

### ISSUE THREAD

**Issue by stewartie4** [0chain/0chain#423]
We currently have a code smell reporter in the form of lint.
However there are a few tweaks we could make.

- Smells should only be reported for the current code being changed (delta against develop)
- Smells do not currently block a PR from merging. This should be automated and enforced
- Only a few lints are enabled, we should increase the number of rules

**Comment by Sriep** [comment]
Also link to https://github.com/0chain/0chain/issues/202

**Comment by Sriep** [comment]
Close completed.
