### ISSUE TITLE
[Teardown] At the end of the pipeline tear down the deployed chain OR have a scheduled job that runs on a daily basis to do this

### ISSUE THREAD

**Issue by stewartie4** [0chain/0chain#428]
To save on resources the pipeline could tear down the deployed instance of the blockchain.

This has a few downsides:
- A subsequent run will need to spin up an entire blockchain again
- The developer may want the stack to remain for subsequent manual testing

Therefore another solution would be to create a daily cron job to clear down the kubernetes namespace based on age of deployment

merging of a PR could also be a trigger to delete a running stack

**Comment by Sriep** [comment]
Completed.
