### ISSUE TITLE
Hard coded smatcontract owner

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#432]
This could be a security problem. Would it be better to set up these values as part of chain genesis?

**Comment by guruhubb** [comment]
yes, these need to different along with chain ID for every network we deploy, so needs to be generated at the onset and then used in yaml to deploy the network. But this is more of a deployment issue, but I agree we need to parameterize this and have a yaml to generate these address at the time of deployment.

**Comment by anish-squareops** [comment]
@Sriep please add more details on "how to generate these".

**Comment by Sriep** [comment]
I assume the same way as any other (id, public key, private key) triplet the administrator of the chain presumable guards the private key. Check out `./zwallet register`.
