### ISSUE TITLE
The BC won’t create a challenge for an allocation is blank

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#450]
https://github.com/0chain/0chain/blob/782dcfc53fee1751080f94657314ee287e9b99f0/code/go/0chain.net/smartcontract/storagesc/challenge.go#L608

blobber will throw an error and mark it as failed if a challenge is opened for a blank allocation. so please check it before opening a challenge for a allocation

**Comment by Sriep** [comment]
Moved into https://github.com/0chain/0chain/issues/579

**Comment by cnlangzi** [comment]
@peterlimg  @sum-it08  it seems be not fixed yet.


<img width="1431" alt="Screen Shot 2022-06-15 at 15 46 47" src="https://user-images.githubusercontent.com/347651/173772021-8f651439-e03d-422f-b77b-1a474d9f25fe.png">

**Comment by cnlangzi** [comment]
it is caused by expired challenges.
