### ISSUE TITLE
PR/master pipeline: integrate and run conductor tests in the pipeline

### ISSUE THREAD

**Issue by stewartie4** [0chain/0chain#465]

**Comment by ma2b0043** [comment]
@dabasov can we close this issue?

**Comment by dabasov** [comment]
no, it's not completed

**Comment by service-0chain** [comment]
gitactions are already in place but there are issues in running conductor tests as below:

- https://github.com/0chain/0chain/actions/workflows/conductor-complex-scenarios-tests.yml
- https://github.com/0chain/0chain/actions/workflows/conductor-blobber-tests.yml
- https://github.com/0chain/0chain/actions/workflows/conductor-standard-tests.yml

**Comment by service-0chain** [comment]
We cannot integrate it into cicd pipeline as conductor test takes time to complete. That is they are scheduled to run on daily basis. Related to subtask in [same](https://github.com/0chain/0chain/issues/1198) tickets.
