### ISSUE TITLE
Can't get unlock token transaction confirmation from sharder

### ISSUE THREAD

**Issue by shaktals** [0chain/0chain#471]
After doing a successful `PUT` request to all miners, I get a `400` from sharders when trying to `GET` confirmation:

Successful PUT:

![Selection_061](https://user-images.githubusercontent.com/24679343/128915429-3c24686b-0eb3-4e4f-86d6-57a63673faf6.png)

Bad request response from sharder:

![Selection_062](https://user-images.githubusercontent.com/24679343/128915586-4c6b304f-d6d0-4562-83c6-d67c0a396fc2.png)

I get the same result from the endpoint when using `postman`.

**Comment by shaktals** [comment]
Even minutes after the successful PUT, I can't get the confirmation.

**Comment by Sriep** [comment]
You did an `unlock` transaction and despite the transaction being successful and the tokens being unlocked you could not find the transaction listed?  Is this correct?

Is this a one-off or repeatable? 

I tried the sharder get and it worked for me. Difficult to see why the `unlock` command would be singled out in any way. My guess is that it was an environmental problem.

**Comment by shaktals** [comment]
> You did an `unlock` transaction and despite the transaction being successful and the tokens being unlocked you could not find the transaction listed on the sharder? Is this correct?

That seems correct, the tokens are unlocked but the `transaction/get/confirmation` endpoint returns 'entity not found'.

> Is this a one-off or repeatable?

Consistently repeatable.

> I tried the sharder get and it worked for me. Difficult to see why the `unlock` command would be singled out in any way. My guess is that it was an environmental problem.

The same `get/confirmation` endpoint works fine when locking tokens, staking them, etc.
I just tried the same operation on `zwallet-cli` and got a similar error, here is the [image](https://user-images.githubusercontent.com/24679343/129240242-faf1635a-df13-4ac6-a9d3-505c93970cab.png).

**Comment by shaktals** [comment]
Sorry, this was totally my misunderstanding of the locking process.
I was not waiting for the `locked` time to pass.
If we wait that time, works perfectly,

But so, I think the `[miner]/v1/transaction/put` endpoint should return an error if the user tries to unlock a token before it's locked time is complete. I'll open an issue there.

**Comment by Sriep** [comment]
Ah, I understand. I am not sure an error is appropriate as the tokens have actually been unlocked, just the unlocking is delayed until it is possible. Better would be a warning as this is an easy gotcha to fall for.

**Comment by shaktals** [comment]
Oh, the unlock request actually succeeds then, but the action is postponed to when the locked term is over. Got it. Linking #478 to this.
