### ISSUE TITLE
Inform release round and txn amount on deleteFromDelegatePool txns

### ISSUE THREAD

**Issue by shaktals** [0chain/0chain#493]
@Sriep, I just asked @guruhubb about some transactions that are being called `Unstake Tokens` on explorer. Upon checking details we see that the transaction name is `deleteFromDelegatePool`. Two things Saswata mentioned:

- the txn output action prop should be `pool will be released in round xxx` and not `next VC`
- the txn amount should be informed (maybe in the output itself?)

Here is a txn example:

[Selection_076](https://user-images.githubusercontent.com/24679343/129973760-9a8be3f0-dc7c-46e1-9fb7-ff0edefd0185.png)

**Comment by Sriep** [comment]
[deleteFromDelegatePool]((https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/minersc/delegate_pools.go#L106)

#### deleteFromDelegatePool

1. Gets user's pool from the blockhain. Finds the pool to be deleted.
2. Checks the pool's status.
3. If the pool is `DELETING` does nothing.
4. If the pool is `PENDING` it removes the pool from the miner and Transfer funds to the pool's owner.
5. if the pool is `ACTIVE` it sets the status to `DELETING`. Added to a list of [Deleting pools](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/minersc/models.go#L489).

#### DELETING status

if `sc.yaml.minersc.reward_round_frequency` is greater than zero, then every time the round number is an exact multiple of `reward_round_frequency` all pools in the list of `Deleting pools` are deleted and funds transferred to the owner. This is in the `minersc.payFees` smart contract which is run every round.

if `sc.yaml.minersc.reward_round_frequency` is zero then this never happens, so active pools are not deleted.

**Comment by shaktals** [comment]
As for the _frontend_, I think the most important part is to return the txn amount in the response. Is it feasible?

As for the release round info, I don't see it as high priority, but to clarify:

if `reward_round_frequency` > 0, we'd have to calculate the round where the pool would be released,
if `reward_round_frequency` == 0, it's just released in the next round?

As I understand, Saswata didn't ask for a behavior change, just to update/adjust the response info.

**Comment by Sriep** [comment]
```
As for the frontend, I think the most important part is to return the txn amount in the response. Is it feasible?
```
By transaction amount do you mean the amount of money in the pool? Should be able to change. 

ATM if the pool is pending and the money is actually deleted (status=pending) then the json of the transfer request is returned by 0chain. Otherwise, the hardcoded value `{"action": "pool will be released next VC"}`. Whatever tool is pointing to 0chain might have to be modified as well.

```
calculate the round where the pool would be released,
```
It should be possible to change deleteFromDelegatePool to return the number of rounds before deletion plus the number of tekns in the pool being deleted. 

Don't worry about `reward_round_frequency == 0`, it probably indicates a malformed chain?

**Comment by shaktals** [comment]
> By transaction amount do you mean the amount of money in the pool? Should be able to change.

Yeap. 

> ATM if the pool is pending and the money is actually deleted (status=pending) then the json of the transfer request is returned by 0chain. Otherwise, the hardcoded value `{"action": "pool will be released next VC"}`. Whatever tool is pointing to 0chain might have to be modified as well.

Do we have tools depending on that return message? It looks like generic info. But we could ask that around on slack to confirm.

> It should be possible to change deleteFromDelegatePool to return the number of rounds before deletion plus the number of tekns in the pool being deleted.

Sounds excellent!

**Comment by Sriep** [comment]
The main tools I am thinking of are zwallet and zbox. One of these will need updating.

**Comment by shaktals** [comment]
Cool, if you need a hand let me know!

**Comment by Sriep** [comment]
Moved to https://github.com/0chain/block-explorer/issues/454
