### ISSUE TITLE
Failed opening the RDB file state.dump.rdb (in server root dir /0chain/data/redis/state)

### ISSUE THREAD

**Issue by mohsenno1** [0chain/0chain#502]
Running a chain of 3 miners and 1 sharder on local using dockers. After few minutes redis start to log this error on console.

```
redis_1       | 1:M 26 Aug 2021 13:32:14.101 # Background saving error
redis_1       | 1:M 26 Aug 2021 13:32:20.032 * 1 changes in 900 seconds. Saving...
redis_1       | 1:M 26 Aug 2021 13:32:20.032 * Background saving started by pid 2383
redis_1       | 2383:C 26 Aug 2021 13:32:20.032 # Failed opening the RDB file state.dump.rdb (in server root dir /0chain/data/redis/state) for saving: Permission denied
```

this can be related to #74 issue. Since the redis documentaion emphasizing on storing to the disk. 

> Docker redis container passed dump.rdb File for data migration or data recovery.

this issue can be also related to #state hash mismatch on miners.

![redis error](https://user-images.githubusercontent.com/19901130/130971373-d1a50eda-2a71-4b42-9ed8-27ea8b09d352.png)

**Comment by guruhubb** [comment]
@mohsenno1 you can put this in the Debugging section of the readme.

**Comment by mohsenno1** [comment]
@guruhubb it's not comfortable to run this bunch of commands every time someone wants to create the chain on dockers. So I added two lines to set this permission in `init.setup.sh`.

can you check this commit on staging branch: d6e6f8cb6d506e319a52fbdca35689301d463dae

**Comment by Sriep** [comment]
Is this still a problem?

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by cnlangzi** [comment]
I think it is fixed now.
