### ISSUE TITLE
Regression: Send ZCN with transaction data (note) is broken in testnet

### ISSUE THREAD

**Issue by stewartie4** [0chain/0chain#510]
API regressions are failing on testnet. See:
https://0chain.github.io/0chain/test/2021-09-04_15.32.13/index.html#pills-requests/folder-338bed6e-fae9-44e3-b9f7-15db9377a1e4-iteration-0/requests-60c83dde-26d5-491f-86c7-de7b47a06548 

When attempting to send ZCN with transaction data the following response is returned: 
![image](https://user-images.githubusercontent.com/18306778/132100193-49778e8e-065c-4314-a209-458008d0e33e.png)

The same response is being thown in block-explorer
![image](https://user-images.githubusercontent.com/18306778/132100212-09e51566-3890-419f-87cf-661024664df0.png)

Sending ZCN without transaction data on or with transaction data on betanet continues to work fine

**Comment by Sriep** [comment]
The `invalid transaction data` comes from the [Transaction.ValidateFee](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/transaction/entity.go#L110) method. 
```go
		var smartContractData smartContractTransactionData
		dataBytes := []byte(t.TransactionData)
		err := json.Unmarshal(dataBytes, &smartContractData)
		if err != nil {
			logging.Logger.Error("unmarshal txn data failed", zap.Error(err))
			return errors.New("invalid transaction data")
		}
```

An attempt is made to unmarshal the transaction data into a [smartContractTransactionData](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/transaction/entity.go#L86) object.
```go
type smartContractTransactionData struct {
	FunctionName string          `json:"name"`
	InputData    json.RawMessage `json:"input"`
}
```

The transaction data is
```
"transaction_data": "Message to recipient",
```
and correctly fails to unmarshal. Hence we get the reported error.

It seems to me that the endpoint `https://test.0chain.net/miner01/v1/transaction/put` is correct to return an `invalid transaction data`` as the transaction data cannot be unmarshalled correctly.
 
The only issue I see is here is that the error returned by `json.Unmarshal` is lost. we should replace
```go
return errors.New("invalid transaction data")
```
with
```go
return fmt.Errorf("invalid transaction data, %v", err)
```
or similar

**Comment by stewartie4** [comment]
@Sriep yeah as we've mentioned in slack, this is a change in behaviour from how things worked before and therefore the CLIs and block explorer is broken
if these repos are updated to send a json object then i see no issue

**Comment by Sriep** [comment]
Moved to https://github.com/0chain/0box/issues/40 and https://github.com/0chain/block-explorer/issues/455

**Comment by shaktals** [comment]
@Sriep @stewartie4 I think this should **not** be closed.

All other transaction types **only** accept the `note` prop as a string.
Only the `Send ZCN` transaction now requires it to be an object `{}`.

So, when calling `/miner01/v1/transaction/put` the clients will have to change the payload format based on the transaction type.
We can workaround it, but it's very ugly in my opinion and should be fixed.

Let us know, this issue has been around for weeks now.
