### ISSUE TITLE
Allow anyone to extend allocation

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#538]
~~Modify `zbox update allocation`, with a new `--update-positive-expiry` option. This will allow anyone to lock tokens in an allocation to extend it's expiry.~~

~~Add a --no-expiry flag for an allocation. If this is set, the expiry period cannot be reduced and the allocation cannot be cancelled or finalized.~~

**Comment by guruhubb** [comment]
Also we should have by default prevent users from reducing the expired period since there is already a cancel allocation command.

**Comment by Sriep** [comment]
Modify update allocation as follows.
1. Allocations cannot have their duration reduced.
2. A new `NFT` which can be set in a new location request; defaulting to false. It allows anyone to extend the allocation.

**Comment by Sriep** [comment]
closed replaced by https://github.com/0chain/0chain/pull/620
