### ISSUE TITLE
Update allocation request - improve performance

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#568]
Update location request is linear in the number of shards. The benchmark suggests taking around 2-4ms per shard, so only takes around 15 shards before exceeding 50ms.

We could either aim at making updateAllocaiontRequest more efficient in general or look for ways to reduce the linear dependency. 

[This block of code](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L793) seems to be a particular issue roughly doubling the time taken. 
```go
	// extend offers after alloc.challenge_completion_time is known
	for _, ba := range alloc.BlobberDetails {
		if err := sc.updateSakePoolOffer(ba, alloc, balances); err != nil {
			return common.NewError("allocation_extending_failed",
				err.Error())
		}
	}
```

**Comment by Sriep** [comment]
The time [updateStakePool](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L879) takes seems to be split between getting the stake pool from the MPt and saving to the MPT. The aim here is to update the stake pools with updated stake information.

Ideas for improving include.
1. Chacking we really need to update an offer before we get the stake pool.
2. Update the stake pools in parallel. Use go routines and wait-groups or channels to get any error returned.
3. Investigate alternate ways of storing the offer information. Maybe store offers in a separate object.
4. We could save stake pool updates in the balance object and them all at once at the end of the round. 

1 and 2 should be fairly straightforward to implement. Tests indicated (2) halved the benchmark time for update allocation, from 120ms to 60ms.

3. I think it might be a good idea to store the offers separately from the stake pool. They can be treated independantly.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
