### ISSUE TITLE
Validators - remove if stake is too low.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#587]
Have a minimum stake for validators. Remove validators that have too low a stake.

**Comment by Sriep** [comment]
To do this the validator should be added or removed from the list of validators used during challenge creation during StakePoolLock and StakePoolUnlock respectively. 

the existing `all validators list` is soon to be replaced by `all validator partitions`. It would be best to delay this change until then. https://github.com/0chain/0chain/issues/785

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by iamrz1** [comment]
TBD after https://github.com/0chain/0chain/pull/1439
