### ISSUE TITLE
0chain events

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#593]
0Chain's MPT currently holds a lot of data that is only used by REST API endpoints to return data to users. This data does not need to be in the MPT, It bloats the size of the MPT, and slows down endpoints that maintain the data.

We should create a row focused `stats database` to support data queries. 

This database will be write-only for smart-contract endpoints, this will allow the `stats database` to be updated in parallel and hence not slow down smart-contract execution.

REST API endpoints will mostly use the `stats database` for read-only access to get data about a particular object.

If the `stats database` gets damaged, we can run a parallel repair program that rebuilds the database over time.

**Comment by Sriep** [comment]
We need to decide what database type to use. `MySQL`, `Postgres`, `SQLite` etc. Probably Postgres as Blobber uses it.

**Comment by Dmdv** [comment]
@Sriep Postgres of any other DB such MySQL or SQLite

**Comment by Sriep** [comment]
To make this a bit more explicit I am proposing that 0chain emit events in the same way that Ethereum/Solidity smart contracts emit events.

An ethereum smart contract can emit events. Events are text strings that are kept in a searchable filterable list or log.  But are unavailable to any smart contract once emitted.

Solidity programmers could than write a tool that polls for new events from their smart contracts and uses them. Maybe the events are actually SQL statements that the Solidity programmer can run on his database, which he provide as a service to 3rd parties.

I am suggesting that 0chain emit events. For example an event might be a new challenge that has just been created, or an existing challenge that has been resolved.

Rather than have blobbers, say, use the event log directly we write a database application that takes the events, adds them to a database that is used to support our existing REST API.

A lot of experience has gone into creating Ethereum events so we could use this as a guide in creating 0chain events. (edited)

**Comment by Sriep** [comment]
https://github.com/0chain/0chain/issues/434 and https://github.com/0chain/0chain/issues/448 should be taken into consideration.

**Comment by Sriep** [comment]
![image](https://user-images.githubusercontent.com/6240686/140149768-d50bd581-1f71-4fc2-91d6-f7064a29950e.png)

![image](https://user-images.githubusercontent.com/6240686/140150349-1fbe7941-5241-45cc-8817-bc5b4d48993f.png)

**Comment by Sriep** [comment]
Move stats db part to https://github.com/0chain/0chain/issues/653

**Comment by Sriep** [comment]
Done in https://github.com/0chain/0chain/pull/655. Stats db merged with events db, but stats part moved to other issues
