### ISSUE TITLE
List of all func & handler called from `0chain/gosdk` pkg.

### ISSUE THREAD

**Issue by twiny** [0chain/0chain#603]
List of endpoints that makes requests from `0chain/gosdk` to Miners, Sharders, Chain.

### Miners
| endpoint              | method | Client(s) name/url     | Handler name/url |
| ------------------    | ------ |------------- | -------------------- |
| `/v1/client/put`      |  POST  |[RegisterToMiners()](https://github.com/0chain/gosdk/blob/014599113a000183afc9b01a2372916f146363d4/zcncore/wallet.go#L453) | -
| `/v1/client/get`      |  GET   |[GetClientDetails()](https://github.com/0chain/gosdk/blob/014599113a000183afc9b01a2372916f146363d4/zcncore/wallet.go#L509) | -
| `/v1/transaction/put` |  POST  |[submitTxn()](https://github.com/0chain/gosdk/blob/014599113a000183afc9b01a2372916f146363d4/zcncore/transaction.go#L212) | -

| endpoint              | method | Client(s) name/url     | Handler name/url |
| ------------------    | ------ |------------- | ------- |
| `/v1/screst/`      |  GET  | Multiple. Defined Below.| [HandleSCRest()](https://github.com/0chain/0chain/blob/15b1511a03e10fa38c8a55fd4a12ab71e627f2b4/code/go/0chain.net/chaincore/chain/state_handler.go#L27)

### Chain

**Comment by Sriep** [comment]
What is the issue here?

**Comment by twiny** [comment]
> What is the issue here?

@Sriep no issues here - this just to keep track of functions that make HTTP requests  from `0chain/gosdk` to sharders, miners and chain..

**Comment by Sriep** [comment]
The issue database is for issues that need to be resolved. Could you move this to the wiki? I'll close this shortly.

**Comment by twiny** [comment]
Alright @Sriep  - i've moved it to the Wiki section.
