### ISSUE TITLE
Lock tokens in write pool, target_id not working as expected

### ISSUE THREAD

**Issue by moldis** [0chain/0chain#608]
It seems tokens are staling somewhere when I am trying to lock them in the write pool. 

Payload to lock tokens:

Calling SC txn with values     
`
{"txn": {"hash":"be2195dae8b493f4c18d8ae196a3325acac683c696d15a2d78d7bdd5aa3dcf17","version":"1.0","client_id":"2de380c3ce18e0a62a14aa7a12e2aaaa591e8f145d507f8e8330510d4febae1f","public_key":"671da197a53b8783ea3ca96400faf4550af7edb4c6837b52b013a5b54b50011e9183f81022a6e35680934e6a9eb9913ddd5d0286e16b2a4a51c67ba1f95fc207","to_client_id":"6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7","chain_id":"0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe","transaction_data":"{\"name\":\"write_pool_lock\",\"input\":{\"allocation_id\":\"913aa94f48ec1645333b50333c0a2d9f074a801fa8f0c0cca7fe07bdc6e659ee\",\"duration\":2591053280079942,\"target_id\":\"434b0fdede52de4408ec49fbe37b99890780e8232604d45aa15e8336d6e8df23\"}}","transaction_value":19000092610,"signature":"affdb24bfc80e4b9c1ee6867d1cda6e80cd1055c88f641e3c9674ddd58f43193","creation_date":1635338984,"transaction_type":1000,"transaction_fee":0,"txn_output_hash":""}}`

Response:
`Txn hash        {"hash": "be2195dae8b493f4c18d8ae196a3325acac683c696d15a2d78d7bdd5aa3dcf17"}`

The next call to wp-info does not include the transaction above. 

Sample transactions, target_id is a real active wallet, but it didn't receive the expected amount of tokens to his write pool.
https://dev.0chain.net/transaction/ae50759703349a8082a1490c8990ab47d7ac8201c49122d64c1f76f2a2b1cfea

Will continue to investigate on my side.

cc @Sriep @guruhubb

**Comment by ma2b0043** [comment]
@moldis when can we expect to close this issue?

**Comment by Sriep** [comment]
Write pools have been completely rewritten since this issue. Closing as outdated.
