### ISSUE TITLE
Do not send entity requests to threshold number of miners all  at the same time

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#613]
Previously, we have refactored to send entity requests to threshold of miners instead of all miners concurrently to save network and cpu resources, but this is not enough, as when network size increase, the threshold number could be large too. An easy way to improve this is send requests to a fixed number of miners concurrently. For example 4 miners, returns immediately if any of them give valid response, or chose another 4 new miners to send  requests to, repeat till we got a valid response or timeout.

**Comment by guruhubb** [comment]
have you looked at [discussion here](https://0chain.slack.com/archives/G01FYNN6DK4/p1635279499025800?thread_ts=1634223012.165300&cid=G01FYNN6DK4 ) based on entity requests needed for practical Byzantine scenarios.

**Comment by peterlimg** [comment]
Yes, I'll try the 10 percent.
