### ISSUE TITLE
Rejected verification tickets for the best rank

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#626]
These two checks are contradictory. We can collect VRF tickets for current round even if verification is already done and at least one block is notarized. It is fully align with protocol, we can get several notarized blocks for one round. 
Second check seems to  be ok, but the first one will reject all verifications. 

We should process all verifications for proposal even if verification is done for the same rank (we can reject verifications for lower ranks though).

```go
func (mc *Chain) HandleVerificationTicketMessage(ctx context.Context,
	msg *BlockMessage) {
...
	if mr.isVerificationComplete() {
		logging.Logger.Error("handle vt. msg -- round verification completed", zap.Int64("round", rn))
		return
	}

... 
	var lfb = mc.GetLatestFinalizedBlock()
	if b.Round < lfb.Round {
		logging.Logger.Debug("verification message (round mismatch)",
			zap.Int64("round", b.Round), zap.String("block", b.Hash),
			zap.Int64("lfb", lfb.Round))
		return
	}
...
}
```

**Comment by peterlimg** [comment]
Yes, the first check should be removed, I'll fix it.
