### ISSUE TITLE
Refactor entity fetching

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#630]
We need to request entities in three ways:
1. Get single entity from single node (we have this one)
2. Get single valid node from several nodes
3. Get single entity from majority of nodes with consensus on data

@peterlimg did good work on improving this functionality, but it can be improved more. 
For case 2 we should check validation in every `handler` there are a lot of handlers with missed validation, look [https://github.com/0chain/0chain/wiki/fetching](fetching) for more details
For case 3 we should add honest consensus on data

**Comment by peterlimg** [comment]
@dabasov seems https://github.com/0chain/0chain/wiki/fetching does not exist.

For case 2, we will send requests to N nodes, and queue the responses in a channel, we do not validate all of them concurrently as it would use lot of CPU resources. Instead, we get the response from the channel and validate them one by one, and return if any one is good, so the rest responses in the channel will all be dropped.

**Comment by dabasov** [comment]
I'm talking about byzantine agreement [more details](https://arxiv.org/pdf/2003.13155.pdf). Briefly, when we can't validate data (for example on `*round.Round`) but we want to agree on it, all nodes can broadcast it simply choose the majority of identical values. Since we have minority of faulty nodes, this approach will work obviously. It was called consensus on fetching previously in 0chain code. 
I agree with you that it is very expensive way to proof data, and should be used only when there are now other way to prove it. But it is not the same as take the first one (eg for round or partial state)

**Comment by dabasov** [comment]
resolved
