### ISSUE TITLE
Stake pool, min lock period.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#645]
Add a [sc.yaml.storagesc.stakepool.min_lock_period](https://github.com/0chain/0chain/blob/staging/docker.local/config/sc.yaml#L87). Defaoult min lock period is 3 years worth of blocks, say 

Modify [stake pool lock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L921) to support the new min_lock_period setting with an extra verification step.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by cnlangzi** [comment]
@peterlimg  @Sriep  what happens if token expires by lock_period? should it be unlocked automatically?
