### ISSUE TITLE
Remove challenges for deleted files.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#646]
WrtieMarkers need to be sent to chain when we `add` a new file, `update` a file, `delete` a file, `copy` or `move` a file, and `rename` a file.

0chain needs to make appropriate changes to challenges. For instance, removing challenges for deleted files. Some of this already works, for example when a file is added. We need to fill in the blanks.

This needs to be coordinated with a matching change to the blobber.

Any crud action that changes the tree is reported to the chain because the Merkle root of the allocation changes as a result

**Comment by Sriep** [comment]
The blobber should send the above WMs today otherwise the root is not consistent.  So the code is already there.
So on storagesc we may need a labelling mechanism to detect deletion of data. 

Or we can keep things simple. If the root of the allocation changes and that allocation has an open challenge, then the smart contract should remove it.

So during processing of WM, check if an open challenge is associated with it. If so, then cancel the challenge.  No code change on the blobber.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
