### ISSUE TITLE
"Nodes fail and recover randomly" test fails

### ISSUE THREAD

**Issue by rrrooommmaaa** [0chain/0chain#651]
Somehow the "Nodes fail and recover randomly" of `no-view-change.fault-tolerance` fails on `staging` branch.
The chain gets stuck whenb the single sharder goes down and never grows after the sharder comes up again.

**Comment by ma2b0043** [comment]
@dabasov there is no one assigned to this issue.

**Comment by fabioDMFerreira** [comment]
@rrrooommmaaa have you found which specific test is intermittently failing?

**Comment by rrrooommmaaa** [comment]
According to https://github.com/0chain/0chain/runs/6628857095?check_suite_focus=true
there is a number of failures. Most of them are simply fail to reach a certain round within the allowed timeout.
These look totally dead:
Test case 0: All sharders go down and come up
Test case 1: Generators fail at start of round

**Comment by fabioDMFerreira** [comment]
@rrrooommmaaa I guess this issue is already resolved. Check this out https://github.com/0chain/0chain/runs/6681477035?check_suite_focus=true. This ran 12 hours ago

**Comment by rrrooommmaaa** [comment]
This run didn't run any tests for some reason

**Comment by fabioDMFerreira** [comment]
We need to specify we want to run this kind of test (view-change) when running the workflow. Re-running the workflow to check whether it is resolved.

https://github.com/0chain/0chain/actions/runs/2422061541

**Comment by fabioDMFerreira** [comment]
@rrrooommmaaa I changed the test slightly to run in a configuration of 7 miners and 1 sharder, and I've fixed some issues in the magic block. The test was hanging in the step `wait_add`.

Now, it is hanging on step `wait_view_change`. As far as I understood the view change feature is not implemented yet. @rrrooommmaaa is possible to have this test working or should we wait for the view change feature? Have this test passed before?

cc @dabasov

**Comment by rrrooommmaaa** [comment]
> Now, it is hanging on step `wait_view_change`. As far as I understood the view change feature is not implemented yet.

Are you sure you're running this test with `view_change: true` setting in `0chain.yaml`?
`view-change.fault-tolerance` should be run with `view_change: true`
`no-view-change.fault-tolerance` -- with `view_change: false`

**Comment by fabioDMFerreira** [comment]
Thanks for pointing that out. Any other configuration I need to change?

I can see more messages, but the `view-change` test still fails. See below the messages printed:
```
2022/06/11 15:20:01.955580 main.go:407:  [INF] phase contribute sharder-1
2022/06/11 15:20:06.736929 main.go:668:  [INF] contribute mpk miner-5
2022/06/11 15:20:06.737592 main.go:668:  [INF] contribute mpk miner-4
2022/06/11 15:20:06.738589 main.go:668:  [INF] contribute mpk miner-1
2022/06/11 15:20:07.600059 main.go:668:  [INF] contribute mpk miner-3
2022/06/11 15:20:07.826292 main.go:668:  [INF] contribute mpk miner-7
2022/06/11 15:20:08.050609 main.go:668:  [INF] contribute mpk miner-6
2022/06/11 15:20:08.704453 main.go:668:  [INF] contribute mpk miner-2
2022/06/11 15:20:12.836751 main.go:407:  [INF] phase share sharder-1
2022/06/11 15:20:23.685382 main.go:407:  [INF] phase publish sharder-1
2022/06/11 15:20:26.760732 main.go:706:  [INF] share or sign shares miner-1
2022/06/11 15:20:26.767983 main.go:706:  [INF] share or sign shares miner-4
2022/06/11 15:20:26.778626 main.go:706:  [INF] share or sign shares miner-2
2022/06/11 15:20:27.194591 main.go:706:  [INF] share or sign shares miner-6
2022/06/11 15:20:27.640728 main.go:706:  [INF] share or sign shares miner-7
2022/06/11 15:20:27.657644 main.go:706:  [INF] share or sign shares miner-7
2022/06/11 15:20:30.667300 main.go:706:  [INF] share or sign shares miner-3
2022/06/11 15:20:31.321844 main.go:706:  [INF] share or sign shares miner-5
2022/06/11 15:20:31.337949 main.go:706:  [INF] share or sign shares miner-5
2022/06/11 15:20:34.591267 main.go:407:  [INF] phase wait sharder-1
2022/06/11 15:20:45.442222 main.go:407:  [INF] phase start sharder-1
2022/06/11 15:20:56.304995 main.go:407:  [INF] phase contribute sharder-1
2022/06/11 15:20:56.314983 main.go:407:  [INF] phase contribute sharder-1
2022/06/11 15:20:56.323270 main.go:407:  [INF] phase contribute sharder-1
2022/06/11 15:21:01.717299 main.go:668:  [INF] contribute mpk miner-4
2022/06/11 15:21:01.719610 main.go:668:  [INF] contribute mpk miner-7
2022/06/11 15:21:01.723470 main.go:668:  [INF] contribute mpk miner-1
2022/06/11 15:21:01.724522 main.go:668:  [INF] contribute mpk miner-6
2022/06/11 15:21:01.726011 main.go:668:  [INF] contribute mpk miner-3
2022/06/11 15:21:02.155304 main.go:668:  [INF] contribute mpk miner-2
2022/06/11 15:21:04.765416 main.go:668:  [INF] contribute mpk miner-5
2022/06/11 15:21:07.154567 main.go:407:  [INF] phase share sharder-1
2022/06/11 15:21:07.164733 main.go:407:  [INF] phase share sharder-1
2022/06/11 15:21:17.958445 main.go:407:  [INF] phase publish sharder-1
```

Any tip on where to look at? The wait phase is the last phase of the view change, but the test doesn't proceed.

**Comment by rrrooommmaaa** [comment]
> I can see more messages, but the `view-change` test still fails.

Should there actually be a view change? All the 7 miners are already in the magic block in this setup, and miner-8 isn't running, or am I wrong? I'm not sure what should happen by the protocol in the situation where the magic block remains the same because there are no new miners to be added. This may or may not be a bug.
