### ISSUE TITLE
Use different StateContext interface for smarcontracts and REST endpoints

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#657]
Smart contracts and REST endpoints have a different sets of operations that they are permitted to perform. The StateContext interface they are passed should reflect that.

For example Rest endpoints might have `GetTrieNode` but not `InsertTrieNode`.

**Comment by dabasov** [comment]
Excellent idea! narrowing write-set is always good

**Comment by Sriep** [comment]
I started it in here https://github.com/0chain/0chain/pull/658, but put on for the moment.

I suggest four interfaces.
1. For smartcontracts.
2. For REST API.
3. The intersection of 1 and 2 for common functions. Probably only `GetTrieNode`.
4. For chain operations outside of endpoints. For example `GetEventDb`, `GetMints` and `GetTransfers`.

For example (1) will have `InsertTrieNode` but not `GetEventDb` while the reverse will be true for (2).

**Comment by Sriep** [comment]
I suggest all new Event database API endpoints use a new restricted StateContextI object. With `GetTrieNode` and only add other methods if needed. In the longer term we will want to remove the StateContextI object altogether and replace with a link to the eventDb.

**Comment by Sriep** [comment]
Smart contracts should not be able to use GetEventDb, having this function available can confuse developers into using it. For example, smart contracts can't know if the event database is up or not. However, the chain meta operations needs to use GetEventDb.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
