### ISSUE TITLE
New Allocation Request

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#668]
New Allocation will no longer choose the blobbers, instead, the client will include a list of blobbers with the new allocation request. 

The [selectBlobbers](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L342) method can be reduced. Instead, it will only verify the user-selected blobbers as in [filterBlobbers](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L428); which can be improved to provide better error messages for the end user https://github.com/0chain/0chain/issues/540. 

The preferred blobbers field can be repurposed and renamed as needed. 

Changes to gosdk https://github.com/0chain/gosdk/issues/297 and zbox https://github.com/0chain/zboxcli/issues/125 will be needed to support this.

This is a rewrite of https://github.com/0chain/0chain/issues/569.

**Comment by moldis** [comment]
Pushed https://github.com/0chain/0chain/pull/684

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by dabasov** [comment]
fixed
