### ISSUE TITLE
Blobber block rewards

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#669]
### Intorduction

The current implementation takes too long so we need to rework it. This is particularly complicated and the algorithm outlined below might need to modified. 

The basic idea is that for each block we pay the blobber's linked wallet a sum. This sum is to based on the blobber's capabilities in comparison to the other blobbers. This calculation is too time-intensive to actually be carried out each block so we have to restrict the calculation to once every `N` blocks, the block reward period. By allowing this period to be configurable we ensure that block rewards payment transactions will not adversely affect the blockchain. 

### Reward

Conceptually every block a fixed payment `block_reward` is split between all blobbers according to some blobber-metric. For each blobber their metic is compared to the total sum for all blobbers and that is the proportion of the total `block_reward` that is minted for the blobber's wallet.

We are intending to use `total stake * total challenges * write price ` as the metric. But should keep the flexible so it can be modified later. 
```
Total = sum over all blobbers (total stake * total challenges * write price(last N blocks))
```
* `total state:` Add to the blobber object a total stake field. Do not include unstaking stakes. Update this total on each lock and unlock.
* `challenges(N):` The number of challenges completed during the last N blocks. Increment on each successful challenge and zero at the start of each block reward period.

### Block Reward Period

The block reward period `BWP` is is configured in the `sc.yaml`. Block reward payments are spread over BWP rounds based on information from the previous BWP.

Example: `BWP = 100` for rounds 1100 to 1200. 9,000 blobbers.

1. `Round 1000`. Select random round between 1001 and 1100. Call this (1000+d)
2. `Round 1000+d` Store in the MPT the total metric ( = total stake * challenges) for all blobbers. The current value should be in MPT and updated continuously.
3. `Rounds 1100` Split up the blobbers 9,000 into 100, equal to within 1, groups of 90. We should keep blobbers in semi-random partitions to make this easier. Suitable partitions will be added in https://github.com/0chain/0chain/pull/588.
4. `Rounds 1101, 1200` Run a block rewards transaction, that pays rewards for 90 blobbers. This will use the total for round `1000+d` The blobbers for the current round having been selected on round 1100 (3). It will use the `for all blobbers totals` calculated on round `100+d`.

### New data 

1. A new blobber total stake field. This is the sum of non-unstaking stakes. An unstaking-stake is one that is needed to support the blobbers allocation load, but will be released as soon as possible. this should be  updated on every lock and unlock.
2. A new blobber field: The number of challenges passed during the current block reward period. Updaet this every time a challenge is passed and zeroed at the start of each block reward period.
3. A new blobber field: The number of passed challenges during the last block reward period, move from (3) at the start of each block reward period.
4. A new field for each blobber, the total stake multiplied by the number of challenges = (1)*(2). This need to be recalculated each time (1) or (2) changes. It is logically reset to zero at the start of each block reward period.
5. The current sum of the values for (4) for all blobbers, for the current period. This starts at zero for each period, with all blobbers contributing zero. Each time a blobber passes a challenge or a stake is locked or unlocked this total is changed. The old value for 4 for this particular blobber is subtracted and the new value for (4) is added. This total for all blobbers value is kept in the MPT and used to calculate the block reward.

### Constants

The block reward period needs to be estimated by benchmarking or other testing. Increasing the period as the number of blobbers increase. For a given block reward period there will be a maximal number of blobbers that the 0chain can sustain.

We might also explore the possibility of running multiple block reward transactions each block. Again this needs benchmarking to see if is really a usfull idea.

#### Notes

When completed will also want to integrate the existing miner and sharder rewards.

This is a continuation of https://github.com/0chain/0chain/issues/314

**Comment by illuyankas** [comment]
1- Suggest that we do a product of Challenges X Stake X Write Price. Total is updated on every write price update and/or every stake update. This saves us from doing a min write price implementation and protects against blobber centralization. 

2- Suggest we define the number and size of each partition. E.g. 100 partitions, 100 blobbers per partition. Every BWP, 10,000 blobbers or less get selected. These Blobbers get assigned to a partition randomly. For example if we have less than 10,000 blobbers, then some partitions get 90,85,20,100 etc - point is each partition has some blobbers in it.

3- On each block, each miner is randomly assigned to a partition. This ensures miners are shuffled across partitions as well.

**Comment by illuyankas** [comment]
In conjunction with above - 

1- Blobbers should be allowed to reduce their price after having been appointed to an allocation. This is to avoid stale allocations. No increase permitted. 

2- Miners should be rewarded for validation of these blobber block rewards. Maybe 2% goes to miners?

**Comment by guruhubb** [comment]
I think this is too complex and difficult to implement and socialize to community, and I don't see a clear need for any of changes at this late stage. We will revisit after launch when we can observe the market dynamics.  

Also, Re 1, stake is a function of write price, so there is an indirect correlation.
Re 2,3 - no need to complicate this and conflate with rewards. This is just for scalability.
 Re 4 - blobber can change their price today.
 Re 5 - miners are already paid - no need to complicate further

**Comment by illuyankas** [comment]
Stake here is an open stake. Not related to Min Stake. Ie stake can be arbitrarily greater than Min Stake if the blobber desires to stake more. 

In doing so, we promote further staking on blobbers. However this needs to be balanced out; hence the write price component. 

Re 1 - Stake is a not a function of write price anymore. Stake is unbounded; the minimum stake remains as `capacity X write price` 

Re 2,3 - it's indeed about scalability but also about security. We need to a way to double check that the miner is not overpaying a blobber, especially if the blobber is his! - the random shuffling of miners across partitions was a suggestion. I'm sure you may have a different implementation / check. 

Re 4 - Blobbers should only be allowed to decrease his write price after being assigned to an allocation not otherwise, i.e shouldn't be allowed to increase price. The same goes for read price. Moreover, this should happen without affecting the `Min Lock`. Idea here is to avoid stale allocations as price of token increases. We have already discussed this. 

Re 5 - Fine.

**Comment by Sriep** [comment]
We should try to make the formulae used to calculate block rewards as flexible as possible so that we can plugin and try out different algorithms.

**Comment by illuyankas** [comment]
Yes @Sriep agreed. 

Algorithm right now is `Challenges x Stake` 
(`Max Stake = unbounded, Min Stake = write price x capacity`)

Changing this to `Challenges x Stake x Scaling Factor` allows for flexibility to change the algorithm down the road if need be. So we get two birds with one stone.  

The suggestion is to initially set this scaling factor equal to Blobber's `Write Price`

**Comment by guruhubb** [comment]
Re 4 blobbers are allowed to change prices, and then it is up to the user to accept it when they upgrade allocation. I think there is a flag (cc @Sriep for clarification).  We cannot put restrictions because the token value can fluctuate.

Re 2,3 how would a miner overpay a blobber when they use VRF

Re 1 a static scale factor is different from a dynamic write price.  In any case, if someone puts in a lot of stake, then they also take on a lot of risk if there are very few challenges.   Write price adds more complexity to the analysis and indeterministic to its effect.

**Comment by Sriep** [comment]
https://github.com/0chain/0chain/pull/605, https://github.com/0chain/zboxcli/pull/120 This added the ability to update the allocation's blobbers terms as part of an update.

**Comment by guruhubb** [comment]
@Sriep can you check if we can do item 1 as @illuyankas suggested.

> 1- Suggest that we do a product of Challenges X Stake X Write Price. Total is updated on every write price update and/or every stake update. This saves us from doing a min write price implementation and protects against blobber centralization.

**Comment by illuyankas** [comment]
@guruhubb I think all is squared off right now. Summary :

Re 1 - insert write price as a factor per above. Subject to implementation.

Re 2,3,4 - all good.

*Note we need to decrease the block rewards every `30mil` blocks (~1 year) by 10% year on year. This goes for all block rewards.

**Comment by Sriep** [comment]
So, to confirm, currently, the block reward calculation is
`Number of successful challenges in last period x blobber's total stake less unstaking tokens x blubber's write price`

`unstaking tokens` are tokens that the user has requested an `unlock` for but could not be unlocked immediately due to commitment to open allocations. We are assuming unstaking are already unlockd because allocations expire silently, and it would require significant extra calculations to factor them in.

**Comment by Sriep** [comment]
To be replaced by block reward lottery https://github.com/0chain/0chain/issues/753
