### ISSUE TITLE
Redis connections number is high on high TPS

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#670]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/54137706/141416083-e77648ad-e18a-46f1-bcd3-f91080ed652f.png">

**Comment by ma2b0043** [comment]
@peterlimg when can we expect to close this issue?

**Comment by dabasov** [comment]
@peterlimg this should be fixed after I tx_pool is cleaned on block finalization and finalized transactions are deleted, we can mark it as duplicated I think

**Comment by peterlimg** [comment]
I'll have a test to check if this still exist.

**Comment by peterlimg** [comment]
This issue seems is mainly caused by the transaction generators, so clean tx_pool on block finalization may not able to fix the problem.

**Comment by peterlimg** [comment]
Closed since this is mainly caused by txn generator code, which is used for testing only.
