### ISSUE TITLE
Possible extension of not notarized block

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#677]
Miner should validate that incoming Proposal extends notarized block. It is one of protocol’s invariants, the only place where miner uses `b.GetPrevBlockVerificationTickets()` is here
```go
func (mc *Chain) updatePriorBlock(ctx context.Context, r round.RoundI, b *block.Block) {
	pb := b.PrevBlock
	mc.MergeVerificationTickets(pb, b.GetPrevBlockVerificationTickets())
	pr := mc.GetMinerRound(pb.Round)
	if pr != nil {
		mc.AddNotarizedBlock(ctx, pr, pb)
	} else {
		logging.Logger.Error("verify round - previous round not present",
			zap.Int64("round", r.GetRoundNumber()),
			zap.String("block", b.Hash),
			zap.String("prev_block", b.PrevHash))
	}
	if pb.VerificationTicketsSize() > b.PrevBlockVerificationTicketsSize() {
		b.SetPrevBlockVerificationTickets(pb.GetVerificationTickets())
	}
}
```
as you can see, when `mc.AddNotarizedBlock(ctx, pr, pb)`  returns false nothing happens.
If it is not checked, it can be used by malicious miner to include not notarized block in the chain (don’t know is it possible also to apply this blocks state) and finalize it later due to finalization of it’s sibling

**Comment by peterlimg** [comment]
This is kind of duplicate function of `updatePreviousBlockNotarization()` that is introduced in `tps-optimze` branch, I'll check and reduce the duplicate works.

**Comment by dabasov** [comment]
resolved
