### ISSUE TITLE
Blobber events database table plus endpoint.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#680]
We need to add a new table to the event database. This is to hold a blobber table. 
0chain to emit events each time blobber information changes. The event database can then respond by updating the blobber table.
A new endpoint for querying the blobber table. The initial use of this will be to select a suitable set of blobbers for an allocation request.

Waiting on https://github.com/0chain/0chain/pull/679

**Comment by moldis** [comment]
@Sriep is this duplicated to https://github.com/0chain/0chain/issues/681 ? Can assign to @kushthedude to work on, or you can handle it?

**Comment by Sriep** [comment]
I think we should write a new REST endpoint to select blobbers for a new allocation request.
