### ISSUE TITLE
Update API /getblobbers to get blobbers from events DB

### ISSUE THREAD

**Issue by moldis** [0chain/0chain#681]
Update API /getblobbers to get blobbers from events DB

**Comment by Sriep** [comment]
I think we should write a new REST endpoint to select blobbers for a new allocation request.

So `\select_blobbers`. 
1. Input the relevant information from the new allocation request.
2. Do a select on the eventDB [blobbers](https://github.com/0chain/0chain/blob/blobber-events/code/go/0chain.net/smartcontract/dbs/event/blobber.go#L12) table
3. Return list of selected blobber ids.
4. Add event emits in storagesc smartcontracts to support new fields in eventDB.blobbers table as needed.

My preference would be to depreciate `getblobbers`, do we really want to be returning information on hundreds of thousands of blobbers here?

**Comment by Sriep** [comment]
The selection process for blobbers can be inspired by [selectBlobbers](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L428).
The new REST-API endpoint can run a `gorm` select request with filters as suggested

This suggests:
- Terms.MaxOfferDuration 
- ReadPriceRange
- WritePriceRange
- Capacity-Used 
- Terms.ChallengeCompletionTime
- Diversity, to be decided but latitude and longitude are in the Blobber table.
- LastHealthCheck
- [Staked Capacity](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L266)

Staked capacity takes into blobber's stakes not committed to allocations. This is not currently stored n the stoaragesc.StorageNode or event.Blobber. So we need to add fields and update them as appropriate. Then emit events to inform the eventDB of the change.

For example you could add the following to the end of [stakePoolLock and stakePoolUnlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L921), if you decided to create a new `offer-free-stake` field:
```go
	updates, err := json.Marshal(dbs.DbUpdates{
		Id: spr.BlobberID,
		Updates: map[string]interface{}{
			"offer-free-stake": info.stake - info.offers,
		},
	})
	if err != nil {
		return "", common.NewErrorf("stake_pool_lock_failed",
			"cannot marshal stake update: %v", err)
	}
	balances.EmitEvent(event.TypeStats, event.TagUpdateBlobber, spr.BlobberID, string(updates))
```
emitUpdateBlobber is already called in update and new allocation request. Just need to update the blobber object before that.

**Comment by Sriep** [comment]
We need to decide what order to return the results in when doing the `select` on the `event.blobber` database table. We can then ask for the first `N` results where `N` is the number of blobbers the allocation wants.

**Comment by moldis** [comment]
Moving back this ticket to @moldis

**Comment by moldis** [comment]
Created the `getAllocBlobbers` endpoint (still under WIP), using this filters criterion:

Terms.MaxOfferDuration
ReadPriceRange
WritePriceRange
Capacity-Used
Terms.ChallengeCompletionTime
LastHealthCheck

Going to add diversify logic and sorting. Thinking to sort on free space available and last healthcheck 

cc @Sriep @guruhubb

**Comment by ma2b0043** [comment]
@moldis @Sriep when can we expect to close this issue?

**Comment by dabasov** [comment]
fixed
