### ISSUE TITLE
R&D: Conductor: Leader extends not notarized prev_block

### ISSUE THREAD

**Issue by moldis** [0chain/0chain#692]
Implement a test: Leader extends not notarized prev_block.
```
(T0) Leader_0: send Proposal0_0, extends not notarized prev_block
(T0) Leader_1: send Proposal1_0
(T0 + δ) Replica_0: reject Proposal0_, verify Proposal1_0
```

**Comment by moldis** [comment]
Estimation < 1 Dec 2021

**Comment by MurashovVen** [comment]
**List of subtasks**
- [x] Implement the mechanism for mocking the block to extend.
- [x] Implement the mechanism for checking the block's verification status.
- [x] Implement the interface for making checks by using the Conductor's directives.
