### ISSUE TITLE
Migrate 0chain/0search to EventDb

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#733]
We need to migrate the 0search/0block endpoints to the EventDb. Particularly the ones needed by Explorer. 
1. block information indexed by block number
2. transaction information indexed by transaction hash
3. allocation indexed by allocation id
4. user information indexed by user id
5. File details indexed by lookup hash or file name

We now need a list of fields for each of these new tables. The ones 0Seach  currently provides and the ones that Explorer actually needs.

How easy 1-5 are will depend on how readily available these fields are - particularly (5) which depends on the information the blobber sends.

Related issue https://github.com/0chain/block-explorer/issues/351#issuecomment-984083417

**Comment by shaktals** [comment]
As per [slack convo](https://0chain.slack.com/archives/C026YA5EYH3/p1638345537270100), the main issue we have to fix is the number of transactions being returned when fetching a block.

As blocks can have up to 1000 transactions, we need some sort of pagination.
But then, on explorer block details page we display transactions by type.
So, ideally the backend should respond with 10~20 records of each type, so the user can immediately see records when clicking on each tab type. And we'd fetch more as the use navigates.

Another solution would be fetching records for each type separately, which could be done for all types on page mount, or individually when the use clicks on a type tab.

![Selection_254](https://user-images.githubusercontent.com/24679343/144436268-47f869a0-bf47-406f-806e-8bfa69f1219b.png)
.

**Comment by Sriep** [comment]
There are two issues.
1. What data to store in the EventDb.
2. What API to provide to access the data.

As long as we get (1) right, we can modify (2) as needed.

Pagination and refresh issues might be left until we have enough implemented for testing/load testing. Can the explorer organise its own pagination, by indicating the records it wants to be returned?

**Comment by krishnemd** [comment]
@Sriep out of 1 to 5 only two data models are used in all those proposed models at the moment. 

1. [Block](https://github.com/0chain/0block/blob/staging/code/go/0block/zblockcore/models/block.go#L0-L1  )
2. [Transaction](https://github.com/0chain/0block/blob/staging/code/go/0block/zblockcore/models/transaction.go#L0-L1 )

Allocation is transaction.

UserDetails is array of seven sorts of transactions.

File Details is array of storage transactions

@shaktals @Sriep  for the types of transaction and what API to hit will post here tomorrow, till then let's validate the data models to use in the DB.

**Comment by shaktals** [comment]
> Pagination and refresh issues might be left until we have enough implemented for testing/load testing. Can the explorer organize its own pagination, by indicating the records it wants to be returned?

When fetching the transactions for a specific block, we don't know beforehand what those transactions are.
So, we can specify exactly what transaction records we want.

I thought several minutes about the best way to do this.

If we can get low latency on the API, the simplest way to solve it is to have a `type` filter and pagination.
When the page first loads, we fetch, let's say, the first 20~50 `wallet` type transactions, paginated.
If the user then clicks on `Stake` or `Rewards` we then fetch records for those types, paginated.

What do you guys think?

**Comment by shaktals** [comment]
> What data to store in the EventDb

@chauchausoup as for this issue, can you confirm what block/transaction props we are actually reading/using on explorer?

I'm not sure that is the only data we'll ever need. But at least it is what we know it's needed now.

**Comment by krishnemd** [comment]
> > What data to store in the EventDb
> 
> @chauchausoup as for this issue, can you confirm what block/transaction props we are actually reading/using on explorer?
> 
> I'm not sure that is the only data we'll ever need. But at least it is what we know it's needed now.

At the moment we are relying on sharders to get the /transaction endpoint data ( the main page that show transaction in details). 
For example if we get UserDetails data which also gives us full fledge transactions of the user but still we are calling sharders. Explorer is using these limited fields ( tentatively) out of the Transaction data.

`
hash
creation_at
client_id
to_client_id
transaction_value
transaction_output
transaction_data
`
But it's ok to go with present implementation of data model to be kept in events DB as we might need them in future enhancement. While forming the API endpoints we might limit the data fields.

**Comment by krishnemd** [comment]
> > Pagination and refresh issues might be left until we have enough implemented for testing/load testing. Can the explorer organize its own pagination, by indicating the records it wants to be returned?
> 
> When fetching the transactions for a specific block, we don't know beforehand what those transactions are. So, we can specify exactly what transaction records we want.
> 
> I thought several minutes about the best way to do this.
> 
> If we can get low latency on the API, the simplest way to solve it is to have a `type` filter and pagination. When the page first loads, we fetch, let's say, the first 20~50 `wallet` type transactions, paginated. If the user then clicks on `Stake` or `Rewards` we then fetch records for those types, paginated.
> 
> What do you guys think?

Yes forming specific API is the viable solution as suggested by @Sriep.

**Comment by Sriep** [comment]
@shaktals @chauchausoup could you check that the below makes sense?

> out of 1 to 5 only two data models are used in all those proposed models at the moment.
> Block
> Transaction

### Block
A Block table looks straightforward, it is just the [Block](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L139) object. We just need to identify the best place for the block to marshal and emit itself. 

We could emit the block at the same time as the [smartcontract events are sent to the event database](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L920).  We need to confirm that the block does not change further, we might need to emit the block later, maybe at the same time the block hash is calculated in [hashAndSignGeneratedBlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/miner/protocol_block_main.go#L33).

### Transaction

The transaction table is confused by the presence of allocation data. It seems to be the [Transaction object](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/transaction/entity.go#L43) with some of out of place fields tacked on, related to allocations and files.

The array of transactions is available at the same time as the [smartcontract events are sent to the event database](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L920).  It should be ok for the block to emit the transactions at this point.

### Allocation

The anomaly here is the allocation information in the transaction table. It seems more sensible to have a separate allocation table. We will need that eventually for the [./zbox get](https://github.com/0chain/zboxcli#get) CLI. This could be populated from events emitted in relevant smartcontracts.

I can't see any reason to couple allocations and transactions so tightly as most transactions don't have an allocation and we probably should avoid sparse SQL databases. The allocation id and the transaction id are the same so joining the tables should be easy.

### UserID

It looks like this is the Transaction table filtered by user id. So it looks like we just need an APi endpoint to run the appropriate SQL query.

### Files

I am not clear how this is used, but like allocations, this looks like some sparse information added to the Transaction table. I would suggest creating a separate table for this information populated by corresponding smart contracts; probably `read_redeem` and `commit_connection`. 

I can't find `LookUpHash` in 0chian. @shaktals @chauchausoup what information does the search by `LookUpHash` and `FileName`  return and do we know what `LookUpHash` and `FileName` are or how are the fields returned here originally populated?

**Comment by shaktals** [comment]
All seems correct. As for `Files`, my knowledge is still limited, but from what I understand, when you upload a file to blobbers, you can commit or not the transaction to the sharders.

So maybe this refers to `Files transactions`?

I guess we don't need any sparse information from blobbers to be stored on EventDB.
My intuition is that we can treat just as a txn type.

I'll let Krishna answer your final questions.

**Comment by krishnemd** [comment]
For Filesname we are calling the endpoint  /recordertransactions/search?metadata=logic.jpeg 
which  gives transactions array indexed by name field as seen [here](https://github.com/0chain/0search/blob/d9473d6379d1890f65772864e46a11c42252436e/src/app/services/transaction.service.ts#L62 ) 
One thing I noticed is that all have same content_hash value.

LookupHash is also known as Pathhash in most of the backend code.
On evaluation what I found is that a given file on same directory has a same Lookuphash on performing file operations, once a dir is changed its lookuphash changes too.

/recordertransactions/search?metadata={lookup_hash} endpoint is used in 0search for it at the moment which gives transactions array indexed by lookup_hash.

LookupHash is related to /blobber repo rather than 0chain as it is predominantly used in [here](https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/reference/ref.go#L137) . 

For API endpoints I found [this](https://github.com/0chain/0search/blob/staging/src/schema/v1/backend/path.ts) 0search implementation helpful.

Below is the ss of returned content for /search?metadata={file_name} search endpoints.
 
<img width="1638" alt="Screen Shot 2021-12-04 at 10 54 53" src="https://user-images.githubusercontent.com/34975245/144698168-8b45c005-46aa-4d02-91b9-2bbf1f02b911.png">

**Comment by Sriep** [comment]
# Block

I think I  have worked where 17 out of the 19 fields in the [block table](https://github.com/0chain/0block/blob/staging/code/go/0block/zblockcore/models/block.go#L22) can come from. 

Can't find `updateAt` row might not be directly to do with the block, just when the database got updated? 

| 0block fields         | 0block type | 0chain Block.?                                     | type    |
|-----------------------|-------------|----------------------------------------------------|---------|
| Hash                  | string      | HashIDField.Hash                                   | Key     |
| Version               | string      | UnverifiedBlockBody.VersionField.Version           | string  |
| CreationDate          | int64       | UnverifiedBlockBody.CreationDateField.CreationDate | int64   |
| Round                 | int64       | UnverifiedBlockBody.Round                          | int64   |
| MinerId               | string      | UnverifiedBlockBody.MinerId                        | Key     |
| RoundRandomSeed       | int64       | UnverifiedBlockBody.RoundRandomSeed                | int64   |
| MerkleTreeRoot        | string      |  ClientState.GetRoot()                        | Key     |
| StateHash             | string      |  UnverifiedBlockBody.ClientStateHash          | Key     |
| ReceiptMerkleTreeRoot | string      |       block.GetReceiptsMerkleTree().GetRoot()                                             |         |
| NumTxns               | int64       |  len(UnverifiedBlockBody.Txn)                 | int     |
| MagicBlockHash        | string      | MagicBlock.HashIDField.Hash                        | Key     |
| PrevHash              | string      | UnverifiedBlockBody.PrevHash                       | string  |
| Signature             | string      | Signature                                          | string  |
| ChainId               | string      | ChainID                                            | Key     |
| ChainWeight           | string      | ChainWeight                                        | float64 |
| RunningTxnCount       | string      | RunningTxnCount                                    | int64   |
| RoundTimeoutCount     | int         | UnverifiedBlockBody.RoundTimeoutCount              | int     |
| CreatedAt             | time.Time   | UnverifiedBlockBody.CreationDateField.CreationDate | int64   |

Key is []byte.
[Block](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L139)
[UnverifiedBlockBody](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L93)
[HashIDField](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/core/datastore/key.go#L130)
[MagicBlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/magic_block_entity.go#L16)
[ClientState.GetRoot() ](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/core/util/markle_patricia_trie_interface.go#L32)

**Comment by Sriep** [comment]
# Transaction 

13 of the 21 can be read from the 0chain [Transaction](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/transaction/entity.go#L43) object.

The `BlockHash` row is presumable from the parent block and should be easy to provide.
The `UpdateAt` and `ComfirmationFetched` I suspect have to do with the running of the 0Block dB and nothing to do with the Transaction? Does explorer need this?
The `LookUpHash`, `Name`, `AllocationId` and `ContentHash` look like they belong elsewhere, likely two separate tables that can be joined. How does Explorer use these fields?

| 0Block Transaction  | type      | 0chain Transaction.  | type   |
|---------------------|-----------|----------------------|--------|
| Hash                | string    | HashIDField.Hash     | Key    |
| BlockHash           | string    | parent object        |        |
| Version             | string    | VersionField,Version | string |
| ClientId            | string    | ClientID             | Key    |
| ToClientId          | string    | ToClientID           | Key    |
| TransactionData     | string    | TransactionData      | string |
| Value               | int64     | Value                | int64  |
| Signature           | string    | Signature            | string |
| CreationDate        | int64     | CreationDate         | int64  |
| Fee                 | int64     | Fee                  | int64  |
| TransactionType     | int       | TransactionType      | int    |
| TransactionOutput   | string    | TransactionOutput    | string |
| OutputHash          | string    | OutputHash           | string |
| Status              | string    | Status               | string |
| CreatedAt           | time.Time | CreationDate         | int64  |

**Comment by krishnemd** [comment]
> # Block

I am too not sure but on looking the blobber code I can see that in this file [protocol.go](https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/challenge/protocol.go) most of the UpdatedAt represent the time.Now().UTC() time.
Might be the time instance of the procedure under operation (db updates in this case)

Interestingly on explorer code too it is time.now() time as [this](https://github.com/0chain/block-explorer/blob/staging/src/lib/dbmanager.js#L42-L43) reference.

For ReceiptMerkelTreeRoot I found [this](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L495) implementation. 

 At the moment explorer is only using these values for **recorderblock?hash={block_hash}**

```
hash
round
created_at
prev_hash
miner_id
signature
chain_id
version
transactions
```

since most of the values are only for rendering purpose more value we get from backend more richer the user response might be on explorer.

**Comment by krishnemd** [comment]
> # Transaction

Explorer uses `updated_at` just for rendering purpose.

`block_hash` is used to fetch detail of the block and in search.
`confirmation_fetched` is not used by explorer
`lookup_hash, name, content_hash, allocation_id` are all used to query while searching  and are also part of 0search endpoints

**Comment by guruhubb** [comment]
The Files part is based on the client committing the transaction to the blockchain. But I think going forward clients don't need to do this since blobbers submit write and read markers for all data activities and these can be sorted out.  Perhaps add a field for `filename`, `lookuphash`, `contenthash` of the file along with the read/write markers.

The only transaction that the client will "commit" is the share authtoken which has the lookuphash of the file for anyone to download the file.  @Sriep

**Comment by guruhubb** [comment]
Also, you will need to include APIs for additional data as was requested by Mo a while back, although some of the requests are redundant and based on the same dataset but filtered differently -

1- Ability to see read/write price of an allocation in $ as time
2- How much data in MB has been written/from to allocation.
3- How much data is stored in allocation at any given point in time. 
4- How much tokens in the read/write pools of an allocation. 
5- Total cost paid to write /read from an allocation. 
6- Geographic distribution of blobbers assigned to an allocation. 
7- Last time an allocation was written/read from.
8- Who can read/write to the allocation. 
9- CRUD operations per allocation
10- CRUD operations per file 

Network
1- How much data is stored on the network.
2- How many allocations exist 7D, 30D, 90D
3- How much data is written / read from allocations 7D, 30D, 90D (graph)
4- Number of blobbers assigned to allocations, 7D, 30D, 90D (graph)
5- Number of blobbers on the network (graph)
6- Number of miners on the network vs active. (Kilimanjaro)
7- Number of sharders on the network vs active. (Kilimanjaro)
8- Geo distribution of miners, sharders, blobbers (map)
9- total staked by miners, sharders, blobbers (including delegation) (graph)
10- miner stats including delegation (same for sharders) (graph)
11- blobber stats including delegation (showing challenges passed, failed, block rewards earned)

**Comment by Sriep** [comment]
# Allocation

For migration from 0Search/OBox only the `Tx` and maybe `Id` fields as foreign keys into the transaction table above.

The other fields will be needed for the `/allocation` endpoint for `Blobber` and `zwallet` enquiries.

We will want to add Stats to this. Plus a new AllocationBlobber Terms table.

| eventDB                 | type   | 0chain allocation       | type          | Notes                                           |
|-------------------------|--------|-------------------------|---------------|-------------------------------------------------|
| Id                      | string | Id                      | string        | unique key                                      |
| Tx                      | string | Tx                      | string        | unique                                          |
| Size                    | int64  | Size                    | int64         |                                                 |
| UsedSize                | int64  | UsedSize                | int64         | to be added to 0chain                           |
| Expiration              | int64  | Expiration              | int64         |                                                 |
| Blobbers                | []     | Blobbers                | []StorageNode | join with blobber table                         |
| Owner                   | string | Owner                   | string        |                                                 |
| OwnerPublicKey          | string | OwnerPublicKey          | string        |                                                 |
| IsImmutable             | bool   | IsImmutable             | bool          |                                                 |
| ChallengeCompletionTime | int64  | ChallengeCompletionTime | int64         |                                                 |
| Cancelled               | bool   | Cancelled               | bool          | only one of cancelled and finalised can be true |
| Finalized               | bool   | Finalized               | bool          |                                                 |
| TimeUnit                | int64  | TimeUnit                | int64         |                                                 |
| Curators                | []     | Curators                | []string      | join with curator table                         |
| IsNft                   | bool   | IsNft                   | bool          | 0chain PR620                                    |
| BlobberTerms                   | []Terms   | BlobberDetails                   | []BlobberAllocation          | Terms per blobber might be different from blobbers current terms                                    |
| ReadPriceMin            | int64  | ReadPriceMin            | int64         |                                                 |
| ReadPriceMax            | int64  | ReadPriceMax            | int64         |                                                 |
| WritePriceMin           | int64  | WritePriceMin           | int64         |                                                 |
| WritePriceMax           | int64  | WritePriceMax           | int64         |                                                 |

**Comment by Sriep** [comment]
# File information

Populate these fields from readMarkers and writeMarkers emitted during `read_redeem` and `commitBlobberConnection` smart contracts.

This information is available on the blobber, but does not all seem to be sent to 0chain. We might need to increase the information the blobber sends to 0chain in `WrtieMarkers`, or provide a direct way for blobbers to emit events.

The TxHash is a foreign key into the transaction table above.

| 0search     | type   | 0chain commitBlobberConnection | string |                          |
|-------------|--------|--------------------------------|--------|--------------------------|
| TxHash      | string | transcation.Hash               | string | From transaction obeject |
| LookUpHash  | string | WriteMarker.AllocationRoot     | string |                          |
| Name        | string |                                |        |                          |
| ContentHash | string |                                |        |                          |

Information sent by blobber to 0chain smart contract. I suggest using these to populate two tables. Then use SQL queries to provide the information Explorer needs.

```go
type ReadMarker struct {
	ClientID        string           `gorm:"column:client_id;primary_key" json:"client_id"`
	ClientPublicKey string           `gorm:"column:client_public_key" json:"client_public_key"`
	BlobberID       string           `gorm:"column:blobber_id" json:"blobber_id"`
	AllocationID    string           `gorm:"column:allocation_id" json:"allocation_id"`
	OwnerID         string           `gorm:"column:owner_id" json:"owner_id"`
	Timestamp       common.Timestamp `gorm:"column:timestamp" json:"timestamp"`
	ReadCounter     int64            `gorm:"column:counter" json:"counter"`
	Signature       string           `gorm:"column:signature" json:"signature"`
	Suspend         int64            `gorm:"column:suspend" json:"suspend"`
	PayerID         string           `gorm:"column:payer_id" json:"payer_id"`
	AuthTicket      datatypes.JSON   `gorm:"column:auth_ticket" json:"auth_ticket"`
}
```

```go
type WriteMarker struct {
	AllocationRoot         string           `json:"allocation_root"`
	PreviousAllocationRoot string           `json:"prev_allocation_root"`
	AllocationID           string           `json:"allocation_id"`
	Size                   int64            `json:"size"`
	BlobberID              string           `json:"blobber_id"`
	Timestamp              common.Timestamp `json:"timestamp"`
	ClientID               string           `json:"client_id"`
	Signature              string           `json:"signature"`
}
```

**Comment by Sriep** [comment]
Objects are event database tables. Assumes the Write and Read markers are updated to include the File information that Explorer needs.

![image](https://user-images.githubusercontent.com/6240686/145190784-a86ffdfb-23ab-4cc2-94d2-18c585336961.png)

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
Split into multiple issues that are mostly done. Closing.
