### ISSUE TITLE
Migrate BoltDB to Redis or Cassandra

### ISSUE THREAD

**Issue by moldis** [0chain/0chain#739]
Preferably Redis with master/slave or Redis cluster configuration. The main goal is to make it easily scalable.
Meaning of this ticket - to understand pros/cons between Redis or Cassandra and the amount of time it will take to migrate from BoltDB

**Comment by peterlimg** [comment]
The boltDB is not being used actually, or do we have any plan to use it?

**Comment by ma2b0043** [comment]
@moldis when can we expect to close this issue?

**Comment by peterlimg** [comment]
Since redis is mainly used as in-memory cache on nodes, and data may not be persistent between restarts. Consider to use rocksdb, we are using it for storing blockchain data, so we can use it for infinite disk extension easily.
