### ISSUE TITLE
node not found

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#74]
Unexpeted `node not found` errors apperaing

Peter reported investigtion in this [slack thread](https://0chain.slack.com/archives/G01FYNN6DK4/p1613282114002900)
`
The 'node not found' issue looks like benign, it would not stuck the BC at least. Even though, it would be great if we can resolve it. All of the errors that contain the 'node not found' are actually the same problem, they are all caused by failing to get miner or sharder id from MPT database.` 

`The 'node not found' error would only occur when MPT can find the key of the path, while it can not find the node by the key from its database. There are some possible ways that can result in this state. But after a lot of tests, all of them are not the true reason. The MPT is implemented pretty well, if you do CURD actions against a MPT instance, it works very good (even with concurrent actions), and we won't see this error. The problem is not caused by the MPT itself, it is the way it is being used. 
I added a db versions tracker in MPT, each time a new MPT is created, a new level node db will be created, and a new db version will be assigned to it. The new db version will be appended to the history db versions from previous db as well. In this way, we can understand in which db version, the node was deleted. Also, when we get the 'node not found' error, we can check against the db versions list. Let's have an example to explain how it works.`

`Suppose we are now with a block on round 1000, and we are computing its state, a temporary MPT state will be created base on the previous block's state. When creating the temporary MPT, a new level node db will be created, let's say the new db version is 1000, it will be recored to the db version tracker. If the previous block's db version tracker is [..., 998, 999], then the current one would be [..., 998, 999, 1000]. After the transactions are executed against the temp MPT, it will be merged into the block's MPT, and the block's MPT db versions would be [...,998, 999, 1000]. If all blocks are generated and linked to its previous block correctly, it should have all the db versions in the versions list. And if any db version is missing, and we are trying to get nodes that are added in that db version, then we will see the 'node not found' error. But how could the block has the node key, the answer is the state was acquired from network.`

`After adding the db versions tracker, I find that the 'node not found' error occurs when the block starts a MPT with a new thread, which means it can not find the history db versions, it has to start with a MPT with an empty DB from a new thread. This may not be a problem for the first several blocks after the new MPT, but once a block's transactions contains functions that tries to get node that are deleted in the missing db versions, we will see the 'node not found' error. I tried to get the missing db versions by executing the states fetched from network, it would fetch blocks back till the finalized block from network. I thought the finalized block should contains all the db versions, but the test result told me that even the finalized block may still not computed. So the problem is still there, and perhaps can resolve it by filling the missing db gaps.
`

**Comment by guruhubb** [comment]
This bug is likely related to #79

**Comment by peterlimg** [comment]
Found a problem about the `Missing State Sync process`, though it will sync state from network, but only the round about 100 (configurable) rounds prior to the current round will be synced. If the state prune process run after the current round encounters the ‘node not found’ issue, then the current round should be able to find the missing mpt nodes by traversing back the mpt dbs.

Apparently, the current round db does not find the missing nodes. The reason might be related to another blocks deleting process, which will be called when finalizing a round. Blocks that are 50 rounds below the finalized block will be deleted (there are also other conditions, but does not matter here). So even though the prune state process could help to sync state, but the state may not be reachable at all.

**Comment by guruhubb** [comment]
@peterlimg isn't this issue sorted out already? If so, please close it with reference to the commit.

**Comment by peterlimg** [comment]
Fixed in b081b71a.
