### ISSUE TITLE
Modify challenge creation algorithm

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#741]
### Challenges

Challenges are generated by the [generateChallenges](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/challenge.go#L524) method. This method is called when the blobber calls either the `read_redeem` or `commit_connetion` endpoints. 
`generateChallenges` creates up to `sc.yaml.storagesc.max_challenges_per_generation` challenges, which typically defaults to 100.

The existing method for creating a challenge selects an allocation at random, then randomly orders the blobbers and select the first with a file/allocation root. Unfortunately, this method could be subject to a [sybil attack](https://en.wikipedia.org/wiki/Sybil_attack), so we intend to redesign this algorithm.

### Select challenge by blobber algorithm

1. Blobbers are partitioned into even-sized partitions.
2. Select a partition at random.
3. Weight the blobbers in the randomly selected partition.
4. Randomly select a blobber using a weighted probability distribution as defined by (3)
5. Select a random allocation supported by the blobber that has an allocation root - file.
6. Create a challenge out of the (blobber, allocation, allocation root)
7. Save challenge information to MPT and emit challenge event.

Repeat 1-7 a number of times equal to  `max_challenges_per_generation`

(3) amount of data stored on blobber

~We will need to modify the blobber object to hold the active used capacity of the blobber and a rolling total of reads during the last P rounds.~
[commitBlobberRead](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L344) increment details of each read against the blobber.
[commitBlobberConnection](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L556) adjuct total data stored, either up or down, agasit the blobber.
Total data stored is an `int64` in StorageNode. 
The number of blobber reads can be an array of ints of size 2*period. Each read is only active for `period length` rounds after the read, so increment the matching `period length` array elements after each read.

**Comment by Sriep** [comment]
As well as emitting to the event database so the blobber can pick it up, challenge data needs to be saved in 0chain for `verifyChalelnge` and ` cancelAllocation` and `finalizeAllocation`

`cancelAllocation` needs to know how many open challenges there are and what proportion of them have expired. In order to calculate a pass rate.

`verifyChallenge`  When checking a completed challenge needs to know the ChallengeId, BlobberId, AllocaionId, Expiry date and the number of validators.

**Comment by Sriep** [comment]
We need to take account of https://github.com/0chain/0chain/issues/646

**Comment by Sriep** [comment]
# Introduction

Blobbers and their delegates receive rewards,  all rewards are done on the MPT and not distributed to delegate wallets unless they do a payMe transaction, see rewards below. However,
token rewards for writes are instead transferred to a challenge pool. Tokens in
this pool are not made immediately available to the blobber or its delegates,
but they may receive those rewards after passing a challenge proving that they
are storing the data that they claim.

This goes over the process from the perspective of 0chain smart contracts. In particular we look at upcoming changes to the following smart contract endpoints.
* read_redeem
* commit_connection
* blobber_block_rewardRewardss
* generate_challenges
* challenge_response
* pay_me (new)

Changes are indicated in quotes and blue arrows in sequence diagrams.

# Upload

The challenge process starts with a file upload. The blobber stores the data then sends a transaction to 0chain using the `commit_connection` endpoint. This sends a WriteMarker object with information on the upload for 0chain to process.

`commit_connection` moves funds from the allocation's write pools to the allocation's challenge pool. These are funds to be transferred to the blobber delegates once the blobber has passed a challenge.


> The blobber has a new field for the total data currently stored. This needs to be incremented by the size of the upload.

> The write marker needs to be emitted so that a new row can be added to the Event database Write Marker table.

> If this takes the data stored on the allocation over 1MB the allocation should be added to the blobber's allocation partition, so that the allocation can take part in challenge generation.

![image](https://user-images.githubusercontent.com/6240686/148646292-1c2f8bdf-8b6d-4463-8175-77532630544c.png)

# Delete

A delete works much the same way as an upload, after deleting the data the blobber schedules a `commit_conection` transaction. The difference is that in the `commit_commection`'s WriteMarker the size field is negative the size of the delete.

`commit_connection` branches depending on the sign of the size. If negative it moves tokens back from the challenge pool to the owner's allocation pool. 

> The blobber has a new field for the total data currently stored.  This needs to be decremented by the size of the delete.

> If an open challenge exists for the deleted file, the challenge needs to be removed.

> The write marker needs to be emitted so that a new row can be added to the Event database Write Marker table.

> If this delete takes the data stored with the allocation below 1MB the allocation should be removed from the list of blobber's allocations used for challenge selection.

![image](https://user-images.githubusercontent.com/6240686/148646260-5d0314a7-0d7d-4109-af1a-4ea0e813fe33.png)

# Download

For a download, the blobber sends a `read_redeem` transaction containing a ReadMarker. This gives the information 0chain needs to move tokens from the read pool of the user funding the download, to the blobber delegates. It is possable the blobbers read price will be zero negating the need to move tokens.

> The blobber objects have a number of reads field to be used for block rewards. This needs to be incremented.

> Currently the read marker is stored in the MPT. It is intended that this will no longer be needed.

> An event will be emitted to insert the Read Marker into the Event db ReadMarker table.

> The method of transferring rewards to delegates is to be changed. See the rewards section below.

![image](https://user-images.githubusercontent.com/6240686/148775382-ebb7af45-a494-4f10-9198-14a110f2962a.png)

# Challenge creation

> Challenge creation is to be completely reworked. The existing method of selecting allocation first is open to attack, so we are changing to selecting blobber first.

As there are potentially too many blobbers to keep in a single list we are partitioning the blobbers. We can then do two random selections, one to select a portion than a blobber in a partition. We want to favour challenges for blobbers who are active, hence we will weigh blobbers by
```
amount of data stored on blobber
```
before random selection. The period is a fixed number of blocked defined originally from `sc.yaml`.

Once we have a blobber we need to randomly select one of its allocations. Again there are potentially too many blobber allocations to keep in one list, so we will use a partition of blobber's allocations. We repeat the above double random selection to find a random allocation.

After selection of allocation and blobber, we confirm that
1. The allocation has an allocation root.
2. The size of the allocation is over 1MB.

If everything is ok we create a challenge. The challenge is emitted as an event so it can be inserted into the Challenge event database table, to be picked up by the blobber. It also needs to be added to an allocation's list of challenges for challenge resolution. Also, the allocation needs the number of open challenges to increment.

The challenge generation blobber partition will need to be maintained in other smart contracts when blobber parameters are altered.

![image](https://user-images.githubusercontent.com/6240686/148805763-413f44c4-6c52-447f-aa22-918f5e1e1fa1.png)

# Challenge response

A challenge-response comes in the form of a slice of validator tickets. Each validator ticket has a result field, for the challenge to pass over half the number of validators should pass the challenge. 

Once the challenge has been verified as existing and not expired the result is acted upon. If the challenges pass money is moved from the challenge pool to the blobber delegates. If the challenge fails tokens are moved from the challenge pool to the allocation write pool along with the blobber slash amount from the blobbers locked stake. Either way, funds are paid to the validator delegates.

While this process stays the same many details will change.
> * The list of challenge ids will need to be slimmer. We can keep the list with the blobber, but if this proves too big for the MPT we will either need to use partitions with a bloom filter or add allocation id to the validator ticket.
> * Stats on challenge results are needed to calculate pass rate when cancelling an allocation. 
> * Otherwise stats are handled by emitting the challenge-response, which will update the event database tables.
> * The way rewards are handled will change, see below.
> * The blobber needs to maintain a slice of passed challenges for the last period as described in block rewards.

![image](https://user-images.githubusercontent.com/6240686/148683849-daf016c0-23f7-4ac1-a0e8-6dcfec8dd89a.png)

# Block reward lottery

> Block rewards are to be entirely replaced with this block reward lottery.

To reward blobbers, every block there will be a lottery and a select group of blobbers will split the block reward payments between their delegates. Only active blobbers with `read price == 0` will receive rewards, so we will use a similar but different partition to challenge creation consisting of blobbers with free reads.

For each block, we randomly select a partition. We weight each blobber by
```
blobber data size increase in last period * stake * write price * (num_reads in last period + 1)
```
and split the block reward between the blobber and their delegates according to the weighting. These partitions will only have blobbers with `read price = 0` so we do not need to recheck the read price. 

The period_length is a fixed number of blocks defined in `sc.yaml` settings. We break the chain up into periods between squeantal ronds where 
```
round_number Modulo period_length = 0
```
So we should keep summery stats from the last period, and accumulate stats for the current period. When `round_numer modulo period_length = 0` we forget the last period, set the accumulated data for the current period to the last period and start collecting data for the new current period. In the reward formula, we use the information from the last period.

The way rewards are paid is changing as below. The block reward blobber partition will need to be maintained in other smart contracts when blobber parameters are altered.

![image](https://user-images.githubusercontent.com/6240686/148647495-ba7a4331-16c8-4d08-8c30-e849f8ccb987.png)

# Rewards

> Rewards are to be entirely reworked.

We want to allow 0chain modules to have hundreds of stakeholders, however, making payments to all stakeholders in a single smart contract will result in an unscalable number of MPT updates. Even more so if we are paying rewards to delegates in multiple mdules, such as in blobber block rewards. Hence we need to rethink how rewards work.

The plan is to hold the rewards in status until a request to transfer funds is made in the new a `pay_me` smart contract. 

Each module (blobber, sharder, miner, authoriser of validator) will have a map of rewards for each of their delegates. This map gets updated each time a reward is earned, if the reward is in the form of a transfer, the funds are initially transferred to the minter. When a delegate makes a `pay_me` transaction the reward held for that delegate is minted.

This will result in only one MPT update for rewards to any one module's delegates. 

It is still to be decided whether this reward object should be attached to a modules stake pool or stored independently. We can decide this by benchmarking. Do we increase the size of the stake pool object, or increase the number of MPT updates in smart contracts like block rewards?

**Comment by peterlimg** [comment]
> 3. Weight the blobbers in the randomly selected partition.
> 4. Randomly select a blobber using a weighted probability distribution as defined by (3)

Hi @Sriep,  it seems like the weight of blobber is not a must for randomly select the blobbers, unless we will use the weight some where else, we'd better avoid the weight calculation here.

**Comment by Sriep** [comment]
We want the blobbers in the partition to have non zero weight. Otherwise, we have to start worrying about the density of blobbers with non zero weight.

However other than checking zero multipliers, the actual calculation only needs to be done during `generate_challenges`. Depending on implementation convenience we might consider precalculating some values before `generate_challenges`. 

`generate_challenges` is linear in `max_challenges_per_generation` while `verify_cahllenge` is a constant value. So it's good if we can see a way of moving work out of `generate_challenges`.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
