### ISSUE TITLE
Challenge does not fail/pass and stays open in some cases

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/0chain#75]
But something wierd is happening on two.devnet-0chain.net although it could be on all networks, where challenges are neither failed nor passed when the “challenge completion time” elapsed.
1. Take https://prod-node-201.fra.jbod.zeroservices.eu/blobber52/_stats for example
2. I have Challenge completion_time	2m0s
3. I have Open Challenges	12
4. There have more than >2min passed
5. Challenge is neither failed nor passed

**Comment by shravanshetty1** [comment]
https://github.com/0chain/0chain/pull/73

**Comment by shravanshetty1** [comment]
since two.devnet is using branch 'https_changes' - https://github.com/0chain/0chain/pull/76

**Comment by shravanshetty1** [comment]
Current flow:

1. Blobber gets challenge from smart contract
2. Blobber process challenge and validates it through validators
3. Challenge is sent back to smart contract. If the challenge has valid verification tickets .etc. the funds are released.

This issue seems to be caused by multiple other issues:
After reviewing the blobber stats page - https://one.devnet-0chain.net/blobber03/_stats

1. Most of the challenges are not being sent back to the smart contract:
There are 2 go routines workers in the blobber, one of them process challenges while the other sends processed challenge back to the smartcontract. The worker that sends challenges back get stuck/blocked. Not sure why, could be a waitgroup or channel issue. Fixing this should fixe majority of the open challenges.

2. Some of the challenges are not being processed by the blobber
a) The challenge is sent by the smart contract for writes to verify if the blobber actually stored the data, if the data is not stored in the blobber the challenge should fail. Currently if the data is not available, the challenge does not fail - but continues trying to process it.
```
2021-03-02T12:26:26.680Z ERROR challenge/worker.go:39 Error getting the validation tickets {"error": "blockdata_not_found: open /blobber/files/files/a72/5bf/092/dffbe4faa10e25e42111705e758a62b1ee58730b1d19bd118a5f9f0/objects/016/1d4/556/259c61f78920be939363b04b2fabc4f: no such file or directory", "challenge_id": "fb1eaf46e5d338c944e155e805d4345437fa89e9bc23dc73c35580156dca1d3d"}
```
We should fail the challenge if there is any errors while processing it.


b) When a challenge is created by the smart contract and sent to the blobber, a list of validators are also sent within the challenge object. If for some reason the validator no longer exists while processing the challenges, the challenge will not gain consensus and the blobber will keep trying to process it.

```
2021-03-02T12:31:54.428Z INFO challenge/protocol.go:171 Got error from the validator. {"error": "Post \"http://prod-node-201.fra.jbod.zeroservices.eu:5061/v1/storage/challenge/new\": dial tcp: lookup prod-node-201.fra.jbod.zeroservices.eu on 172.20.0.10:53: no such host"}
```

We should get the validators while actually processing it.


The current implementation of challenge is overly complicated, we maybe better of rewriting current implementation.

**Comment by guruhubb** [comment]
Re 1, its likely that the chain is stuck or there are network issues. Check that.
Re 2, Yes agree, but if blobber has no data, then it should not even send the response to the validator. This way validator doesn't get paid and the rewards go back to the user. Follow the payment flow as well.
Re 3, This is a bigger problem in the sense that the validators are chosen randomly from the network. First check if it is random. 
Next check when the blobber/validator does not send the health check info to the SC, the SC updates the list and removes the unresponsive blobber and validator.  
I agree that the process of randomly getting a list of validators should be at the time of the challenge creation.

**Comment by Sriep** [comment]
The challenge staying open when the blobber does not send a response is being handled by https://github.com/0chain/0chain/issues/81.

Keep the issue open for the issue with validators Re3 above.

**Comment by Sriep** [comment]
Issue 81 now replaced by 0chian issue https://github.com/0chain/0chain/issues/198 and blobber issue  https://github.com/0chain/blobber/issues/93.

**Comment by Sriep** [comment]
The validator issue now moved to https://github.com/0chain/0chain/issues/234
