### ISSUE TITLE
Blobber block reward lottery

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#753]
# Block Rewards

We want to reward blobbers based on their total stake and recent challenge history. So each block we will run a smart contract that will reward split a fixed sum between a random collection of blobbers and their delegates. Weighting the payments by stake and recent successful challenges.

# Smart contract

1. Blobber are partitioned 
2. Select a partition at random
3. Weight the blobbers in the randomly selected partition
4. Calculate reward amounts for randomly selected blobbers. Divide up the blobber's block reward between blobbers and their delegates, taking account of weighting.
5. Rewards added to Blobber's delegate's reward object.

 The weight will be
```
challenges completed in last period * stake * write price
```

New keys to be added to sc.yaml
- `block_reward.challenge_period` - period after which block reward should be computed
- `block_reward.block_reward_change_period`- period after which block reward will reduce
- `block_reward.block_reward_change_ratio` - by how much ratio will the block reward be reduced after every block reward change period
stake is blobber's total stake excluding unstaking tokens.

The block reward amount should be flexible. For example, we will likely want it to reduce by a set proportion year on year.

**Comment by Sriep** [comment]
Related issue https://github.com/0chain/0chain/issues/831

**Comment by Sriep** [comment]
The pay_blobber_block_rewards endpoint can be removed.

**Comment by Sriep** [comment]
# Periods and Weight calculation

The weight calculation is based on data collected in the previous period. This held in the new block_reward_challenge_period smart contract setting.

 So if a period is 250 rounds. Then no rewards are given for the first 250 rounds, consider rewards as being paid in arrears. 

For example on round 7547, rewards weights will be calculated for data collected on rounds 7251 to 7500.

# Partitions

We will need a blobber partition object similar to the [validator selector](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/partitions/validator_list.go).

At any one time, we will have two partitions, one for statistics being collected for the current period (collection partition), and one for the previous period which is to be used for block rewards (active parttion). We should only keep information for blobbers that have passed a challenge or otherwise have non-null summary statistics.

Similar to the existing [ValidatorNode](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/partitions/validator_list.go#L48), we will need a BlobberBlockRewardNode
```golang
type BlobberBlockRewardNode struct {
	Id  string `json:"id"`
	passes int64 `json:"passes"`
}
```
Plus add here any other summary statistics that are needed for the weight equation. By keeping the summary stats in the partition object we can avoid having to get the Blobbers from the MPT which saves around 10-20ms.

We will also need a blobber partition object for challenge generation issue https://github.com/0chain/0chain/issues/741, however, this will be a completely separate partition with blobbers that have had challenge excuses given in the last challenge generation period.

# VerifyChallenge

1. If the blobber passes a challenge, get the current partition.
2. If the partitions are outdated then delete the active partition, rename the collection partition to the active partition and create a new empty collection partition.
3. Increment blobber partition entry for the number of passes. If the blobber is already in the partition, its location should be stored in the object.
4. If necessary update the blobber = StorageNode with the new partition location.
5. Save blobber and partition

# Block Rewards

1. Get active partitions.
2. Select random parition
3. Weight blobbers using info from portion objects.
4. Get Blobber stake pools.
5.  Add reward promise to blobber stake pools.
6. Emit event for rewards to event database for reward statitics.
7. Save stake pools.

# Block reward event database table

We will need to add block reward information to the event database for REST API calls. This can probably be done in a separate PR subsequently.

**Comment by Sriep** [comment]
# Total amount of data (TB) stored with the Blobber

Add a new field to the StorageNode object. This value is to be updated during [commit_connection](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L564) calls.

Increment the new total data stored field by the value of [WriteMarker.Size](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L1026) during each `commit_connection` call. The size field will be positive for uploads and negative for deletes.

For  use in block rewards it will likely be necessary to add this to the [BloberRewardNode](https://github.com/0chain/0chain/blob/bbr/code/go/0chain.net/smartcontract/partitions/blobber_reward.go#L16) Object

# Amount of data (TB) read from the Blobber during period N

The [BloberRewardNode](https://github.com/0chain/0chain/blob/bbr/code/go/0chain.net/smartcontract/partitions/blobber_reward.go#L16) Object will need to updated during [read_redeem](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L344).

You will need to increment the amount read by [ReadMarker.ReadSize](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L1181) on each call to `commitBlobberRead`

**Comment by mohsenno1** [comment]
> The weight will be
> 
> challenges completed in last period * stake * write price

Why write price should be included in this calculation? This means the blobbers with higher write price are more likely to be rewarded. Shouldn't this be vice versa? Do we want to motivate blobbers for increasing the write price?

**Comment by ssardana96** [comment]
> > The weight will be
> > challenges completed in last period * stake * write price
> 
> Why write price should be included in this calculation? This means the blobbers with higher write price are more likely to be rewarded. Shouldn't this be vice versa? Do we want to motivate blobbers for increasing the write price?

@mohsenno1 please ignore the weight logic above. It's not updated yet.
the calculations are under revision currently.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
