### ISSUE TITLE
Include emitted events into Block hash.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#756]
In order to ensure all modules emit the same events, we should add the emitted events to the block hash.

Currently, we emit events in [computeStateLocal](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L920). We should look for the best place to emit events so that no further block events are added.

[Transaction Hash and index](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/event.go#L13) should uniquely identify an event so we can hash this for each event, combined in a predefined order to give the event block hash.

[Block.getHashData](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L439) can then be modified to include this block events hash.

We will need to make changes to goSDK to mirror the change to 0chains block hash.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
To replace with an integrated plan for coordinating the events database.
