### ISSUE TITLE
Event db: Ensure events processed in correct order.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#757]
[Events are emitted](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/entity.go#L920)
```
go c.GetEventDb().AddEvents(b.Events)
```
and in [AddEvents](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/process.go#L31)
```
func (edb *EventDb) AddEvents(events []Event) {
    for loop that process events.
}
```
We need to ensure that events are processed in the correct order. That database tables are updated in the correct order.

We should protect AddEvents with a mutex or channels. So events from one block cannot be processed until events from the previous block are finished. We also do not want to slow down the chain by waiting for events to be processed. So, add an intermediate layer between the block calling AddEvents and events being processed; where execution can wait while events from earlier blocks are handled.

1. Start new event processing worker thread in [NewEventDb](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/eventdb.go#L8). 
2. Have the 0chain.Block thread pass the events for a block to an `event processing channel`, before continuing with the chain.
3. The event database worker thread from (1) continually polls the `event processing channel` for the next event, then processes it.

**Comment by samtholiya** [comment]
I am not using channels but using a mutex.
The reason is using a channel still does not guarantee the processing of blocks in order if its buffer is overloaded.
```golang
package main

import (
	"fmt"
	"time"
)

func Do(a chan int) {
	more := true
	for more {
		s, more := <-a
		if !more {
			return
		}
		time.Sleep(1 * time.Second)

		// Printed after sleep is over
		fmt.Println(s)
	}
}

func main() {
	send := make(chan int, 2)
	go Do(send)

	for i := 0; i < 1000000; i++ {
		go func(j int) {
			send <- j
		}(i)
	}
	time.Sleep(1000 * time.Second)
}

```
Now mutex does not solve this problem but helps process the events for one block at a time.
Yes channels could achieve the same but. it would be adding one goroutine that is not necessary and a channel memory that is not necessary as well. A mutex can achieve the same functionality and still keep the code simple

**Comment by kushthedude** [comment]
Wont the mutex block the queue for all events which are coming to be processed @samtholiya ?

**Comment by Sriep** [comment]
Can't you use an intermediate worker thread? Use two channels, ChainToWorker - an event list blocker channel, and WorkerToEventD an event buffered channel.

Chain.

1. Repeatedly send to ChainToWorker until successful.
2. Move on.

Worker

1. Poll ChainToWorker.
2. If a new event list, append it to a local event slice.
3. Check WorkerToEventDb buffer, 
4. If free space in WorkerToEventDb buffer, move slice head to ChainToEventD channel.
5. Repeat.

EventDb

1. Repeatedly poll ChainToEventD for the next event.
2. Process event
3. Repeat

**Comment by Sriep** [comment]
Reopened - This has not been fixed yet.

Events should be ordered and there should be a hash stored in the MPT for the events for a block.

The event database is always in a processing round N state. If it receives a finished round N event it moves to a processing round N+1 state. (Or it could check an event_block_hash, and only proceed when the event_block_hash in the MPT equals the one calculated by the event db processing loop.)

If a round N+m event is received in a processing round N state, the event is stored in the event table but otherwise ignored.

When the event database changes state from processing round N to processing round N+1 it can check to see if any round N+1 events are in the event table.

**Comment by dabasov** [comment]
fixed in batch-update https://github.com/0chain/0chain/pull/1724
