### ISSUE TITLE
Event db: Read and Write Allocation pool and blobber pool tables.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#760]
We need a new allocation pool table to mirror the [storagesc.allocationPool](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation_pool.go#L143) object. Each allocation pool has an slice of blobberPools so we will need a second table for that.

Foreign keys are links to tables added other issues.

AllocationId will not be unique as each allocation will have two slices of allocation pools, one for [readPools](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/readpool.go#L28) and one for [writePools](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/writepool.go#L28). So (AllocationID, IsWrtiePool) form a unique clustered index.

The storagesc.allocaionPool.Id field is actually the same as the `Transaction.Hash` of the transaction that created the pool, hence the relation to the `Transaction` table and will be unique across allocation pools. The 0chain userId is used as part of the key to store an allocation read or write pool.

We need code in events to create these databases and handle events emitted to add, remove or update rows in them.

Some 0chian storagesc smart contracts will need to modify be to emit the above events and modify the allocationPool and blobberPool tables. Every time an [allocationPoolObject](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation_pool.go#L143). or [blobberPool](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation_pool.go#L60) object is modified in the MPT a corresponding event needs to be emitted. Mostly an allocaionPool object will be changed as part of a change to the corresponding readPool or wrtiePool.
[readPoolLock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/readpool.go#L452)
[readPoolUnlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/readpool.go#L506)
[writePoolLock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/writepool.go#L240)
[writePoolUnlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/writepool.go#L374)
[newAllocationRequest](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L392)
[updateAllocationRequest](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L894) [and](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L842)
[cancel Allocation and finilizeAllocation](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1503)

| Event db allocationPool | type          | allocationPool | type          | Note                                                  |
|-------------------------|---------------|----------------|---------------|-------------------------------------------------------|
| AllocationId            | uint          |                |               | foreign key into allocation table either read or write pools                   |
| TransactionId                  | uint          |                |               | foreign key into transcation table (see above) |
| UserID                  | uint          |                |               | foreign key into user table (see above) |
| Balance                 | int64         | .Balance       | int64         |                                                       |
| Blobbers                | []blobberPool | .Blobbers      | []blobberPool |                                                       |
| IsWritePool                | bool |       |   |     Is allocation pool in readPool or witePool?  clustered unique with allocationId                                                  |

| Event db BlobberPool | type  | blobberPool         | type    | Note                                  |
|----------------------|-------|---------------------|---------|---------------------------------------|
| AllocationPoolId     | uint  |                     |         | foreign key into allocationPool table |
| BlobberId            | uint  |                     |         | foreign key into blobber table        |
| balance              | int64 | blobberPool.Balance | Balance |                                       |

**Comment by Sriep** [comment]
[Rest Api endpoints](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/sc.go#L93) /getReadPoolStats, /getReadPoolAllocBlobberStat, /getWritePoolStat, /getWritePoolAllocBlobberStat, /getStakePoolStat and /getUserStakePoolStat will need to be modified to use these new tables.

**Comment by Sriep** [comment]
https://github.com/0chain/0chain/issues/774 will be adding new reward fields to stake pools.

**Comment by Sriep** [comment]
It might be better to split into two tables. ReadAllocationPool and WriteAllocationPool

| Event db ReadAllocationPool | type          | allocationPool | type          | Note                                                  |
|-------------------------|---------------|----------------|---------------|-------------------------------------------------------|
| AllocationId            | uint          |                |               | foreign key into allocation table either read or write pools                   |
| TransactionId                  | uint          |                |               | foreign key into transcation table (see above) |
| UserID                  | uint          |                |               | foreign key into user table (see above) |
| Balance                 | int64         | .Balance       | int64         |                                                       |
| Blobbers                | []blobberPool | .Blobbers      | []blobberPool |                                                       |


| Event db WriteAllocationPool | type          | allocationPool | type          | Note                                                  |
|-------------------------|---------------|----------------|---------------|-------------------------------------------------------|
| AllocationId            | uint          |                |               | foreign key into allocation table either read or write pools                   |
| TransactionId                  | uint          |                |               | foreign key into transcation table (see above) |
| UserID                  | uint          |                |               | foreign key into user table (see above) |
| Balance                 | int64         | .Balance       | int64         |                                                       |
| Blobbers                | []blobberPool | .Blobbers      | []blobberPool |                                                       |

**Comment by Sriep** [comment]
We need to remember the initial value of an allocation pool. 
 Add a `StatBalance` field to the allocationPool table.

Send the `StatBalance` along as the pool's balance when a pool is first created. After this first update the `StatBalance` pool is immuatable.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
This will need to be coordinated with the change t read and write pools https://github.com/0chain/0chain/issues/1064 and https://github.com/0chain/0chain/issues/1062.

**Comment by Sriep** [comment]
Replaced with https://github.com/0chain/0chain/issues/1062 and https://github.com/0chain/0chain/issues/1064
