### ISSUE TITLE
Event db: New allocation blobber terms table

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#761]
We need a table to hold an allocation's blobber's terms. This will not in general be the same as the blobber's terms. They will start the same but allocation's blobber's terns will not necessarily change if the corresponding blobber's terms change.

The (allocationId and BlobberId) foreign keys form a unique clustered index.

Add code in event database to create the table and support events to add, delete or update rows.

We need changes to 0chain.storagesc smartcontracts to emit events every time [StorageAllocaion.BlolbberDetails.Terms](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L404) changes
[newAllocationRequest](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L401)
[UpdateAlloctionRequest](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1057)
[Finilise allocation](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1341)
[Cancel allocation](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1267)

| Event db Terms          | type    | StorateAllocaion.BlolbberDetails.Terms                   | type          | notes                                         |
|-------------------------|---------|-------------------------|---------------|-----------------------------------------------|
| AllocationId             | uint    |                         |               | foreign key into allocaion table              |
| BlobberId               | uint    |                         |               | foreign key into blobber table                |
| ReadPrice               | int64   | ReadPrice               | Balance       |                                               |
| WritePrice              | int64   | WritePrice              | Balance       |                                               |
| MinLockDemand           | float64 | MinLockDemand           | float64       |                                               |
| MaxOfferDuration        | int64   | MaxOfferDuration        | time.Duration | is int64 the best method of saving durations? |
| ChallengeCompletionTime | int64   | ChallengeCompletionTime | time.Duration |                                               |

**Comment by ma2b0043** [comment]
@sriep when can we expect to close this issue?
