### ISSUE TITLE
Event db: Allocation curator table

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#762]
This table mirrors the [StorageAllocaion.Curators](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L601) field.

The `CuratorId` is logically a key into the user's table, however, there is no guarantee that the CuratorId will be a valid user. For example, adding an id as a curator and registering the id as a 0chain user can happen in either order.

Add the Curator table to Event database. Add code to add, and remove a curator.

We need to emit events in 0chain.storagesc to induce changes to this table.
[addCurator](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/curator.go#L99)
[removeCurator](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/curator.go#L62)

| Event db Curator | type   | StorageAllocaion.curators | type   | Note                              |
|------------------|--------|---------------------------|--------|-----------------------------------|
| allocationId     | uint   |                           |        | foreign key into allocation table |
| CuratorId        | string | curators[i]               | string |                                   |

**Comment by amanjain97** [comment]
@Sriep AllocationID is actually `string` type in CuratorInput struct in storagesc. Throughout the smartcontract package, it is used as `string`. Shall we change it to string ?
