### ISSUE TITLE
Event db: Allocation table

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#763]
We need a new Event database Allocation table to mirror [storagesc.StorageAllocaion](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L544)

We need code in event database to include the table as well as support events that add, delete or update allocations. Also we need to take account of the extra complications of sub tables.

TransactionId, foreign key into Transcation table, is the last transaction to modify the allocation object.
[Terms](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L404) , the variable data from the StorateAllocaion.BlobberDetails.Terms object.
Curators, a []string field in the StorageAllocastion object
ReadPools, allocation pools with IsWritePool = false
WrietPools, allocation pools with IsWritePool = true

We need to emit events in `storagesc` when an allocation is added or updated. changes:
[newAllocationRequest](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L401)
[UpdateAlloctionRequest](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1057)
[Finilise allocation](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1341)
[Cancel allocation](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1267)

The [\allocation](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/handler.go#L178) can be redone to use this table. The [\allocations](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/handler.go#L106) also, but this should be appreciated or redesigned.

| Event db Allocaion table   | type             | StorageAllocation              | type               | notes                                                     |
|----------------------------|------------------|--------------------------------|--------------------|-----------------------------------------------------------|
| AllocaionID                | string           | ID                             | string             | unique key                                                |
| TransactionId              | uint             | Tx                             | string             | foreign key into transaction table                        |
| DataShards                 | int              | DataShards                     | int                |                                                           |
| ParityShards               | int              | ParityShards                   | int                |                                                           |
| Size                       | int64            | Size                           | int64              |                                                           |
| Expiration                 | int64            | Expiration                     | Timestamp          |                                                           |
| Terms                      | []Terms          | BlobberDetails                 | []BlobberAllocaion | Terms sub table contains foreign keys for linked blobbers |
| Owner                      | string           | Owner                          | string             | Should this be foreign key into user table?               |
| OwnerPublicKey             | string           | OwnerPublicKey                 | string             |                                                           |
| IsImmutable                | bool             | IsImmutable                    | bool               |                                                           |
| ReadPriceMin               | int64            | ReadPriceRange.Min             | Balance            |                                                           |
| ReadPriceMax               | inat64           | ReadPriceRange.Max             | Balance            |                                                           |
| WritePriceMin              | int64            | WritePriceRange.Min            | Balance            |                                                           |
| WritePriceMax              | int64            | WritePriceRange.Max            | Balance            |                                                           |
| MaxChallengeCompletionTime | int64            | MaxChallengeCompletionTime     | time.Duration      |                                                           |
| ChallengeCompletionTime    | int64            | ChallengeCompletionTime        | time.Duration      |                                                           |
| StartTime                  | int64            | StartTime                      | TimeStamp          |                                                           |
| Finalized                  | bool             | Finalized                      | bool               | Only one of finalized or cancelled can be true.           |
| Cancelled                  | bool             | Canceled                       | bool               | Misspelt                                                  |
| UsedSize                   | int64            | UsedSize                       | int64              |                                                           |
| MovedToChallenge           | int64            | MovedToChallenge               | Balance            |                                                           |
| MovedBack                  | int64            | MovedBack                      | Balance            |                                                           |
| MovedToValidators          | int64            | MovedToValidators              | Balance            |                                                           |
| Curators                   | []Curator        | Curators                       | []string           | curator sub table                                         |
| TimeUnit                   | int64            | TimeUnit                       | time.Duration      |                                                           |
| UsedSize                   | int64            | Stats.UsedSize                 | int64              | Stats will be moved out of StorageAllocation object       |
| NumWrites                  | int64            | Stats.NumWrites                | int64              | Stats will be moved out of StorageAllocation object       |
| NumReads                   | int64            | Stats.NumReads                 | int64              | Stats will be moved out of StorageAllocation object       |
| TotalChallenges            | int64            | Stats.TotalChallenges          | int64              | Stats will be moved out of StorageAllocation object       |
| OpenChallenges             | int64            | Stats.OpenChallenges           | int64              | Stats will be moved out of StorageAllocation object       |
| SuccesfulChallenges        | int64            | Stats.SuccessChallenges        | int64              | Stats will be moved out of StorageAllocation object       |
| FailedChallenges           | int64            | Stats.FailedChallenges         | int64              | Stats will be moved out of StorageAllocation object       |
| LatestClosedChallengeTxn   | uint             | Stats.LatestClosedChallengeTxn | string             | foreign key into Transaction table                        |

**Comment by wittyjain** [comment]
@kushthedude

**Comment by Sriep** [comment]
We need a new endpoint to return the number of active allocations.
```sql
select count(*) from Allocations where Finalized = false and Cancelled = false
```

**Comment by Sriep** [comment]
We need a new endpoint to return the number of blobber allocations

```sql
select sum(ParityShards) + sum(DataShards) from Allocations where Finalized = false and Cancelled = false
```

**Comment by Sriep** [comment]
Removed reference to isNft

**Comment by ma2b0043** [comment]
@sriep when can we expect to close this issue?
