### ISSUE TITLE
Event db: ReadMarker table

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#764]
We need an event database [ReadMarker](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L1166) table. this is populated during [read_redeem](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L344).

We need code for the new table and add ReadMarker method. There five foreign keys into other tables to arrange.

We need to emit an add ReadMarker event in[commitBlobberRead](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L348) which includes the input ReadMarker sent by the blobber plus the transaction hash.
ReadSize is the difference between the last readCounter and this one [commitBlobberRead](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L419) .

The [/latestreadmarker](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/handler.go#L194) can be reworked to use this table.

https://github.com/0chain/0chain/issues/789 adds new API methods to access this table.

| Event db ReadMarker | type   | ReadMarker   | type      | notes                              |
|---------------------|--------|--------------|-----------|------------------------------------|
| Client              | uint   | ClinetId     | string    | foreign key into user table        |
| BlobberId           | uint   | BlobberId    | string    | foreign key into blobber table     |
| AllocationId        | uint   | AllocationId | string    | foreign key into allocation table  |
| TransactionId       | uint   | t.Hash       | string    | foreign key into transaction table |
| OwnerId             | uint   | OwnerId      | string    | foreign key into user table        |
| Timestamp           | int64  | Timestamp    | Timestamp |                                    |
| ReadCounter         | int64  | ReadCounter  | int64     |                                    |
| ReadSize         | int64  | ReadCounter  | int64     |                                    |
| Signature           | string | Signature    | string    |                                    |
| Suspend             | int64  | Suspend      | int64     |                                    |
| PayerId             | uint   | PayerID      | string    | foreing key into user table        |
| AuthTicket          | string | AuthTicket   | JSON      |      searchable index                              |
| BlockNumber             | int64  | txn.Round      | int64     |                                    |

**Comment by ssardana96** [comment]
@Sriep is `Suspend` key deprecated?

**Comment by Sriep** [comment]
I am not convinced `Suspend` is used, but it is there so I added it for completeness.
