### ISSUE TITLE
Transaction: nonce

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#765]
### Abstract
Nonce is a new integer field that will be added to Transaction. 
`Nonce           int64             json:"nonce" msgpack:"n"`
Nonce will be used to order transactions for arbitrary client, if `tx1.nonce < tx2.nonce`, then transaction tx1 must be executed before tx2, nonce is unique for current client. If tx2 follows tx1 and there is no other transactions between them, `t2.nonce = t1.nonce + 1`. 
Creation_date becomes informational field and no longer is used for ordering transactions.
This is client’s responsibility to manage nonce, usually it is done through wallet or other software. Common way to manage nonce on client will be to query server for nonce of last successfully executed transaction for current client and increment it  for newly created transaction. It is pretty normal to send several transactions for execution at once with sequentially incremented nonces, they will be executed ordered by nonce.
Nonce becomes part of state, it means that nonce will be stored in MPT together with clients’ balances

### Components to be changed
- **Miner** 
**Tx_pool**. Transactions are added to pool as usual. 
**Generator**. Transactions will be picked out of the pool in ascending order, sorted by receive time, as it is done now. For every transaction picked from the pool, generator must check that `tx.nonce - client.nonce = 1`, if not this transaction will be returned to the pool. Such transaction can be executed in the future when nonce gap will be filled by missed transactions, it can usually happen due to transaction reordering. If transaction is not executed for a long time it will be evicted from the pool. If several transactions have the same nonce the oldest will be executed. 
_Note: later on It’ll be possible to order them by fee, like it is commonly done in blockchains, then in case of equal nonce transaction with biggest fee will be executed first (one can cancel transaction in the pool this way)_
**Executor**. For every transaction executor must check current client’s nonce stored in state and if tx.nonce-current != 1 must fail transaction with proper error code. After transaction is executed nonce should be incremented in State structure for current client.
**Handler**. Handler `/v1/client/get/nonce?client_id={{wallet_id}} `to query nonce will be added. Handler will return nonce at LFB state version.
**MPT**.  State structure will be changed, nonce field will be added.
`Nonce        int64   json:"nonce" msgpack:"n"`
**Client code**. There are several places in the code where miner sends transaction to 0chain. Request to nonce endpoint should be added before transaction to obtain current nonce.
- **GoSDK**
Client should add request to nonce endpoint to obtain current client’s nonce before every transaction. Client can cache nonce for a session and update properly. 
- **BlockExplorer**
There should be added nonce field to the transaction body

**Comment by Sriep** [comment]
We need a `User` table in the Event database to use for foreign keys into other tables. Mirrors [State](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/state/state.go#L16). See https://github.com/0chain/0chain/issues/778

Could use this for `getNonce` (And also maybe `getBalacne`) REST API calls?

**Comment by dabasov** [comment]
@Sriep yeah, I don't see an issue here, even if requested nonce is not fresh enough due to some crash, it won't break n/w and miner will simply fail transaction, so looks good to me

**Comment by Sriep** [comment]
Also, you might look at https://github.com/0chain/gosdk/issues/326. This seems to be making similar changes to the same goSDK methods you would need to change to get nonce for a transaction. 
So each smart-contract transaction will be potentially sandwiched between two REST-API calls.

**Comment by peterlimg** [comment]
Maybe we don't have to get nonce every time when create a transaction, clients can save the last successfully executed transaction nonce locally, we can use the `nonce +1` to create a new transaction directly, and only when it failed, should we send request to get the latest nonce, or we can have the latest nonce returned with the failed transaction error message. This could reduce lots of MPT access and we don't need to send 2 requests for 1 transaction. @dabasov @Sriep @guruhubb what do you think.

**Comment by dabasov** [comment]
@peterlimg actually, we can store nonces in the cache on server lower the load on MPT, like we do for confirmations for example. or we can use event db for querying nonces, what @Sriep offered
but, I agree, we should reduce http queries first of all, for thet we can cache nonces on clients and request it from server on cache invalidations, just what I suggest here 
> Client can cache nonce for a session and update properly.
then client can do `nonce+1` 

obviously, this cache approach on client won't work if there are several devices that execute transactions for single client, don't think it will happen ofyrn

**Comment by peterlimg** [comment]
Yes, even if we have several devices that use the same client, it can still work if devices can get last nonce from the error response message and retry the transaction with new nonce.

**Comment by ma2b0043** [comment]
@dabasov when can we expect to close this issue?

**Comment by dabasov** [comment]
@ma2b0043  in a week
