### ISSUE TITLE
Core: cancel generator on round change

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#767]
Block assemble should be cancelled in two cases:
1. Current round is transitioned to the next round (notarization received)
2. Round is timed out,(new block should be assembled)

Should discuss second case, after restart current generator can be generator again and generated block can be reused with different RRS, it is possible because state did not change during restart

**Comment by peterlimg** [comment]
@dabasov , is this fixed in fix/staging_vrf_next_round_not branch?

**Comment by dabasov** [comment]
@peterlimg atm we use root context to start generator, but code is refactored and ready to fix it, this func is responsible for generation:
``
func (mc *Chain) TryProposeBlock(ctx context.Context, mr *Round)
``

First case is easy to implement, the similar way as verification is implemented (store cancel function and call it in case of transition to the next round)

The second case will need to adjust block generation cancellation, we discussed yesterday with @guruhubb. 
The idea is as follows: use context cancellation to stop transaction select and state computation and return assembled block. It can be useful to limit generation time on generator (to delta or similar interval) and to reuse generated block between timeouts (simply add it to round as own proposal)
