### ISSUE TITLE
Event db: Challenge table.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#769]
We need a new Challenge table for the Event Db.

Code for this already exists in https://github.com/0chain/0chain/pull/679 [challenge.go](https://github.com/0chain/0chain/blob/challenge-events/code/go/0chain.net/smartcontract/dbs/event/challenge.go#L10).

This needs to be reworked as part of https://github.com/0chain/0chain/issues/741. The event database code should be altered to use the blobber table rather than the blobberChallenge table.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
