### ISSUE TITLE
New storagesc update_validator_settings endpoint

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#773]
We need a new storage smart contract endpoint, update_validator_settings. This will act in much the same way as [update_blobber_settings](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L224) but will update a validator's stake pool settings. 

Related to https://github.com/0chain/0chain/issues/772

**Comment by ma2b0043** [comment]
@sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
ref https://github.com/0chain/0chain/issues/905
