### ISSUE TITLE
Add local global settings to MPT,

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#776]
The [0chian.yaml.development.txn_generation.min_txn_fee](https://github.com/0chain/0chain/blob/staging/docker.local/config/0chain.yaml#L81) is currently different for each miner and stored as a [global variable](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/miner/miner/main.go#L60).

We want to add min_txt_fee to the global settings saved to the MPT, so that it is the same network-wide.

**Comment by Sriep** [comment]
The following settings are to be kept in the MPT. They need a `update_global_settings` transaction to change.

The indicated settings [following global settings](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/globals.go#L26). These are either stored in the [global development object](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/config/dev_config.go#L5), in the chain or other ad-hock global variables.

We need to move the vales from their current location to the chain's [Config object](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/config.go#L53).

```go
	State         // todo from development
	Dkg                               // todo from development
	ViewChange                        // todo from development
	BlockRewards                      // todo from development
	Storage                           // todo from development
	Faucet                            // todo from development
	Interest                          // todo from development
	Miner                             // todo from development
	Multisig                          // todo from development
	Vesting // todo from development
	Owner   // probably don't want this changeable
	BlockGenerationTimout        // todo from chain
	BlockGenerationRetryWaitTime // todo from chain
	RoundTimeoutsTimeoutCap // todo from chain
	TransactionTimeout // todo from global
	TransactionMinFee  // todo from global
	ClientDiscover // todo from chain
	StateSyncTimeout   // todo from chain
	StuckCheckInterval // todo from chain
	StuckTimeThreshold // todo from chain
	LfbTicketAhead                           // todo from chain

```

**Comment by Sriep** [comment]
The following entries should not be held in the MPT but read from the `0chain.yaml` file
```  
dbs:
    events:
      enabled: true
      name: events_db
      user: zchain_user
      password: zchian
      host: postgres #localhost
      port: 5432
      max_idle_conns: 100
      max_open_conns: 200
      conn_max_lifetime: 20s
```

**Comment by Sriep** [comment]
https://github.com/0chain/0chain/issues/736 also updates settings with new security levels.

**Comment by ssardana96** [comment]
In this issue we'll be doing `min_txt_fee`. The other global changes will have a bigger impact, separated in #1029
