### ISSUE TITLE
 Zcnsc: Authorizer should have delegates

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#777]
The zcnsc's authorizer shold have delegates in the same way as miners, sharders, blobbers and validators have delegates. 

The common [stakepool code](https://github.com/0chain/0chain/tree/staging/code/go/0chain.net/smartcontract/stakepool) can be used for this. Check the [storagesc.collect_reward endpoint](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/collect_reward.go#L10) and calls to DistributeRewards https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/challenge.go#L145, https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1444 etc.

Fees are to be paid when the user convert zcn-native to zcn-erc and vice versa. https://github.com/0chain/0chain/issues/882. These fees can then be distributed to stakeholders.

We will also need a `collect_reward` smartcontract, similar to [storagesc](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/collect_reward.go#L11) and [minersc](https://github.com/0chain/0chain/blob/miner-rewards/code/go/0chain.net/smartcontract/minersc/collect_reward.go#L14).

These two PRs [miner rewards](https://github.com/0chain/0chain/pull/1025) and [StakePool event database table](https://github.com/0chain/0chain/pull/1013) are related.

**Comment by Dmdv** [comment]
Blocked because delegates needs reworks

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by Dmdv** [comment]
@ma2b0043 closed
