### ISSUE TITLE
Event db: User table

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#778]
We need a users table for the event database. This gives foreign keys in several other tables. [WriteMarker](https://github.com/0chain/0chain/issues/768) [ReadMarker](https://github.com/0chain/0chain/issues/764) [Allocation](https://github.com/0chain/0chain/issues/763) [Curator](https://github.com/0chain/0chain/issues/762) and [Allocation Pool](https://github.com/0chain/0chain/issues/760).

The state object is typically handelled outside smart contracts. The MPT data object is [State](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/state/state.go#L16).

The user is part of the key the user state is stored under. [getState](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state.go#L441).
Nonce will be added as part of https://github.com/0chain/0chain/issues/765.

Change balance events will need to be emitted each time a user's wallet balance changes. Changes to:
-  [AddTransfer](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state/state_context.go#L128) 
-  [AddMint](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state/state_context.go#L145).
- others ...?

| Users         | type   | State         | type    | notes                                                |
|---------------|--------|---------------|---------|------------------------------------------------------|
| TransactionId | uint   | State.TxHash  | string  | foreign key to last transaction to change user state |
| Balance       | int64  | State.Balance | Balance |                                                      |
| UserId        | string |               | string  | used in MPT key                                      |
| Nonce         | int64  |               | int64   | added issue 765                                      |

**Comment by Sriep** [comment]
We will want to add a GetNonce REST-APi method to get the nonce for a user. This will probably be done as part of https://github.com/0chain/0chain/issues/765.

Also, change the [getBalance](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state_handler.go#L103) REST API method to use this table. This should help with testing. 
1. Add the new getBalance endpoint, which is using the User table.
2. The old getBalance endpoint should be used for backward compatibility on older chains. Call this if the new endpoint is about to error with cannot find event db or user.
3. Change GoSDK to switch to the new endpoint here https://github.com/0chain/gosdk/blob/staging/zcncore/wallet.go#L47. Change GET_BALANCE to point to new endpoint.

**Comment by ssardana08** [comment]
@Sriep will we need new API to get user details based on ID, or some transaction for this?

**Comment by ssardana96** [comment]
@Sriep we'll have to make [GetClient](https://github.com/0chain/0chain/blob/c09c99073035d97e8cd6db17db406872ac81e9c0/code/go/0chain.net/chaincore/client/entity.go#L272) to be now read from eventsdb, right?

**Comment by ma2b0043** [comment]
@Sriep @ssardana08 when can we expect to close this issue?

**Comment by Sriep** [comment]
Need to resolve https://github.com/0chain/0chain/issues/933

**Comment by samtholiya** [comment]
@Sriep #969 is already merged in the same pr
