### ISSUE TITLE
Event db: Authorizer table for zcnsc

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#784]
1. We will need an Authorizer table in the eventdb,
2. Each time an authorizer changes we will need to emit an event.
3. Then code in the event database to process zcnsc events.
4. Change getAuthorizerNods to get data from eventDB rather than MPT.

| Authorizer   | type   | zcnsc.AutorizerNode | type   | notes |
|--------------|--------|---------------------|--------|-------|
| AuthorizerId | string | ID                  | string |  unique index     |
| PublicKey    | string | PublicKey           | string |       |
| URL          | string | URL                 | string |       |
| Balance      | int64  | Balance             | int64  |       |

gorm.Model already has an ID field, so use AuthorizerId for string id.

**Comment by Dmdv** [comment]
From our discussion
> So we will need an Authorizer table in the eventdb,
> Each time an authorizer changes we will need to emit an event.
> Then code in the event database to process zcnsc events.
> Change getAuthorizerNods to get data from eventDB rather than MPT.
> How many a authorizer nodes can this endpoint expect to return? Assuming a running chain > > with 10million allocaions and users, 100,000 blobbers etc.

**Comment by Sriep** [comment]
this is a repeat of https://github.com/0chain/0chain/issues/842
