### ISSUE TITLE
Event db API: data stored in network.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#787]
We need an endpoint to return the amount of data stored on the network.

# storagesc

Each blobber will send a [WriteMarker](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L1018) for each change to data stored on the blobber.

The [StorageNode](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/models.go#L304) will have a new field to reflect the amount of data stored on the blobber. This field is updated with the information in the WriteMarker each call to [commitBlobberConnection](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L556).

Each time this blobber field is updated we need to emit an event to update the blobber table with this new value. 

# Event db

This will require a new SavedData field on the Blobber table.

The new endpoint will then return the aggregate value for all data stored across all blobbers.

```sql
SELECT SUM(saved_data) AS total FROM blobber;
```

**Comment by shaktals** [comment]
@Sriep for the _total storage and utilization_ data that will be needed by the new explorer, we will need not just the current values, but also the values for yesterday, the day before, and so on.

So we'd need a service to query this info from blobbers and save it to a new table, so that the data progression can be displayed.

**Comment by Sriep** [comment]
Also lok at issues https://github.com/0chain/0chain/issues/922 and https://github.com/0chain/0chain/issues/903
