### ISSUE TITLE
BC gets stuck when VC:true

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#79]

**Comment by peterlimg** [comment]
@guruhubb reported on slack:
> four devnet is stuck with VC:true when miner/sharder tried to join - pls check the errors - there are n2n errors such as block_not_available: Requested block is not available which is probably resulting in update_mb_worker	{"error": "no finalized magic block from sharders  error and setting DKG from store	{"mb_round": 5751, "error": "unexpected end of JSON input"}

**Comment by peterlimg** [comment]
Perhaps the block is not available  error is not the reason why the BC get stuck, it an error caused by the BC stuck. I find logs that a miner keeps request a block of specific round for a long time, every request got the response with error of ‘block is not available’.  When a miner receives the block request, it would check the requested round and get the heaviest notarized block in that round, but if the BC got stuck, and there’s no block generated in that round, we will see this error.

**Comment by guruhubb** [comment]
It seems the same issue that you reported in your second comment for #85 where the state is not in sync in some of the miners. So sync with sharders first and then miners as a last resort.

**Comment by peterlimg** [comment]
Close this and work on #192
