### ISSUE TITLE
Event db: New Miner table and Sharder table.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#790]
We need a new miner table. 

To populate we need to emit event:
-  [add_miner](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L143) Add.
-  [update_miner_settings](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L348)  Update.
- [payFees](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/fees.go#L350) Update fees.
- [DeleteMiner](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L255) Delete but see https://github.com/0chain/0chain/issues/499
- [stakePoolLock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L921) and [stkePoolUnlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L999) update TotalStake.
- [createMagicBlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/dkg.go#L787) Update status.

| Miner             | type    | SimpleNode        | type    | note                                   |
|-------------------|---------|-------------------|---------|----------------------------------------|
| MinerId           | string  | ID                | string  | unique key                             |
| N2NHost           | string  | N2NHost           | string  |                                        |
| Host              | string  | Host              | string  |                                        |
| Port              | int     | Port              | int     |                                        |
| Path              | string  | Path              | string  |                                        |
| PublicKey         | string  | PublicKey         | string  |                                        |
| ShortName         | string  | ShortName         | string  |                                        |
| BuildTag          | string  | BuildTag          | string  |                                        |
| TotalStaked       | int64   | TotalStaked       | int64   |                                        |
| Delete            | bool    | Delete            | bool    |                                        |
| DelegateWallet    | string  | DelegateWallet    | string  |                                        |
| ServiceCharge     | float64 | ServiceCharge     | float64 |                                        |
| NumberOfDelegates | int     | NumberOfDelegates | int     |                                        |
| MinStake          | Balance | MinStake          | Balance |                                        |
| LastHealthCheck   | int64   | LastHealthCheck   | int64   |                                        |
| Rewards           | Balance | GeneratorRewards  | Balance |                                        |
| Fees              | Balance | GeneratorFees     | Balance |                                        |
| TotalStake   | Balance |    TotalStake  | Balance |   new field update in Lock and Unlock   |
| Active            | bool    | Status            | int     | NodeStatusInactive or NodeStatusActive |
| TotalStake        | Balance | TotalStake        | Balance | Update whenever stake changes          |
| Longitude        | int | Longitude        | int | added in    https://github.com/0chain/0chain/issues/793      |
| Latitude        | int | Latitude        | int |  added in  https://github.com/0chain/0chain/issues/793      |

**Comment by Sriep** [comment]
We also need a new `Sharder` table. This is identical to the `Miner` table, except uses [add_sharder](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sharder.go#L84) and [update_sharder_settings](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sharder.go#L16) and [delete_sharder](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sharder.go#L194).

Otherwise, sharder code is usually just below the miner code.

**Comment by Sriep** [comment]
The Miner and Sharder tables can be used to provide data for the [/getMinerList](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L81) and [getSharderList](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L91) and [nodeStat](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L222) endpoints.

We need two new API endpoint that returns the number of active and number of inactive miners and sharders respectively.
```sql
select count(*) from Miner where Active = true
select count(*) from Miner where Active = false
```
and
```sql
select count(*) from Sharder where Active = true
select count(*) from Sharder where Active = false
```

**Comment by Sriep** [comment]
Geolocation fields https://github.com/0chain/0chain/issues/793

**Comment by Sriep** [comment]
We need a new API method to return the total stake of miners.
```sql
select sum(total_stake) from miner
```

We need a new API method to return the total stake of sharders.
```sql
select sum(total_stake) from sharder
```

**Comment by ssardana96** [comment]
> The Miner and Sharder tables can be used to provide data for the [/getMinerList](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L81) and [getSharderList](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L91) and [nodeStat](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/handler.go#L222) endpoints.
> 
> We need two new API endpoint that returns the number of active and number of inactive miners and sharders respectively.
> 
> ```sql
> select count(*) from Miner where Active = true
> select count(*) from Miner where Active = false
> ```
> 
> and
> 
> ```sql
> select count(*) from Sahrder where Active = true
> select count(*) from Sharder where Active = false
> ```

@Sriep rather than creating a new endpoint, we can extend getMinerList and getSharderList with query params active=true inactive=true. or status = 1(active) 2(inactive)

**Comment by ssardana96** [comment]
Tasks to do for addminer:
* in chain.updateState -> pass eventdb in StateContext sctx
* Use the eventdb to query & if there is no data, code should be backward compatible to lookup in trie.
* Write should be happening to only eventdb now and not MPT

**Comment by ssardana96** [comment]
@Sriep @kushthedude why is StateContext called `balances` everywhere in code?
What is it that StateContext contains?

**Comment by ssardana96** [comment]
@Sriep @kushthedude as of now there is a concept of GlobalNode in addminer.
Now with EventDb integration, we will have to keep this also in EventDb?
If yes, how will it be stored? and with that we will have to make changes to [getGlobalNode](https://github.com/0chain/0chain/blob/1e8779f639d24bcd832baaf07adbd2e31915b066/code/go/0chain.net/smartcontract/minersc/sc.go#L188) as well.

**Comment by ssardana96** [comment]
> 

@Sriep currently SimpleNode has `MaxStake` as well. Don't we need that in miner db?
@Sriep there is an existing field `TotalStaked` and you've mentioned a new property to be added `TotalStake`. What's the difference between two?

**Comment by Sriep** [comment]
Adding new functionality to existing endpoints should be fine, just make sure backwards compatibility is maintained.

**Comment by Sriep** [comment]
StateContextI is called balances everywhere in the code for historic reasons, please refer to GitHub commit history logs for more details.

StateContextI allows smartcontracts to communicate outside their deterministic bubble. For example, it provides access to the block_chains MPT database, it also allows smart contracts to request mints and balance transfers. It also allows access to the block object with information like block number, block time.

**Comment by Sriep** [comment]
```
as of now there is a concept of GlobalNode in addminer.
Now with EventDb integration, we will have to keep this also in EventDb?
```
No request to add GlobalNode at the moment. 

We will want to move [existing endpoints](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/sc.go#L92) to the event database where possible.

**Comment by ssardana96** [comment]
```
@Sriep there is an existing field TotalStaked.
But in the table above you've mentioned a new property to be added TotalStake. 
What's the difference between two?
```

@Sriep can you clarify on this

**Comment by Sriep** [comment]
Assume `TotalStaked` and `TotalStake` are the same.
Not sure if we need `MaxStake` but we have `MinStake` so should probably have `MaxStake` as well.

**Comment by ssardana96** [comment]
@Sriep as Active is a new field in Miner Table.
We need to list down all the places where the status would be active and where all it'll be inactive

it's clear in [createMagicBlock](https://github.com/0chain/0chain/blob/1e8779f639d24bcd832baaf07adbd2e31915b066/code/go/0chain.net/smartcontract/minersc/dkg.go#L759) that it'll be taken from `Status`
What is expected behavior in other scenarios - AddMiner, UpdateMinerSettings, etc.

**Comment by ssardana96** [comment]
@Sriep do we need a `Delete` field in Miner Table?
as we would be hard deleting miner always

**Comment by ssardana96** [comment]
```
We need a new miner table.

To populate we need to emit event:

add_miner Add.
update_miner_settings Update.
payFees Update fees.
DeleteMiner Delete but see Make delete miner or sharder permanent #499
stakePoolLock and stkePoolUnlock update TotalStake.
createMagicBlock Update status.
```

@Sriep @kushthedude Miner table is almost done. Blockers for me:
- Active is a new field, so we need to find what will be it's value at various places - while updating, adding new, etc.
- `stakePoolLock and stakePoolUnlock update TotalStake.` is this related to miner table? I'm not able to find a link between storagesc and miners event. Need help!

**Comment by Sriep** [comment]
```
We need to list down all the places where the status would be active and where all it'll be inactive
```
You need to emit an event whenever the field can change value. So search for `.Status =` in `minersc` But remember this is a miner not a delegate pool which also has a Status field. As far as I can tell this is createMagicBlock

**Comment by Sriep** [comment]
`do we need a Delete field in Miner Table?`
This indicates that the node is to be deleted at the next view change. I can't think of a reason not to include it, users might be interested in filtering by this value.

**Comment by Sriep** [comment]
You should not need to make any changes in storagesc. stakePoolLock and Unlock are for blobbers.
