### ISSUE TITLE
Event db API: Data written from allocation. Data read from allocation.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#791]
New endpoint to return the amount of data written to allocation for last N blocks.
```sql
SELECT SUM(Size) AS total FROM WriteMarker WHERE BlockNumber > ?
```

New endpoint to read the amount of data read from allocation.
```sql
SELECT SUM(ReadSize) AS total FROM ReadMarker WHERE BlockNumber > ?
```

Where ? is typically enough blocks to cover last 7 days, 30 days or 90 days. Can get current block number from Block table.

We want an endpoint to return the number of writes to the write marker table for an allocation.
```sql
SELECT count(*) FROM WriteMarker WHERE AllocationId =  params.Get("allocation_id")
```

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
From https://github.com/0chain/0chain/issues/904
```
UI requires to show the read write action in realtime in a map.

Do /latestReadMarker and /latestWriteMarker when implemented
 be able to contribute to the requirement of read write data count for each blobber ?
If so then we need to publish the /latestReadMarker, /latestwriteMarker 
and the required party will subscribe to it ?
```
