### ISSUE TITLE
Event db API: Change `screst` handler to use event database endpoints.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#796]
Event database API endpoints should be kept in a package close to the event database. Not in the smart contract as they are now. 

This will need changes in `chaincore/chain/state_handler.go` to redirect to the new endpoints. In particular [GetSCRestPoints](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state_handler.go#L165). 

This is the current code that gets the endpoints.
```go
	scInt, ok := smartcontract.ContractMap[key]
        ...
	restPoints := scInt.GetRestPoints()
```
We should keep this during transition but add access to the new map of event database API endpoints.

**Comment by Sriep** [comment]
Also consider https://github.com/0chain/0chain/issues/857.  We will want to split the `SmartContractInterface` into a `SmartContractInterface` and a `RestApiInterface`.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
This will likely be done as part of https://github.com/0chain/0chain/issues/926.

**Comment by Sriep** [comment]
Close for the moment in favour of https://github.com/0chain/0chain/issues/926
