### ISSUE TITLE
GetStakePoolInfo to add similar field as "free" to reflect Staked Capacity in terms of ZCN/GB.

### ISSUE THREAD

**Issue by krishnemd** [0chain/0chain#797]
As per the[slack convo](https://0chain.slack.com/archives/C01U94VF56Y/p1637924638278800) and the present implementation of sp-info as seen on CLI we need to reflect Staked Capacity in terms of ZCN/GB rather than GB. I am not sure if its already implemented or not but I think posting here will be helpful to extract out the required value if already implemented.
<img width="1095" alt="Screen Shot 2021-12-18 at 11 21 01" src="https://user-images.githubusercontent.com/34975245/146630798-bbd36277-c7e8-4a3e-9b82-30818ab0520b.png">

[GetStakePoolInfo](https://github.com/0chain/gosdk/blob/582679edb2b611f71b66106beb72e44ae520303b/zcncore/wallet.go#L1231)

**Comment by Sriep** [comment]
https://github.com/0chain/0chain/issues/814 will redo stake pool endpoints to use the Event database.

**Comment by shaktals** [comment]
@chauchausoup @Sriep as per slack conversation mentioned on the title, we don't need another field on the getStakePoolInfo.

We just need to know **which endpoint** can we use to find the token/GB ratio that is recorded on the blobber smart contract.
Maybe @cnlangzi can help us here?

I summarize the slack thread for clarity:

**Me:**
"it seems like `free_from_blobber_stake_stats` represents tokens, not bytes"
**Saswata:**
"Each blobber has a token/GB on the smartcontract so it should be api call"

Which API should we call to know that token/GB ratio?

**Comment by shaktals** [comment]
@Kishan-Dhakan has confirmed on [slack](https://0chain.slack.com/archives/G01FYNN6DK4/p1643095905125400?thread_ts=1643046219.123200&cid=G01FYNN6DK4) that the `free` prop is actually given in bytes, so the explorer flow is already correct and we can close this.
