### ISSUE TITLE
zcnsc: Improve performance.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#800]
Smart contract performance needs to be kept below 50ms.

The main problem could be GetAuthorizerNodes. We can't handle unbounded lists of objects in the MPT.

**Comment by Dmdv** [comment]
Results for 100 000 wallets

<img width="318" alt="image" src="https://user-images.githubusercontent.com/805238/147507522-544e087e-e002-4a8f-a3cd-631ac7c28e38.png">
