### ISSUE TITLE
Carefully use RequestEntityFromAll() to get request from miners or sharders

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#807]
The following requests would call the `sharders.RequestEntityFromAll()` to fetch data from sharders:

- `FBRequestor`
- `LatestFinalizedMagicBlockRequestor`

This will cause performance issue when network size increased. A sharder will get requests from all miners every time when the function is called. We should do it like the way we do for miners, which means send request to small part of the sharders first, and reach to new ones only when the previous requests are all failed.

**Comment by ma2b0043** [comment]
@peterlimg when can we expect to close this issue?
