### ISSUE TITLE
Challenges should fail after some time if they have not been processed

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/0chain#81]

**Comment by shravanshetty1** [comment]
Current flow:
1) Blobber gets challenge from smart contract
2) Blobber process challenge and validates it through validators
3) Challenge is sent back to smart contract. If the challenge has valid verification tickets .etc. the funds are released.

Currently smart contract tracks the time, if blobber takes longer than the challenge_completion_time to process the challenge the smart contract treats the challenge as failed and does not realease funds.

However on the blobber side there is no code that tracks if the challenge_completion_time has been exceeded. So it will keep processing it.

If challenge is canceled on blobber end and not sent back, smart contract will not be able to enforce blobber penalty .etc.

Please suggest solutions, this seems like an architecture issue.

**Comment by guruhubb** [comment]
Yes SC should fail challenge if they don't receive from blobber. This can be triggered via any crud action, which is the same process for generating challenge.

**Comment by Sriep** [comment]
Currently on reading the code, what it appears to do is:
1. Blobber polls smart contract for challenges.
2. Blobber never gets around to completing a challenge.
3. At some time after allocation expiration + challenge completion time:
4. [The allocation is finalised](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1253). (I think this is ./zwallet alloc-fini)
5. While finalising the allocation, all open challenges are failed and penalties and payments paid.

**Comment by Sriep** [comment]
Suggested changes.

1. Challenges that have exceeded the `challenge_completion_time` to be removed from challenges sent to the blobber.
2. Currently, financial changes are done on `challenge response` or on `allocation finalisation`. This could be changed.
3. Unit test written to ensure the calculations are correct.

**Comment by Sriep** [comment]
Purposed solution:
1. Unit test for `finalizeAllocation` to check it distributes payments correctly.
2. Update blobber to filter the list of challenges returned by `/openchallenges` for timed out challenges.
3. Unit test for blobber changes.

Going forward consider having a smart contract that performs housekeeping tasks like keeping challenge information and payments as up to date as possible.

**Comment by Sriep** [comment]
Closing. Replaced by 0chian issue https://github.com/0chain/0chain/issues/198 and blobber issue https://github.com/0chain/blobber/issues/93
