### ISSUE TITLE
Miner Sharder /_diagnostics data on JSON.

### ISSUE THREAD

**Issue by krishnemd** [0chain/0chain#824]
Explorer needs {{miner, sharder}}/_diagnostics data on a JSON format. A clone of present html type response but on JSON.

**Comment by samtholiya** [comment]
@chauchausoup would be great if you could mention the expected JSON format.

**Comment by krishnemd** [comment]
@samtholiya the same html data on JSON. You can decide format on your own unless all data are there as of html on JSON its fine.

**Comment by Sriep** [comment]
We should convert all REST API endpoints to return in JSON format. However, that will require changes to zbox, zwallet and system tests.
