### ISSUE TITLE
Event db: Miner and sharder block rewards.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#830]
We need two new tables for miner and sharder block rewards. This should be done in step with https://github.com/0chain/0chain/issues/829 which would probably be considered a blocker. Currently rewards are paid in [payFees](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/fees.go#L396) but that will might change with https://github.com/0chain/0chain/issues/829.

We might add extra fields to these table lager.

| MinerBlockReward 	| Field 	| Note                         	|
|------------------	|-------	|------------------------------	|
| BlockId          	| uint  	| foreign key into block table 	|
| MinerId          	| uint  	| foreign key into miner table 	|
| Reward           	| int64 	|                              	|

| SharderBlockReward 	| Field 	| Note                         	|
|------------------	|-------	|------------------------------	|
| BlockId          	| uint  	| foreign key into block table 	|
| SharderId          	| uint  	| foreign key into sharder table 	|
| Reward           	| int64 	|                              	|

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by avanaur** [comment]
Looked into doing this together with #829. Cannot progress yet as #829 is best done after #1025

**Comment by iamrz1** [comment]
Still blocked by [Block rewards for miners and sharders](https://github.com/0chain/0chain/issues/829)

**Comment by dabasov** [comment]
Implemented in Minted
