### ISSUE TITLE
EventDb: BlobberBlockRewards table

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#831]
Table to hold blobber block rewards paid every block. This is dependant on https://github.com/0chain/0chain/issues/753.

| BlobberBlockReward 	| Field 	| Note                           	|
|--------------------	|-------	|--------------------------------	|
| BlockId            	| uint  	| foreign key into block table   	|
| BlobberId          	| uint  	| foreign key into blobber table 	|
| Reward             	| int64 	|                                	|
| BlobberStake       	| int64 	| total stake                    	|
| BlobberFees        	| int64 	| service fees                   	|

The table contains the information used in determining the block reward.

**Comment by Sriep** [comment]
We want endpoints to support
```sql
select avg(reward) from blobber_block_reward where block_id < N and block_id > N-60 and blobber_id = BlobberID
```
and
```sql
select avg(BlobberStake) from blobber_block_reward where block_id < N and block_id > N-60 and blobber_id = BlobberID
```

**Comment by Sriep** [comment]
```sql
select avg(reward) from blobber_block_reward where block_id < N and block_id > N-60
```
and
```sql
select avg(BlobberStake) from blobber_block_reward where block_id < N and block_id > N-60 and Reward >0
```

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
Added reward table in https://github.com/0chain/0chain/pull/1870.
