### ISSUE TITLE
Event db endpoints should only run on the sharder

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#833]
Event database endpoints should only be run from the sharder. Attempting to run them on a miner should return an error, and they should not be run.

**Comment by samtholiya** [comment]
Need more details, how can we ensure that endpoints are hit by miners or sharders.

**Comment by Sriep** [comment]
They are being called because [GetSCRestPoints](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state_handler.go#L151) is called from both `miner/miner.go` and `sharder/sharder.go` main functions.

Probably it is best to have different [SetupStateHandlers](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state_handler.go#L21) for [miner.main()](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/miner/miner/main.go#L407) and [sharder.main()](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/sharder/sharder/main.go#L396)

I'll check on slack that there are no problems with this.

**Comment by kushthedude** [comment]
Depends on https://github.com/0chain/0chain/issues/857

**Comment by ma2b0043** [comment]
@Sriep @samtholiya @kushthedude when can we expect to close this issue?

**Comment by avanaur** [comment]
@Sriep can you clarify what are the `event db` endpoints? Are these referring to all endpoints under `/v1/screst/*` therefore all smart contract endpoints? Then if the endpoint is accessed through miner, should expect the 404 error?

**Comment by Sriep** [comment]
This should be fixed as part of swagger documentation https://github.com/0chain/0chain/pull/1134.
