### ISSUE TITLE
Event db: new Authorizer table

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#842]
New table for zcnsc.authorizer object, plus endpoint. Events need to be emitted in zcnsc whenever an authorizer is added or changes. Code in Event database to handle new events. A REST API endpoint to return autorizers.

Table no complete, additional fields will be needed.

| Authorizer   	| type   	|
|--------------	|--------	|
| AuthorizerId 	| string 	|
| Balance      	| uint   	|
| Url          	| string 	|

**Comment by Dmdv** [comment]
@Sriep Working on it

**Comment by Dmdv** [comment]
Attached 
https://github.com/0chain/0chain/pull/848

**Comment by Sriep** [comment]
Closed https://github.com/0chain/0chain/issues/784 which is a repeat of this.
