### ISSUE TITLE
viewChangePoolsWork run on VC:false cause BC stuck

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#85]
Check the changes here, https://github.com/0chain/0chain/commit/52b92356ffda66911b49e2ed2f35cdb0a5335e64#diff-6723731c1e90a62a21704463528[…]d7cfb4b2c30d5822aa5359fL419-R446.

The msc.viewChangePoolsWork would only run when block.Round == gn.ViewChange, while in this commit, it could also run when VC:false and do round reward. It is now repeatedly failed with the error of missing miner node: node not found  and seems no new block could be generated. (edited)

**Comment by peterlimg** [comment]
A new situation is that even the viewChangePoolsWork works well or it's not being called, the BC could still get stuck, as the block generation process repeatedly failed due to the error of `node not found`. After checking the miners state, find that only miner01 has the full MPT state db on LFB,  miner02 and miner03 have vary degree of missing nodes. Though, sharders all have full MPT dbs.

**Comment by guruhubb** [comment]
Perhaps miner should talk to sharders first to sync up state instead of other miners.

**Comment by peterlimg** [comment]
> Perhaps miner should talk to sharders first to sync up state instead of other miners.

Yes, I'll check how they sync up state. 

Also, I find the network two was stuck yesterday again. After checking the dumped mpt state of their last finalized block, I found the same situation: two miners have missing node err in db, one miner and two sharders have full state db.
