### ISSUE TITLE
Smartcontact to setup chain genesis

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#850]
We need a smart contract to run on the first round. Currenlty this is needed so genesisi miners can be sent to the Event database, as genesis miners do not use the `addMiner` smart contract.

1. Add a [CreateAddGenesisMiners](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/miner/protocol_block.go#L69) transaction somewhere around here.[Ger
2. Call the new CreateAddGeesisMiners in [GenerateBlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/miner/protocol_block_main.go#L228) if its the first round.
3. Add the new smart contract which will get the list of miners and emit events with their details.

This is needed for https://github.com/0chain/0chain/issues/790

**Comment by Sriep** [comment]
We have the workaround of adding a 
```go
if balances.GetBlock().Round  == 1 {
   do round one initlisation stuff ...
}
```
block to the payFees endpoint which is called every round.

**Comment by ssardana96** [comment]
@Sriep we verified this with [miner/sharder eventdb PR](https://github.com/0chain/0chain/pull/843) that genesis miners makes call to addMiner API and hence get registered.
Is this ticket about the same ?

If same, I guess then we don't have to do this as it is already happens.

**Comment by kushthedude** [comment]
Following issue is already handled in the sharder PR where we are getting the genesis miner since event the genesis miner uses the `SC_ADD_MINER`.
