### ISSUE TITLE
Choose REST API endpoint by genesis event database version

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#857]
For backward compatibility, we will need to choose between different endpoints depending on the build history of the chain.

Add a new immutable genesisEventDbVersion to global settings. Initialise this to a hardcoded value during genesis or the first block. Mayne in [miner.main](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/miner/miner/main.go#L47) and [sharder.main](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/sharder/sharder/main.go#L94).

Somewhere around [ExecuteRestAPI](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/smartcontract/handler.go#L24) we will need to get the start version of the chain. A StateContextI object is one of the EcecuteRestAPI input parameters so should be simple to get the EventDbVersion

[SmartContractInterface.GetRestPoints](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/smartcontractinterface/interface.go#L38) will need to be modified to take a version number parameter and return the endpoint list suitable for that version number. 

This will require modification to all smart contracts`GetRestPoint` implementations to support this change.
```go
type SmartContractInterface interface {
	Execute(t *transaction.Transaction, funcName string, input []byte, balances c_state.StateContextI) (string, error)
	GetRestPoints(version int) map[string]SmartContractRestHandler
	...
}
```

This can be considered a blocker for merging most Event Db changes.

We might also want to consider https://github.com/0chain/0chain/issues/796 in conjunction with this change. Which would mean splitting the `SmartContractInterface` into a `SmartContractInterface` and a `RestApiInterface`.

**Comment by Sriep** [comment]
1. Choose REST API endpoint by genesis event database version
2. Add a new setting, genesis_eventdb_version to global settings.
3. Do not set from 0cahin.yaml. Instead hard code the version and add that to the MPT global settings during genesis. Probably can add to viper settings now and wait for https://github.com/0chain/0chain/issues/687 to finish the job,
4. If the chain's code gets updated we will maintain a memory of the code used during chain genesis.
5. Each time we make an event dabatase code change that can effect backwead compatability increment this hard coded vale.
6. Each time we run an REST API call from GetSCRestPoint we get the genesis event database version from the settings in the MPT. balances.GetTrienode(Golabl_Settings_Key). https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/globals.go#L487
7. We enter this genesis event database version just got from the MPT into GetRestPoints(version).
8. We need to order endpoints by event database version. All preexisting endpoints set to version 0. Each new endpoints linked to the event database version in which they were added. Then some code in GetRestPoints to match the endpoints to the versions.

**Comment by Sriep** [comment]
We don't need this prior to mainnet. So this does not block any pre mainnet event database issues anymore.

**Comment by ma2b0043** [comment]
@Sriep if its a necessary of the mainnet, can you add "post-mainnet" label to this issue?

**Comment by Sriep** [comment]
Move backwards compatibility to a separate discussion.
