### ISSUE TITLE
Create foreign keys in WriteMarker table

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#859]
As other tables are created, create foreign keys to [WriteMarkers](https://github.com/0chain/0chain/issues/768) table

Foreign Keys already created:
- BlobberID

Foreign Keys pending:
- Client (User Table)
- AllocationId (allocation Table)
- TransactionId (transaction table)

**Comment by ma2b0043** [comment]
@ssardana08 when can we expect to close this issue?

**Comment by avanaur** [comment]
Added a [draft PR](https://github.com/0chain/0chain/pull/1220) for the two missing foreign keys.
Still blocked by #778 for FK to the User table.

**Comment by iamrz1** [comment]
Closed by https://github.com/0chain/0chain/pull/1500
