### ISSUE TITLE
Non converging VRF due to different round timeouts

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#86]
1. Start 4 miners, 1 sharder.
2. Bring miner2 down. BC should keep moving.
3. 15 seconds later bring miner3 down. BC stops.
4. Bring miner2 up (not miner3). BC gets stuck with no VRF changes with round timeouts. Generally a new round timeout should have new generators assigned with new VRF because you're using the counter increment to generate a new VRF.

**Comment by Sriep** [comment]
On Jun 13, 2020, at 8:32 AM, Saswata Basu <saswata@0chain.net> wrote:
Hey Siva,
I think the round timeout still has an issue in the case where half the miners are on one round, and the other half on another. I think we need to revise the algorithm to have the miners stay in the last or most popular timeout round and not increment it by one, otherwise its a race condition which will never get resolved. Thoughts?
thanks,
Saswata
```go
If (number of vrf tickets > threshold) {
  If (vrfs all same) 
      execute current code
  else sort popular vrf timeouts {
  if popularity rank is same
    select last timeout, add one to sync 
  else 
    select most popular timeout, add one to sync
  }
}
```

**Comment by Sriep** [comment]
Saswata Basu [6:54 PM] Max  [2:12 AM]
Here the file main.go, to demo converging timeout by using my method. 100 nodes start with random timeout [0; 100] and randome delay in the range of 3 sec. This is emulation of restartRound, because for each node it happen for itself timing.
And here Ken’s And Siva’s solution (ken.go). In that case ony 5 nodes converging from 100.
That mean that math method does not work. I suggest that use it in blockchain and build in is useless. And it does not matter how many rounds run. Because the problem with timeout appear only during the restartRound. Moreover, Kens method already has been checked and you have written that there is a problem in converging VRF share.
[Ken's method](https://0chain.slack.com/files/U012NSXAYH3/F018554LMLG/ken.go?origin_team=T9C1E9JEB&origin_channel=D01NYCVANLC)
[Max's main.go](https://0chain.slack.com/files/U012NSXAYH3/F017MF9TD6Y/main.go)
:01
There two implentations that we had regarding the timeout logic - ken’s code and Max’s code (current). I’m not sure if Ken’s code had a problem but I think Max’s code doesnt work either.

**Comment by Sriep** [comment]
[Ken's method](https://0chain.slack.com/files/U012NSXAYH3/F018554LMLG/ken.go?origin_team=T9C1E9JEB&origin_channel=D01NYCVANLC)
[Max's main.go](https://0chain.slack.com/files/U012NSXAYH3/F017MF9TD6Y/main.go)
:01
There two implentations that we had regarding the timeout logic - ken’s code and Max’s code (current). I’m not sure if Ken’s code had a problem but I think Max’s code doesnt work either.

**Comment by Sriep** [comment]
Added a cap to the value returned by IncrementTimeoutCount configured in 0chain.yanl. Capping the maximum number of timeout forces convergence. 

Fixed in https://github.com/0chain/0chain/pull/90/files and https://github.com/0chain/0chain/pull/91

**Comment by guruhubb** [comment]
With changes made subsequently by @peterlimg, this problem may have been fixed. Please test this again @Sriep ?

**Comment by Sriep** [comment]
Retested and could not reproduce the issue.
