### ISSUE TITLE
StoraageAllocation dependecy on allocation_pools table

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#879]
`allocationTableToStorageAllocation` WritePoolOwners needs to be populated from `allocation_pools` table
```sql
select user_id from allocation_pools where allocation_id = ? AND is_write_pool=true
```

To be done after #760

**Comment by ma2b0043** [comment]
@ssardana08 when can we expect to close this issue?

**Comment by rizary** [comment]
This need https://github.com/0chain/0chain/issues/1064 to be fixed first.

**Comment by iamrz1** [comment]
@dabasov WritePoolOwners have been removed from StorageAllocation permanently.
@Sriep is this a valid issue anymore? Or can we close it?

**Comment by dabasov** [comment]
not needed anymore
