### ISSUE TITLE
Zcnsc: Add Global settings to MPT smart contract

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#880]
The [global settings](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/zcnsc/models.go#L27) from zcnsc
```go
type GlobalNode struct {
	ID                 string        `json:"id"`
	MinMintAmount      state.Balance `json:"min_mint_amount"`
	PercentAuthorizers float64       `json:"percent_authorizers"`
	MinBurnAmount      int64         `json:"min_burn_amount"`
	MinStakeAmount     int64         `json:"min_stake_amount"`
	BurnAddress        string        `json:"burn_address"`
	MinAuthorizers     int64         `json:"min_authorizers"`
	MaxFee             int64         `json:"max_fee"`
}
```
need to kept in the MPT.

We can use the same method as settings for [other smart contracts](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/interestpoolsc/node.go#L16).

**Comment by Dmdv** [comment]
Completed in this PR https://github.com/0chain/0chain/pull/957
