### ISSUE TITLE
Zcns: Set Authoriser settings smart contract

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#881]
We need a new smart contract to set authoriser settings. 

Authorises need a new fee field, this is to be less than or equal to the global max_fee setting. We charge the user that fee when they convert zcn-native to zcn-erc and vice versa

This is similar to the [add_blober](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/blobber.go#L174) and [add_miner](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/miner.go#L31) endpoints from other smart contracts.

Also set and get any global zcnsc settings. If there are no global settings we can skip this.

Implementation steps:

- [x] 1. Get/Update global settings for zcnsc 
- [x] 2. Get/Update authorizer settings
- [x] 3. Add max_fee to settings

**Comment by Dmdv** [comment]
1. Get/Set global settings for zcnsc
2. Update authorizers settings fee <= max_fee

**Comment by Dmdv** [comment]
`global zcnsc settings` ready in https://github.com/0chain/0chain/pull/957
