### ISSUE TITLE
Transactions in event database should be searchable with client_id

### ISSUE THREAD

**Issue by samtholiya** [0chain/0chain#890]
https://0chain.slack.com/archives/C02QDMYFQJG/p1642022754110100?thread_ts=1641664353.058800&cid=C02QDMYFQJG

As per @shaktals comment, we need to add more capabilities to the transaction api from event database that will help them to search transactions in the event database by client_id

**Comment by shaktals** [comment]
> https://0chain.slack.com/archives/C02QDMYFQJG/p1642022754110100?thread_ts=1641664353.058800&cid=C02QDMYFQJG
> 
> As per @shaktals comment, we need to add more capabilities to the transaction api from event database that will help them to search transactions in the event database by
> 
>     1. metadata 
>     2. hash.

You're missing one search prop from my comment on slack.

**Comment by Sriep** [comment]
I think we should leave `GetTransactionByHashHandler` unchanged and add a new endpoint `GetTransactionByClientIdHandler`.

The two endpoints seem too different to combine. For example, their return types are different, one returns a transaction and the other a list of transactions.
