### ISSUE TITLE
Event DB: Update Stake in Validator table

### ISSUE THREAD

**Issue by dhruv0000** [0chain/0chain#894]
Sake fields of the Validator Table in EventDB will need to be updated in [stakePoolLock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L920) and [stakePoolUnlock](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L1000) and an event emitted.
Best done in conjunction with #587.

Should be done once the new rewards structure is built. [#741](https://github.com/0chain/0chain/issues/741#issuecomment-1008002060) #577

**Comment by ma2b0043** [comment]
@dhruv0000 when can we expect to close this issue?

**Comment by iamrz1** [comment]
Blocked by [Validators - remove if stake is too low](https://github.com/0chain/0chain/issues/587)

**Comment by dabasov** [comment]
check if validators stake pool is really working

**Comment by iamrz1** [comment]
Done in https://github.com/0chain/0chain/pull/1593
