### ISSUE TITLE
Foreign Keys to ReadMarker table

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#897]
| Event db ReadMarker | type   | ReadMarker   | type      | notes                              |
|---------------------|--------|--------------|-----------|------------------------------------|
| Client              | uint   | ClinetId     | string    | foreign key into user table        |
| AllocationId        | uint   | AllocationId | string    | foreign key into allocation table  |
| OwnerId             | uint   | OwnerId      | string    | foreign key into user table        |

Linked to #764

**Comment by samtholiya** [comment]
need https://github.com/0chain/0chain/pull/864 to complete before this can be continued

**Comment by ma2b0043** [comment]
@samtholiya when can we expect to close this issue?

**Comment by samtholiya** [comment]
@ma2b0043 this can be completed only after #864 is merged

**Comment by iamrz1** [comment]
Closed by https://github.com/0chain/0chain/pull/1493
