### ISSUE TITLE
WriteMarkers to substitute commit metadata

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#900]
- given a file name we should be able to get list of all WriteMarkers
- this needs to bring in a logic of storing filename with all writemarkers

As filename is a string which can change, I would not recommend to store as a field, but rather have a separate table with list of all filenames filenames linked at all places with an id.

dependency on https://github.com/0chain/blobber/issues/467
Slack thread https://0chain.slack.com/archives/C02QDMYFQJG/p1641483274009400

**Comment by ma2b0043** [comment]
@ssardana08 when can we expect to close this issue?
