### ISSUE TITLE
Eventdb Transaction should be searchable using metadata

### ISSUE THREAD

**Issue by samtholiya** [0chain/0chain#901]
https://0chain.slack.com/archives/C02QDMYFQJG/p1642022754110100?thread_ts=1641664353.058800&cid=C02QDMYFQJG

Transaction by hash is already present
ClientID is supposed to be done by ticket https://github.com/0chain/0chain/issues/890

With this, we expect transaction to be searchable - queried by filename

**Comment by ma2b0043** [comment]
@samtholiya when can we expect to close this issue?

**Comment by PratikDhanave** [comment]
@ma2b0043 I like to work on this

**Comment by melkon98** [comment]
@samtholiya is this issue not completed yet? 
If not, please answer to this question

What do we actually want to be returned?

List of transaction ids.
List of file names
WriteMarkers
Something else

**Comment by dabasov** [comment]
https://github.com/0chain/web-apps/issues/472

**Comment by lawRathod** [comment]
We may be able to close this issue since https://github.com/0chain/0chain/issues/1365 is already merged in staging??

What do you think?
@dabasov @Sriep
