### ISSUE TITLE
Total value locked.

### ISSUE THREAD

**Issue by krishnemd** [0chain/0chain#903]
UI requires the given values for 0chain in general rather than any specific MSB. And as per the requirement here is how total value locked is calculated.

`Total Value Locked:  (Total Staked ZCN (Includes delegated + staked on blobber)) + Total Locked ZCN) * ZCN Price`

With reference to the requirement above we need three API endpoints to get:

1) Total Staked ZCN ( including delegated pool)
2) Total ZCN staked on Blobber
3) Total Locked ZCN

**Comment by ma2b0043** [comment]
@chauchausoup when can we expect to close this issue?

**Comment by krishnemd** [comment]
@ma2b0043 the requirement depends on 3 new endpoints. For a particular blobbers we do need the above mentioned stats. For when to expect I think @Sriep can enlighten on it.

**Comment by lawRathod** [comment]
The following info will be available in snapshot table https://github.com/0chain/0chain/pull/1475:
* Total Staked ZCN 
* Total Locked ZCN
* Total locked ZCN on blobber

**Comment by manasnisar** [comment]
@dabasov This one's is already there. Should I close it?
