### ISSUE TITLE
Read Write data in realtime for each blobber.

### ISSUE THREAD

**Issue by krishnemd** [0chain/0chain#904]
UI requires to show the read write action in realtime in a map.

Do /latestReadMarker and /latestWriteMarker when implemented be able to contribute to the requirement of read write data count for each blobber ?
If so then we need to publish the /latestReadMarker, /latestwriteMarker and the required party will subscribe to it ?

**Comment by samtholiya** [comment]
Just fyi
In favour of general api we have implemented writeMarker and readMarker generic api's https://github.com/0chain/0chain/pull/995

**Comment by ma2b0043** [comment]
@chauchausoup when can we expect to close this issue?

**Comment by Sriep** [comment]
Looks like  repent of https://github.com/0chain/0chain/issues/791

**Comment by Sriep** [comment]
Can we close this issue?

**Comment by Sriep** [comment]
Closing as repeat of https://github.com/0chain/0chain/issues/791 closed by https://github.com/0chain/0chain/pull/1138
