### ISSUE TITLE
New allocation request

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#909]
# Allocation

This represents a commitment to store data for a user. This is passed on to a set of blobbers who will save user data when requested, and allow access to view that data. 

## New allocation

The `new_allocation_request` endpoint creates an allocation. The following parameters are used to define the transaction.

| Parameter                     	| Description                                                                                                                	| Notes                                       	|
|-------------------------------	|----------------------------------------------------------------------------------------------------------------------------	|---------------------------------------------	|
| selected blobbes              	| A string list of blobber ids to use for storing data. The number of blobbers used will be data shards + parity shards      	| https://github.com/0chain/0chain/issues/668 	|
| data shards                   	| Effects uplaod and downlad speeds.  With parity shards give number of blobbers                                             	|                                             	|
| parity shards                 	| Effect availability.  With data shards give number of blobbers                                                             	|                                             	|
| owner                         	| Owner id , to be used when funding an allocation for another user.                                                         	|                                             	|
| owner public key              	| Public key of owner if funding for another user.                                                                           	|                                             	|
| max challenge completion time 	| Used to filter blobbers.                                                                                                   	|                                             	|
| read price range              	| Max and min read price used to filter blobbers.                                                                            	|                                             	|
| write price range             	| Max and min write price used to filter blobbers.                                                                           	|                                             	|
| expire                        	| Expiration time. Once set this can not be reduced.                                                                         	| https://github.com/0chain/0chain/issues/828 	|
| size                          	| Size of data reserved. Used to filter blobbers.                                                                            	|                                             	|
| mutablity                     	| Boolean, indicates data cannot be modified once downloaded.  Once set to immutable this setting cannot be changed further. 	| https://github.com/0chain/0chain/issues/828 	|
| who can extend                	| Boolean, indicates whether only the owner can extend the allocation period, or whether anyone can.                         	| https://github.com/0chain/0chain/issues/828 	|
| can upload                    	| Boolean indicates whether files can be uploaded to the allocation.                                                         	| https://github.com/0chain/0chain/issues/828 	|
| can delete                    	| Boolean indicates whether files can be deleted from the allocation.                                                        	| https://github.com/0chain/0chain/issues/828 	|
| can update                    	| Boolean indicates whether files controlled by this allocation can be updated.                                              	| https://github.com/0chain/0chain/issues/828 	|
| can move                      	| Boolean indicates whether files controlled by this allocation can be moved                                                 	| https://github.com/0chain/0chain/issues/828 	|
| can copy                      	| Boolean indicates whether files controlled by this allocation can be copied                                                	| https://github.com/0chain/0chain/issues/828 	|
| can rename                    	| Boolean indicates whether files controlled by this allocation can be renamed                                               	| https://github.com/0chain/0chain/issues/828 	|

## Select allocaion blobber

We provide a REST API endpoint. This will take the blobber filter fields in the table above and select a list of suitable blobbers for a new allocation request. https://github.com/0chain/0chain/issues/681.

| Parameter                     	| Filter                                                                        	| Notes                                       	|
|-------------------------------	|-------------------------------------------------------------------------------	|---------------------------------------------	|
| data shards                   	| number of blobbers to select = data shards + parity shards                    	| https://github.com/0chain/0chain/issues/668 	|
| parity shards                 	| number of blobbers to select = data shards + parity shards                    	|                                             	|
| max challenge completion time 	| blobber's challenge completion time must be <= than this                      	|                                             	|
| read price range              	| blobber's read price in requested range                                       	|                                             	|
| write price range             	| blobber's write price in request reange                                       	|                                             	|
| size                          	| blobber's staked capacity less existing commitments sufficient for allocation 	| https://github.com/0chain/0chain/issues/781 	|
| diversity                     	| blobber's location. Exact details to be decided.                              	| https://github.com/0chain/0chain/issues/681 	|

We will have a REST API endpoint that will do a query on the blobber table in the events DB. It will use the tabulated filters in the query and order by some parameters. The first `data_shards + partity_shards` blobbers fond by the query are returned by the API call. The user can then uses this list of blobbers as input into the new allocation request.

The `zbox newallocation` CLI will hide this process from the user. Sending the select blobber REST API call before adding the new allocation transaction. 

## Related issues

https://github.com/0chain/0chain/issues/734, https://github.com/0chain/0chain/issues/668, https://github.com/0chain/0chain/issues/592, https://github.com/0chain/0chain/pull/684, https://github.com/0chain/0chain/issues/781, https://github.com/0chain/0chain/issues/681 and https://github.com/0chain/0chain/issues/828.

**Comment by ma2b0043** [comment]
@sriep when can we expect to close this issue?

**Comment by peterlimg** [comment]
Fixed by #1229
