### ISSUE TITLE
New mints table in the event databse

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#910]
A new mint database table. For each block, this will hold the total number of tokens minted during that block.

Each time tokens are [minted](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state/state_context.go#L145) emit an event. Total up the `mint events` each block and add a row to the mint table.

We might expand this later.

We will also want an endpoint to return the sum of the mints for a given range of blocks.

**Comment by samtholiya** [comment]
@Sriep 
1. What do you mean by `the total number of tokens minted during that block` Which location exactly. There are multiple places we are adding mint. How to identify
2. What do you mean by `total up the mint events and then adding them to the mint table` which mint belong to the same group to be total? 
3. I guess the answers to the above two questions should also answer holds the answer to ` the total number of tokens minted during that block`

Is there a table schema in your mind that you can post

**Comment by Sriep** [comment]
During a block [StateContextI.AddMint](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state/state_context.go#L145) will be called some number of times. We wish to total the amount of these [mint's amount field](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/state/mint.go#L15)  and save that total to the event database.

It might be easier to add a `minted` column to the block table. Probably easiest to emit events on AddMint, then modify the event db processing code to keep totals for the current and previous block, and include when adding a row to the block table.

We will then need an endpoint that returns the sum of these minted fields between two block numbers.

**Comment by samtholiya** [comment]
Took some time but What if the sequence is :
Block A added a mint
Block B added a mint
Block A added a mint
Block B added a mint
Block A added a mint
Block B added a mint

In the case above we might have to calculate multiple times the previous mint total and next mint total
I would say calculating total while reading is much effective in terms of I/O and extra compute

**Comment by Sriep** [comment]
All the events for block `N` are all handled before any of the events for block `N+1`. Hence the scenario I think you are suggesting can't happen. https://github.com/0chain/0chain/issues/757

If blocks are handled out of order that is a bug that has to be fixed elsewhere.

**Comment by ma2b0043** [comment]
@Sriep @samtholiya when can we expect to close this issue?

**Comment by Sriep** [comment]
We should combine with https://github.com/0chain/0chain/issues/1390 to store mints in the new snapshot table.

**Comment by lawRathod** [comment]
Will be closed in https://github.com/0chain/0chain/pull/1475

**Comment by manasnisar** [comment]
@dabasov Already there. I see a `total_mint` column in snapshots table. Should I close this?
