### ISSUE TITLE
Custom icon and website link on blobbers/miners/sharders config, and ability for clients to read it

### ISSUE THREAD

**Issue by shaktals** [0chain/0chain#911]
As per demand of the new `block-explorer` being built, we need to add new props/fields on MSBs configs, that will be used for URLs of:

- custom icon
- website link

Then we need the ability to read those props when fetching MSBs details on clients.

**Comment by shaktals** [comment]
ping @moldis

**Comment by shaktals** [comment]
ping @Sriep

**Comment by ma2b0043** [comment]
@shaktals when can we expect to close this issue?

**Comment by shaktals** [comment]
@ma2b0043 is the feature ready?

**Comment by dabasov** [comment]
after all we decided to add this data to the 0box, so when blobber is created this data will be stored there.

**Comment by iamrz1** [comment]
@dabasov do we need to keep this issue open?

**Comment by rizary** [comment]
closed and move to https://github.com/0chain/0box/issues/255
