### ISSUE TITLE
New reward table for event database

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#912]
New reward table for event database. This will contain the tokens minted in `pay_me` transactions. 

We will want the 
- block number
- user wallet id
- pool id
- amount

Emit an event during `pay_me` transactions with the details. 

We want a REST API endpoint that will give the sum of pay_me transaction payments for a range of block numbers.

This issue is blocked by [Stake holder rewards pools and pay_rewards endpoint](https://github.com/0chain/0chain/issues/774)

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?

**Comment by iamrz1** [comment]
Closed by https://github.com/0chain/0chain/pull/1175
