### ISSUE TITLE
Smart contract return 400 for every possible error

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/0chain#92]
Should return appropriate status code

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |
