### ISSUE TITLE
Blobber info to be added on /getblobber

### ISSUE THREAD

**Issue by krishnemd** [0chain/0chain#921]
UI do have a provision to show the following blobber related information on the individual blobber page which I guess is not present at the moment. 

1) Blobber Logo Image
2) Blobber Name
3) Blobber description (300 chars)

4) **_Blobber Commission_**: Question is that, how do we calculate the blobber comission and what are the metrics under which the comission is assigned to a blobber.

5) **_No of nodes per blobber_** : For this I think when we do https://beta.0chain.net/sharder01/v1/screst/:id/getblobbers
 request it shows us 6 nodes on each node being a blobber. So the question arrises if a node a single blobber or a single blobber has multiple nodes throughout the globe ?
 
6) **Website** link or **reference** link of the blobber.

**Comment by Sriep** [comment]
https://github.com/0chain/blobber/issues/514 is a blobber issue that this depends on.

**Comment by ma2b0043** [comment]
@chauchausoup when can we expect to close this issue?

**Comment by krishnemd** [comment]
@ma2b0043 it depends on the above mentioned issue.

**Comment by peterlimg** [comment]
Closed by #1083
