### ISSUE TITLE
How much data is stored on the network ?

### ISSUE THREAD

**Issue by krishnemd** [0chain/0chain#922]
UI requires the amount of data stored on the network.  If there is some sort of general info page of a given network then lets add this filed in there or if we have to create it from scratch then we may add similar other fields like total ZCN staked on the network, [total value locked on network](https://github.com/0chain/0chain/issues/903), no of MSB on the network, uptime of the network etc.

**Comment by Sriep** [comment]
Also https://github.com/0chain/0chain/issues/787

**Comment by krishnemd** [comment]
Closing this in favour of https://github.com/0chain/0chain/issues/787
