### ISSUE TITLE
Add new API latestwritemarker

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#925]
`/latestwritemarker` to know the value in explorer app "Last time an allocation was written/read from." 
Add it as a RestHandller in [SmartContract](https://github.com/0chain/0chain/blob/9c78b97165efa9fc7ee415dcf04fca4d2e8cc03e/code/go/0chain.net/smartcontract/storagesc/sc.go#L48)

**Comment by Sriep** [comment]
I assume we can use the first WriteMarker returned when ordered by decreasing row timestamp. I think we want the same for ReadMarkers as well.

**Comment by ssardana96** [comment]
@Sriep I was thinking that we should plan some API like - have skip, sort, limit in API so that we can fetch any writemarker
and always send `total_markers` so that UI/client will always knows the possible values it can have. (cc: @samtholiya )

**Comment by ssardana96** [comment]
@chauchausoup @shaktals what are your thoughts on this:
do we need an API very specific to latestwritemarker?
or I was thinking to design an API generic like /writemarker where we can have params
Latest WM can then be achieved by /writemarker?sort=-1&limi=1&skip=0

**Comment by shaktals** [comment]
We don't have a hard demand for a specific endpoint to retrieve the latest WriteMarker.

On the other hand, as @Sriep mentioned if we can just order the results by timestamp, and have sort of pagination, it should be enough for us.

**Comment by chauchausoup** [comment]
> 

The demand is of :
`Last time an allocation was written/read from.`
I think the pagination method will let us achieve it.

**Comment by krishnemd** [comment]
> @chauchausoup @shaktals what are your thoughts on this: do we need an API very specific to latestwritemarker? or I was thinking to design an API generic like /writemarker where we can have params Latest WM can then be achieved by /writemarker?sort=-1&limi=1&skip=0

The demand is of :
`Last time an allocation was written/read from.`
I think the pagination method will let us achieve it.
