### ISSUE TITLE
Swagger documentation

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#926]
We wish to provide documentation of the new REST API endpoints.

We now plan to use swagger to provide in-code documentation. Set up the initial OpenAPI/swagger framework. 

A problem here is that swagger is mainly `Design first`, and we have inherited a `code first` code base. So there is will be some pain in setting up the initial documentation. We don't necessarily need to complete all the documentation here but should have enough examples so others can fill in the gaps.

This might require reorganising of event database endpoints. Possible putting in a separate package.

**Comment by ma2b0043** [comment]
@Sriep when can we expect to close this issue?
