### ISSUE TITLE
Eventdb allocation - curator mapping

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#929]
[Curators](https://github.com/0chain/0chain/blob/b70155c80d54f5df4ef4eb9bb0552d9d7bdf574a/code/go/0chain.net/smartcontract/storagesc/models.go#L601) in allocation struct should not be stored in allocation table, which is happening #867 

This field in `allocationTableToStorageAllocation` should be populated by curator table https://github.com/0chain/0chain/issues/762
remove curators from `storageAllocationToAllocationTable`

```sql
SELECT curator_id FROM curators WHERE allocation_id = ?;
```

**Comment by iamrz1** [comment]
Right, table `curators` with allocation_id as the `foreign_key` to look them up.
