### ISSUE TITLE
Blocker on UserTable

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#933]
to mark UserTable: Eventdb #778 to completion, we need to figure out how to emit event from:
- [PutClient](https://github.com/0chain/0chain/blob/6af8438d63636e08e1dd19f41ccc4143c4fd4a3b/code/go/0chain.net/chaincore/client/entity.go#L291)
- [GetClient](https://github.com/0chain/0chain/blob/6af8438d63636e08e1dd19f41ccc4143c4fd4a3b/code/go/0chain.net/chaincore/client/entity.go#L272)

reference PR: #864

**Comment by ssardana96** [comment]
@Sriep this table is simple to add once the blocker is removed.

**Comment by ma2b0043** [comment]
@ssardana08 when can we expect to close this issue?

**Comment by samtholiya** [comment]
done in commit on the branch
should we close this?
