### ISSUE TITLE
Description field for providers.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#938]
Providers should have a description field. 

1. Add a new Description field to the `.yaml` settings for miner, sharder, blobber, validator and provider.
2. Add to a new `description` field to the input to `add_miner`, `add_sharder`, `add_blober`, `add_validator` and `add_authoriser`. For miners and blobbers we can rename the existing `short_name` field. 
3. Also add the `description` field in two to the input to the `update_<provider>_setting` smart contracts. 
4. Add a new `description` column to the miner, sharder, blobber, provider and validator event database table. 
5. Add the new description field to the event emitted from the `add_provider` and `update_provider_settings` smart contracts.

**Comment by Sriep** [comment]
Repeat of https://github.com/0chain/0chain/issues/921

**Comment by ma2b0043** [comment]
@sriep when can we expect to close this issue?

**Comment by Sriep** [comment]
Added to blobbers in https://github.com/0chain/0chain/pull/1083, we now want to move to event database. Plus add for miners, shaders, validators and authorisers.
