### ISSUE TITLE
Use allocation id as foreign key to allocations in curator table

### ISSUE THREAD

**Issue by amanjain97** [0chain/0chain#952]
https://github.com/0chain/0chain/pull/899#discussion_r790730118_

**Comment by kushthedude** [comment]
@amanjain97 Do you think we can handle this as part of #929?

**Comment by ma2b0043** [comment]
@amanjain97 when can we expect to close this issue?

**Comment by iamrz1** [comment]
Closed. First added in https://github.com/0chain/0chain/pull/976, later integrated to staging as part of https://github.com/0chain/0chain/pull/1054
