### ISSUE TITLE
Transaction: cost

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#974]
## Abstract
Block execution time can vary significantly depending on amount and type of transactions included into it. Currently block size is limited by amount of transactions and byte size but verification timeout is not estimated and limited. Different functions of smart contracts require different amount of CPU time for execution. The amount of operations, such as  MPT access, computation of cryptographic functions, all can significantly increase CPU usage. Malicious miner can group computational heavy transactions in single block and cause block verification timeout. 
Naive timing out of execution does not help much, if during block verification one transaction is executed on fast miner and the same transaction is timed out on slow one, than network can split and no progress will be made on this round, causing the restart of the round. 

## Proposal
To limit the CPU usage capacity we suggest to propose transaction cost. Cost will be calculated based on CPU time usage, spent by transaction execution. The cost can be defined by static table: for each `smart_contract.operation` an abstract number, for example, `zcn.mint: 1000` and `zcn.burn: 800`. Cost will be calculated empirically for every operation and will be added to the  sc.yaml config. 
Max block cost will be defined in 0chain.yaml.
```
  block:
    max_block_cost: 100000
```

### Rationale 
Cost will help to avoid block verification timeout, since there is a strong correlation between cost and execution time. Knowing block total cost will allow to choose Delta, round timeout and smart contract execution timeout more precisely, which in order will allow to reduce finality time dispersion. 

### Block generation
Block generation will stay the same with only new cost limit added.  Transactions will be still ordered by fee and, if generator won't be able to pick transaction because of cost limit, generator will skip it and will try to pick the next one.

### Block verification
Just before state computation step the new step will be added. Miner will run through transaction list and compute total cost of the block. In case total cost is above the limit, this block will be rejected before state computation even starts.

### Incentivizing
In general, clients should be incentivized to execute high cost transactions less often than low cost one, like transfer. It can be easily incentivized, for example, by adding an extra fee `extra_fee = cost*weight` to transaction fee, similar to how gas works in Ethereum. It is not a part of this proposal and needs further discussion

**Comment by dabasov** [comment]
### Implementation
**Constants**
Cost for every smart contract func is given in sc.yaml file. as a string:int map. Here is the example for faucet
```
  faucetsc:
    owner_id: 1746b06bb09f55ee01b33b5e2e055d6cc7a900cb57c0a3a5eaabb8a0e7745802
      ...
    cost:
      update-settings: 100
      pour: 100
      refill: 100
```
In 0chain.yaml max cost for a block is given: `serverchain.block.max_block_cost: 10000`
Owner of the smart contract should be able to updated the costs of funcs, currently it is not implemented yet.

**Block generation**
When transactions are picked from the tx_pool, estimator calculates cost of current block and checks whether calculated cost does not exceeds `max_block_cost` limit. If limit is reached no more transactions with not zero cost are picked. 
Note: to guarantee that mandatory transactions are added, their cost must be equal to zero, currently 0 `cost have payFees`, `pay_blobber_block_rewards`, `commit_settings_changes`

**Block verification** 
To verify block, miner calculates its cost as a sum of costs of all transactions. It is reasonable to calculate cost before state is calculated, just to guarantee that block will be calculated in time. If cost of the block exceeds `serverchain.block.max_block_cost: 10000` its verification fails.

**Comment by peterlimg** [comment]
Close via #1006
