### ISSUE TITLE
Send events to event database when we complete block stake

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#993]
https://0chain.slack.com/archives/C01GMABG2T1/p1644361635068779?thread_ts=1644296899.482209&cid=C01GMABG2T1

We should not execute insert events to db transaction when we compute block state (we can collect the events instead, like what we do for the MPT state). We should only do the db insert action when this block is finalized, otherwise we will see this error when two blocks for the same round get executed or one block executed twice due to round restarting.

**Comment by peterlimg** [comment]
Closed by #1059
