### ISSUE TITLE
updateallocation: invalid size validation is not added

### ISSUE THREAD

**Issue by princeparmar** [0chain/0chain#997]
UPDATEALLOCATION:
It just let me decrease allocation size BELOW the amount stored in the allocation. Also it let me do it with --lock 0
https://0chain.slack.com/archives/GREHVKQKS/p1644556772275659?thread_ts=1644426678.837979&cid=GREHVKQKS

Add validation that allocation size cannot be updated to less than amount stored in allocation
Add --lock 0 validation

**Comment by ma2b0043** [comment]
@princeparmar when can we expect to close this issue?
