### ISSUE TITLE
Conductor: fix start_lock && unlock directives

### ISSUE THREAD

**Issue by MurashovVen** [0chain/0chain#998]
The conductor's lock/unlock mechanism does not work properly: when a miner is locked it only stops registering miner's wallet.
Need to fix it.

**Comment by ma2b0043** [comment]
@MurashovVen when can we expect to close this issue?

**Comment by fabioDMFerreira** [comment]
@dabasov which actions should the directive lock?

**Comment by fabioDMFerreira** [comment]
I guess this issue is resolved. @dabasov please confirm.

Documentation says
```
start_lock - starts the list of nodes but lock them such that the nodes do nothing (eg. does not sign, does not generate blocks)

unlock - update the state of the list of nodes to be no longer locked
```

Although we aren't blocking the blocks generation we are preventing the starting of the next round in the next place
```
func (mc *Chain) moveToNextRoundNotAhead(ctx context.Context, r *Round) {
	mc.moveToNextRoundNotAheadImpl(ctx, r, lockChainIfConfigured)
}

func lockChainIfConfigured() {
	for {
		if !crpc.Client().State().IsLock {
			break
		}

		<-time.NewTimer(time.Microsecond * 200).C
	}
}
```
The next round only starts after the unlocking. This means the nodes can't do anything.
