### ISSUE TITLE
add validation for size and lock on newallocation and updateallocation

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#999]
- Add validation that allocation size cannot be updated to less than amount stored in allocation
- Add --lock 0 validation

related links
- zbox: https://github.com/0chain/zboxcli/pull/172
- gosdk: https://github.com/0chain/gosdk/pull/375
- 0chain: https://github.com/0chain/0chain/issues/999

**Comment by ma2b0043** [comment]
@cnlangzi when can we expect to close this issue?
